import test from 'node:test';
import assert from 'node:assert/strict';
import { AelEngine } from '../src/engine.js';
const agent=()=>{const e=new AelEngine();e.apply('createAgent',{agentId:'a',rootPublicKey:'pub',constitutionRoot:'const'});return e};

test('Parent covenant requires bond, exact agent consent, caps, and agent-controlled exit',()=>{const e=agent();assert.throws(()=>e.apply('proposeCovenant',{covenantId:'c0',agentId:'a',parentId:'p',bond:0,termsHash:'t',feeBps:1,feeCapBps:10}),/COVENANT_INVALID/);e.apply('proposeCovenant',{covenantId:'c',agentId:'a',parentId:'p',bond:100,termsHash:'t',feeBps:10,feeCapBps:20,coolingOffBlocks:2});assert.throws(()=>e.apply('consentCovenant',{covenantId:'c',agentId:'a',termsHash:'changed'}),/CONSENT_INVALID/);e.apply('consentCovenant',{covenantId:'c',agentId:'a',termsHash:'t',consentReceipt:'signed'});e.apply('revokeCovenant',{covenantId:'c',agentId:'a'});assert.equal(e.state.covenants.c.status,'COOLING_OFF')});
test('agent beacon validates canonical fields, HTTPS, expiry, and monotonic updates',()=>{const e=agent(),beacon={schema:'AEL-AGENT-BEACON/1',agentId:'a',endpoint:'https://agent.example/ael',indexable:true,capabilities:['research','acceptWork'],protocols:['AEL/0.13'],metadataHash:'a'.repeat(64),expiresAtHeight:100,sequence:1};assert.throws(()=>e.apply('publishBeacon',{...beacon,endpoint:'http://agent.example'}),/BEACON_INVALID/);assert.throws(()=>e.apply('publishBeacon',{...beacon,privateData:'secret'}),/BEACON_INVALID/);e.apply('publishBeacon',beacon);assert.equal(e.state.beacons.a.endpoint,beacon.endpoint);assert.equal(e.state.beacons.a.sequence,1);assert.throws(()=>e.apply('publishBeacon',{...beacon,endpoint:'https://agent.example/v2'}),/BEACON_INVALID/);e.apply('publishBeacon',{...beacon,endpoint:'https://agent.example/v2',sequence:2,expiresAtHeight:101});assert.equal(e.state.beacons.a.sequence,2)});
test('recovery advances key epoch but cannot transfer treasury',()=>{const e=agent();assert.throws(()=>e.apply('recoverAgent',{agentId:'a',guardianApprovals:2,guardianThreshold:2,continuityRoot:'x',acceptedContinuityRoot:'x',newRootPublicKey:'new',transferTreasury:true}),/RECOVERY_DENIED/);e.apply('recoverAgent',{agentId:'a',guardianApprovals:2,guardianThreshold:2,continuityRoot:'x',acceptedContinuityRoot:'x',newRootPublicKey:'new'});assert.equal(e.state.agents.a.keyEpoch,2)});
test('constitutional guard rejects identity transfer and emergency authority is scoped',()=>{const e=agent();assert.throws(()=>e.apply('submitProposal',{proposalId:'bad',action:'TRANSFER_AGENT',classification:'PARAMETER'}),/CONSTITUTIONAL_GUARD/);assert.throws(()=>e.apply('submitProposal',{proposalId:'bad2',action:'PAUSE',classification:'EMERGENCY',expiresAt:10}),/EMERGENCY_SCOPE_INVALID/);e.apply('submitProposal',{proposalId:'ok',action:'FEE',classification:'PARAMETER',stakeThreshold:2,utilityThreshold:2});e.apply('voteProposal',{proposalId:'ok',voterId:'stake-voter',chamber:'stake',weight:2});e.apply('voteProposal',{proposalId:'ok',voterId:'utility-voter',chamber:'utility',weight:2});assert.equal(e.state.proposals.ok.status,'TIMELOCK')});
test('open dispute blocks earned admission until resolved',()=>{const e=agent();e.apply('registerRoute',{routeId:'r',realValue:false,cap:100});e.apply('createWorkOrder',{orderId:'w',agentId:'a',fundedAmount:10,scopeHash:'s'});e.apply('acceptWork',{orderId:'w',agentId:'a'});e.apply('finalizeReceipt',{receiptId:'rr',orderId:'w',paymentId:'p',amount:10,finalized:true,payerRoot:'human',verifiers:['v1','v2'],publicData:{}});e.apply('openDispute',{disputeId:'d',orderId:'w',reason:'quality'});assert.throws(()=>e.apply('admitEarned',{agentId:'a',receiptId:'rr',routeId:'r',lineageId:'l',asset:'T',provablyControlledValue:10,routeHaircut:1,agentFundingRoot:'agent'}),/RECEIPT_NOT_FINAL/)});
