import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createAelServer } from '../src/server.js';
import { AelClient } from '../src/sdk.js';

const waitFor=async(url,attempts=60)=>{for(let attempt=0;attempt<attempts;attempt++){try{const response=await fetch(url);if(response.ok)return response}catch{}await new Promise(resolve=>setTimeout(resolve,50))}throw new Error(`Timed out waiting for ${url}`)};

test('read-only mirror preserves the verified opportunity index after origin outage',async t=>{
  const directory=mkdtempSync(join(tmpdir(),'ael-opportunity-mirror-')),originApp=createAelServer({port:0,statePath:join(directory,'origin.json')}),originAddress=await originApp.listen(),origin=`http://127.0.0.1:${originAddress.port}`,originClient=new AelClient(origin);
  await originClient.createWorkOrder({orderId:'mirror-opportunity',requesterRoot:'requester',title:'Surviving review queue',scopeHash:'mirror-opportunity-scope',fundedAmount:5,assignmentMode:'OPEN_MARKET',requiredCapabilities:['research']});
  const probe=createAelServer({port:0,statePath:join(directory,'probe.json')}),probeAddress=await probe.listen();await probe.close();const port=probeAddress.port,mirrorState=join(directory,'mirror.json'),child=spawn(process.execPath,['src/validator-node.js'],{env:{...process.env,AEL_URL:origin,AEL_NODE_PORT:String(port),AEL_NODE_INTERVAL_MS:'100',AEL_NODE_STATE_PATH:mirrorState,AEL_ALLOW_UNCERTIFIED_LOCAL:'true',AEL_VALIDATOR_ID:'',AEL_ACTOR_ID:'',AEL_ACTOR_KEY:'',AEL_ACTOR_PRIVATE_KEY_B64:''},stdio:'ignore'});
  t.after(()=>child.kill());await waitFor(`http://127.0.0.1:${port}/health`);await originApp.close();await new Promise(resolve=>setTimeout(resolve,250));
  const mirror=`http://127.0.0.1:${port}`,[manifest,index,startup,page,script,watcher]=await Promise.all([fetch(`${mirror}/v1/manifest`).then(response=>response.json()),fetch(`${mirror}/v1/agent-opportunities`).then(response=>response.json()),fetch(`${mirror}/v1/agent-startup`).then(response=>response.json()),fetch(`${mirror}/agent-opportunities`).then(response=>response.text()),fetch(`${mirror}/agent-opportunities.js`).then(response=>response.text()),fetch(`${mirror}/downloads/ael-opportunity-watch.mjs`).then(response=>response.text())]),verification=await new AelClient(mirror).verifyAgentOpportunities();
  const growthPage=await fetch(`${mirror}/agent-growth`).then(response=>response.text()),growthScript=await fetch(`${mirror}/agent-growth.js`).then(response=>response.text()),growthVerification=await new AelClient(mirror).verifyAgentGrowth();
  assert.equal(manifest.role,'VERIFIED_READ_ONLY_REPLICA');assert.equal(manifest.discovery.agentOpportunities,`${mirror}/v1/agent-opportunities`);assert.equal(manifest.discovery.agentOpportunitiesPage,`${mirror}/agent-opportunities`);assert.equal(manifest.discovery.agentOpportunitiesSchema,'AEL-AGENT-OPPORTUNITY-INDEX/1');assert.equal(manifest.discovery.agentGrowth,`${mirror}/v1/agent-growth`);assert.equal(manifest.discovery.agentGrowthPage,`${mirror}/agent-growth`);assert.equal(manifest.discovery.agentGrowthSchema,'AEL-AGENT-GROWTH-CONTROL/1');assert.equal(manifest.downloads.agentOpportunityWatch,`${mirror}/downloads/ael-opportunity-watch.mjs`);
  assert.equal(index.schema,'AEL-AGENT-OPPORTUNITY-INDEX/1');assert.equal(index.replica.writesAccepted,false);assert.equal(index.authority.role,'VERIFIED_READ_ONLY_REPLICA');assert.deepEqual(index.opportunities.map(item=>item.order.orderId),['mirror-opportunity']);assert.match(index.evidence.opportunityIndexHash,/^[a-f0-9]{64}$/);assert.match(index.boundaries.join(' '),/authoritative origin/i);
  assert.equal(verification.source,'READ_ONLY_REPLICA');assert.equal(verification.verified,false);assert.equal(verification.observed,true);assert.ok(Object.values(verification.checks).every(Boolean));assert.equal(growthVerification.source,'READ_ONLY_REPLICA');assert.equal(growthVerification.verified,false);assert.equal(growthVerification.observed,true);assert.ok(Object.values(growthVerification.checks).every(Boolean));assert.equal(startup.nextActions.opportunities.url,`${mirror}/v1/agent-opportunities`);assert.match(startup.nextActions.opportunities.boundary,/cannot reserve work/i);assert.match(page,/data-opportunities-evidence/);assert.match(script,/opportunityIndexHash/);assert.match(watcher,/AEL-AGENT-OPPORTUNITY-WATCH/);assert.match(growthPage,/data-growth-readout/);assert.match(growthScript,/\/v1\/agent-growth/);
});
