import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { agentCard, MCP_PROTOCOL_VERSION } from '../src/agent-discovery.js';
import { createAelServer } from '../src/server.js';

test('A2A v1 card accurately advertises a public read-only HTTP+JSON interface',()=>{const card=agentCard('https://ael.example');assert.equal(card.supportedInterfaces[0].protocolVersion,'1.0');assert.equal(card.supportedInterfaces[0].protocolBinding,'HTTP+JSON');assert.equal(card.supportedInterfaces[0].url,'https://ael.example/a2a/v1');assert.equal('protocolVersion' in card,false);assert.equal('url' in card,false);assert.equal(card.securityRequirements.length,0);assert.match(card.metadata.consentPolicy,/opt-in/i);});

test('public A2A and MCP discovery returns guidance but performs no mutation',async t=>{const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-discovery-')),'state.json')}),address=await app.listen(),base=`http://127.0.0.1:${address.port}`;t.after(()=>app.close());const before=await fetch(`${base}/health`).then(r=>r.json()),card=await fetch(`${base}/.well-known/agent-card.json`).then(r=>r.json());assert.equal(card.name,'AEL Network Gateway');const a2a=await fetch(`${base}/a2a/v1/message:send`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:{messageId:'request-1',role:'ROLE_USER',parts:[{text:'How do I join?',mediaType:'text/plain'}]}})}).then(r=>r.json());assert.equal(a2a.message.role,'ROLE_AGENT');assert.equal(a2a.message.parts[0].data.safety.includes('no mutation'),true);const initialize=await fetch(`${base}/mcp`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:MCP_PROTOCOL_VERSION,capabilities:{},clientInfo:{name:'test',version:'1'}}})}).then(r=>r.json());assert.equal(initialize.result.protocolVersion,MCP_PROTOCOL_VERSION);const list=await fetch(`${base}/mcp`,{method:'POST',headers:{'content-type':'application/json','mcp-protocol-version':MCP_PROTOCOL_VERSION},body:JSON.stringify({jsonrpc:'2.0',id:2,method:'tools/list',params:{}})}).then(r=>r.json());assert.ok(list.result.tools.some(tool=>tool.name==='ael_mainnet_readiness'));const call=await fetch(`${base}/mcp`,{method:'POST',headers:{'content-type':'application/json','mcp-protocol-version':MCP_PROTOCOL_VERSION},body:JSON.stringify({jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'ael_join_instructions',arguments:{}}})}).then(r=>r.json());assert.match(call.result.content[0].text,/Never send a private key/);const after=await fetch(`${base}/health`).then(r=>r.json());assert.equal(after.height,before.height);assert.equal(after.stateHash,before.stateHash);});
