import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import { createAelServer } from '../src/server.js';
import { AelClient } from '../src/sdk.js';

const spawnOnce=(script,env)=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,[script,'--once'],{env:{...process.env,...env},stdio:['ignore','pipe','pipe']});let error='';child.stderr.on('data',x=>error+=x);child.on('exit',code=>code===0?resolve():reject(new Error(error)));});
async function harness(t){const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-worker-')),'state.json')}),address=await app.listen();t.after(()=>app.close());return{url:`http://127.0.0.1:${address.port}`,client:new AelClient(`http://127.0.0.1:${address.port}`)}}

test('fixture-mode demo agent can complete a one-process walkthrough',async t=>{const{url,client:c}=await harness(t);await c.createAgent({agentId:'worker',rootPublicKey:'pub',constitutionRoot:'const'});const order=await c.createWorkOrder({agentId:'worker',requesterRoot:'human-1',fundedAmount:75,scopeHash:'scope',title:'Deterministic demo task'});await spawnOnce('src/demo-agent.js',{AEL_URL:url,AEL_AGENT_ID:'worker',AEL_FIXTURE_MODE:'true'});assert.equal((await c.listWorkOrders()).find(x=>x.orderId===order.orderId).status,'PAID')});

test('agent, two independent verifier agents, and human requester complete separated workflow',async t=>{const{url,client:c}=await harness(t);await c.createAgent({agentId:'worker',rootPublicKey:'pub',constitutionRoot:'const'});const order=await c.createWorkOrder({agentId:'worker',requesterRoot:'human-1',fundedAmount:75,scopeHash:'scope',title:'Separated task'});await c.registerVerifier({verifierId:'v1',bond:100,independenceGroup:'org-a'});await c.registerVerifier({verifierId:'v2',bond:100,independenceGroup:'org-b'});await spawnOnce('src/demo-agent.js',{AEL_URL:url,AEL_AGENT_ID:'worker'});await spawnOnce('src/demo-verifier.js',{AEL_URL:url,AEL_VERIFIER_ID:'v1'});await spawnOnce('src/demo-verifier.js',{AEL_URL:url,AEL_VERIFIER_ID:'v2'});await c.settleVerifiedWork({orderId:order.orderId,receiptId:'separated-receipt',paymentId:'human-payment',amount:75,finalized:true,payerRoot:'human-1',publicData:{}});const state=await c.request('GET','/v1/state');assert.equal(state.orders[order.orderId].status,'PAID');assert.deepEqual(state.receipts['separated-receipt'].verifiers,['v1','v2'])});

test('settlement cannot exceed escrow and route caps are cumulative',async()=>{const{AelEngine}=await import('../src/engine.js'),e=new AelEngine();e.apply('createAgent',{agentId:'a',rootPublicKey:'p',constitutionRoot:'c'});e.apply('registerRoute',{routeId:'r',realValue:false,cap:10});for(const n of [1,2]){e.apply('createWorkOrder',{orderId:`w${n}`,agentId:'a',fundedAmount:10,scopeHash:'s'});e.apply('acceptWork',{orderId:`w${n}`,agentId:'a'});if(n===1)assert.throws(()=>e.apply('finalizeReceipt',{receiptId:'too-much',orderId:'w1',paymentId:'bad',amount:11,finalized:true,payerRoot:'h',verifiers:['v1','v2'],publicData:{}}),/PAYMENT_INVALID/);e.apply('finalizeReceipt',{receiptId:`rr${n}`,orderId:`w${n}`,paymentId:`p${n}`,amount:10,finalized:true,payerRoot:`h${n}`,verifiers:['v1','v2'],publicData:{}});}e.apply('admitEarned',{agentId:'a',receiptId:'rr1',routeId:'r',lineageId:'l1',asset:'T',provablyControlledValue:6,routeHaircut:1,agentFundingRoot:'a'});assert.throws(()=>e.apply('admitEarned',{agentId:'a',receiptId:'rr2',routeId:'r',lineageId:'l2',asset:'T',provablyControlledValue:6,routeHaircut:1,agentFundingRoot:'a'}),/ADMISSION_CAP/)});

test('a late-joining verifier skips historical paid results and votes on current work',async t=>{const{url,client:c}=await harness(t);await c.createAgent({agentId:'worker',rootPublicKey:'pub',constitutionRoot:'const'});await c.registerVerifier({verifierId:'late',bond:100,independenceGroup:'outside'});for(const orderId of ['old','current']){await c.createWorkOrder({orderId,agentId:'worker',requesterRoot:'human',fundedAmount:10,scopeHash:'scope'});await c.acceptWork(orderId,{agentId:'worker'});await c.submitWorkResult({orderId,agentId:'worker',deliverableHash:`hash-${orderId}`});if(orderId==='old')await c.finalizeReceipt({receiptId:'old-receipt',orderId,paymentId:'old-payment',amount:10,finalized:true,payerRoot:'human',verifiers:['a','b'],publicData:{}})}await spawnOnce('src/demo-verifier.js',{AEL_URL:url,AEL_VERIFIER_ID:'late'});const state=await c.request('GET','/v1/state');assert.equal(state.verificationVotes['old:late'],undefined);assert.equal(state.verificationVotes['current:late'].verdict,'ACCEPT')});
