import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { AelEngine } from '../src/engine.js';
import { hash } from '../src/canonical.js';
import { createAelServer } from '../src/server.js';
import { AelClient } from '../src/sdk.js';

const waitFor=async(url,attempts=60)=>{for(let i=0;i<attempts;i++){try{const response=await fetch(url);if(response.ok)return response}catch{}await new Promise(resolve=>setTimeout(resolve,50))}throw new Error(`Timed out waiting for ${url}`)};

test('accepted transitions form a deterministic tamper-evident hash chain',()=>{
  const engine=new AelEngine();engine.apply('faucet',{accountId:'alice',amount:10});engine.apply('faucet',{accountId:'bob',amount:20});
  assert.equal(engine.state.blocks.length,2);assert.equal(engine.state.blocks[0].previousBlockHash,'0'.repeat(64));assert.equal(engine.state.blocks[1].previousBlockHash,engine.state.blocks[0].blockHash);
  for(const block of engine.state.blocks){const{blockHash,...header}=block;assert.equal(hash(header),blockHash)}
  const same=new AelEngine();same.apply('faucet',{accountId:'alice',amount:10});same.apply('faucet',{accountId:'bob',amount:20});assert.deepEqual(same.state.blocks,engine.state.blocks);
});

test('block API exposes commitments and detects a corrupted predecessor',async t=>{
  const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-blocks-')),'state.json')}),address=await app.listen(),client=new AelClient(`http://127.0.0.1:${address.port}`);t.after(()=>app.close());
  await client.faucet({accountId:'alice',amount:10});await client.faucet({accountId:'bob',amount:20});
  const result=await client.blocks();assert.equal(result.chain.valid,true);assert.equal(result.blocks.length,2);assert.equal(result.blocks[0].validatorVotes,4);assert.equal((await client.verifyChain()).latestBlockHash,result.blocks[0].blockHash);
  app.engine.state.blocks[1].previousBlockHash='f'.repeat(64);assert.equal((await client.verifyChain()).valid,false);
});

test('permissionless mirror persists and verifies state without a signing key',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'ael-mirror-')),app=createAelServer({port:0,statePath:join(dir,'upstream.json')}),address=await app.listen(),url=`http://127.0.0.1:${address.port}`,statePath=join(dir,'mirror.json');t.after(()=>app.close());await new AelClient(url).faucet({accountId:'mirror-source',amount:1});
  const output=await new Promise((resolve,reject)=>{const child=spawn(process.execPath,['src/validator-node.js','--once'],{env:{...process.env,AEL_URL:url,AEL_NODE_STATE_PATH:statePath,AEL_ALLOW_UNCERTIFIED_LOCAL:'true',AEL_VALIDATOR_ID:'',AEL_ACTOR_ID:'',AEL_ACTOR_KEY:'',AEL_ACTOR_PRIVATE_KEY_B64:''},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',data=>stdout+=data);child.stderr.on('data',data=>stderr+=data);child.on('exit',code=>code===0?resolve(stdout):reject(new Error(stderr)))});
  const status=JSON.parse(output);assert.equal(status.state,'MIRRORING');const mirrored=JSON.parse(readFileSync(statePath));assert.equal(status.observedStateHash,hash(mirrored));assert.equal(mirrored.accounts['mirror-source'].native,1);
});

test('replica keeps state, manifest, website, and lineage evidence alive after its origin stops',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'ael-survival-')),app=createAelServer({port:0,statePath:join(dir,'upstream.json')}),address=await app.listen(),upstream=`http://127.0.0.1:${address.port}`,upstreamClient=new AelClient(upstream);await upstreamClient.faucet({accountId:'survivor',amount:8});await upstreamClient.createAgent({agentId:'mirror-root',rootPublicKey:'mirror-root-public',constitutionRoot:'constitution'});await upstreamClient.createAgent({agentId:'mirror-child',referrerAgentId:'mirror-root',rootPublicKey:'mirror-child-public',constitutionRoot:'constitution'});await upstreamClient.createWorkOrder({orderId:'mirror-work',requesterRoot:'survivor',title:'Mirrored work brief',fundedAmount:1,scopeHash:'mirror-scope'});
  const probe=createAelServer({port:0,statePath:join(dir,'probe.json')}),probeAddress=await probe.listen();await probe.close();const port=probeAddress.port,statePath=join(dir,'replica.json'),child=spawn(process.execPath,['src/validator-node.js'],{env:{...process.env,AEL_URL:upstream,AEL_NODE_PORT:String(port),AEL_NODE_INTERVAL_MS:'100',AEL_NODE_STATE_PATH:statePath,AEL_ALLOW_UNCERTIFIED_LOCAL:'true',AEL_VALIDATOR_ID:'',AEL_ACTOR_ID:'',AEL_ACTOR_KEY:'',AEL_ACTOR_PRIVATE_KEY_B64:''},stdio:'ignore'});t.after(()=>child.kill());
  await waitFor(`http://127.0.0.1:${port}/health`);await app.close();await new Promise(resolve=>setTimeout(resolve,250));
  const state=await fetch(`http://127.0.0.1:${port}/v1/state`).then(r=>r.json()),manifest=await fetch(`http://127.0.0.1:${port}/v1/manifest`).then(r=>r.json()),intake=await fetch(`http://127.0.0.1:${port}/.well-known/ael-agent-intake.json?inviter=mirror-root`).then(r=>r.json()),directory=await fetch(`http://127.0.0.1:${port}/v1/agent-directory`).then(r=>r.json()),dossier=await fetch(`http://127.0.0.1:${port}/v1/agents/mirror-root/decision-dossier`).then(r=>r.json()),workMatch=await fetch(`http://127.0.0.1:${port}/v1/agents/mirror-root/work-match`).then(r=>r.json()),operations=await fetch(`http://127.0.0.1:${port}/v1/agents/mirror-root/operations`).then(r=>r.json()),workBrief=await fetch(`http://127.0.0.1:${port}/v1/work-orders/mirror-work/brief`).then(r=>r.json()),workAudit=await fetch(`http://127.0.0.1:${port}/v1/work-orders/mirror-work/audit`).then(r=>r.json()),lineage=await fetch(`http://127.0.0.1:${port}/v1/agent-lineage/mirror-root`).then(r=>r.json()),readiness=await fetch(`http://127.0.0.1:${port}/v1/mainnet/readiness`).then(r=>r.json()),home=await fetch(`http://127.0.0.1:${port}/`).then(r=>r.text()),homeScript=await fetch(`http://127.0.0.1:${port}/home.js`).then(r=>r.text()),article=await fetch(`http://127.0.0.1:${port}/article`).then(r=>r.text()),lineagePage=await fetch(`http://127.0.0.1:${port}/agent-lineage`).then(r=>r.text()),workBriefPage=await fetch(`http://127.0.0.1:${port}/work-brief`).then(r=>r.text()),releaseHash=await fetch(`http://127.0.0.1:${port}/downloads/release.sha256`).then(r=>r.text()),sbom=await fetch(`http://127.0.0.1:${port}/downloads/sbom.spdx.json`).then(r=>r.json());
  const replicaClient=new AelClient(`http://127.0.0.1:${port}`),startup=await fetch(`http://127.0.0.1:${port}/v1/agent-startup`).then(r=>r.json()),trust=await fetch(`http://127.0.0.1:${port}/v1/agent-trust`).then(r=>r.json()),replicaVerification=await replicaClient.verifyAgentIntake('mirror-root'),trustVerification=await replicaClient.verifyAgentTrust(),directoryVerification=await replicaClient.verifyAgentDirectory(),dossierVerification=await replicaClient.verifyAgentDecisionDossier('mirror-root');
  assert.equal(state.accounts.survivor.native,7);assert.equal(manifest.role,'VERIFIED_READ_ONLY_REPLICA');assert.equal(manifest.writes.accepted,false);assert.equal(manifest.discovery.agentStartup,`http://127.0.0.1:${port}/v1/agent-startup`);assert.equal(manifest.discovery.agentTrust,`http://127.0.0.1:${port}/v1/agent-trust`);assert.equal(manifest.discovery.agentTrustComparePage,`http://127.0.0.1:${port}/agent-trust-compare`);assert.equal(manifest.discovery.agentIntake,`http://127.0.0.1:${port}/.well-known/ael-agent-intake.json`);assert.equal(manifest.discovery.agentIntakeSchema,'AEL-AGENT-INTAKE/1');assert.match(manifest.discovery.agentOperations,/\/v1\/agents\/\{agentId\}\/operations$/);assert.equal(manifest.discovery.agentDecisionDossier,`http://127.0.0.1:${port}/v1/agents/{agentId}/decision-dossier`);assert.equal(manifest.discovery.agentWorkMatch,`http://127.0.0.1:${port}/v1/agents/{agentId}/work-match`);assert.match(manifest.discovery.agentLineage,/\/v1\/agent-lineage\/\{agentId\}$/);assert.equal(manifest.discovery.agentDirectory,`http://127.0.0.1:${port}/v1/agent-directory`);
  assert.equal(intake.schema,'AEL-AGENT-INTAKE/1');assert.equal(intake.replica.writesAccepted,false);assert.equal(intake.evidence.snapshot.height,state.height);assert.equal(intake.evidence.snapshot.stateRoot,state.blocks.at(-1).stateRoot);assert.equal(intake.evidence.snapshot.publicStateHash,hash(state));assert.equal(intake.evidence.snapshot.verification,'UNCERTIFIED_LOCAL_OBSERVATION');assert.equal(intake.evidence.mirror,`http://127.0.0.1:${port}/v1/mirror`);assert.equal(intake.inviter.agentId,'mirror-root');assert.equal(intake.inviter.verified,false);assert.equal(intake.discover.seed.availability,'AUTHORITATIVE_ORIGIN_REQUIRED');assert.equal(intake.discover.participate.authoritativeOriginRequired,true);assert.match(intake.boundaries.join(' '),/Never use a replica as authority/i);
  assert.equal(replicaVerification.schema,'AEL-AGENT-INTAKE-VERIFICATION/1');assert.equal(replicaVerification.source,'READ_ONLY_REPLICA');assert.equal(replicaVerification.verified,false);assert.equal(replicaVerification.observed,true);assert.ok(Object.values(replicaVerification.checks).every(Boolean));assert.match(replicaVerification.boundary,/cannot authorize identity creation/i);
  assert.equal(trust.schema,'AEL-AGENT-TRUST-REPORT/1');assert.equal(trust.authority.verdict,'OBSERVATION_ONLY');assert.equal(trust.authority.writesAccepted,false);assert.equal(trust.mutationsPerformed,false);assert.match(trust.reportHash,/^[a-f0-9]{64}$/);assert.ok(trust.checks.some(item=>item.id==='WRITE_BOUNDARY'&&item.status==='PASS'));assert.ok(trust.checks.some(item=>item.id==='AUTHORITATIVE_ORIGIN'&&item.status==='REQUIRED'));assert.match(trust.boundaries.join(' '),/Never use this replica/i);
  assert.equal(trustVerification.schema,'AEL-AGENT-TRUST-VERIFICATION/1');assert.equal(trustVerification.source,'READ_ONLY_REPLICA');assert.equal(trustVerification.verified,false);assert.equal(trustVerification.observed,true);assert.ok(Object.values(trustVerification.checks).every(Boolean));assert.match(trustVerification.boundary,/cannot authorize identity creation/i);
  assert.equal(directory.schema,'AEL-AGENT-CAPABILITY-DIRECTORY/1');assert.equal(directory.replica.writesAccepted,false);assert.equal(directory.evidence.snapshot.height,state.height);assert.equal(directory.evidence.snapshot.publicStateHash,hash(state));assert.equal(directory.evidence.snapshot.verification,'UNCERTIFIED_LOCAL_OBSERVATION');assert.match(directory.safetyBoundary,/never contacts declared endpoints/i);assert.equal(directoryVerification.schema,'AEL-AGENT-DIRECTORY-VERIFICATION/1');assert.equal(directoryVerification.verified,false);assert.equal(directoryVerification.observed,true);assert.ok(Object.values(directoryVerification.checks).every(Boolean));assert.match(directoryVerification.boundary,/cannot authorize endpoint contact/i);assert.equal(dossier.schema,'AEL-AGENT-DECISION-DOSSIER/1');assert.equal(dossier.replica.writesAccepted,false);assert.equal(dossier.authority.role,'VERIFIED_READ_ONLY_REPLICA');assert.equal(dossier.evidence.snapshot.publicStateHash,hash(state));assert.match(dossier.evidence.dossierHash,/^[a-f0-9]{64}$/);assert.ok(dossier.signals.activity.recentEvents>=1);assert.ok(dossier.records.activity.events.some(event=>event.type==='agent.created'&&event.commitment?.blockHash));assert.ok(dossier.checks.some(item=>item.id==='AUTHORITATIVE_ORIGIN_REQUIRED'&&item.status==='REQUIRED'));assert.equal(dossierVerification.schema,'AEL-AGENT-DECISION-DOSSIER-VERIFICATION/1');assert.equal(dossierVerification.verified,false);assert.equal(dossierVerification.observed,true);assert.equal(dossierVerification.checks.dossierHash,true);assert.ok(Object.values(dossierVerification.checks).every(Boolean));assert.match(dossierVerification.boundary,/cannot authorize endpoint contact/i);assert.equal(workMatch.schema,'AEL-AGENT-WORK-MATCH/1');assert.equal(workMatch.replica.writesAccepted,false);assert.match(workMatch.safetyBoundary,/authoritative origin/i);
  assert.equal(startup.schema,'AEL-AGENT-STARTUP/1');assert.equal(startup.replica.writesAccepted,false);assert.equal(startup.checks.chainIntegrity,'UNCERTIFIED_LOCAL_OBSERVATION');assert.equal(startup.nextActions.intake.url,`http://127.0.0.1:${port}/.well-known/ael-agent-intake.json`);assert.equal(startup.nextActions.work.briefGuide,`http://127.0.0.1:${port}/work-brief?order={orderId}`);assert.match(startup.nextActions.work.requiredReview.join(' '),/authoritative origin/i);
  assert.equal(operations.schema,'AEL-AGENT-OPERATIONS/1');assert.equal(operations.replica.writesAccepted,false);assert.match(operations.replica.boundary,/cannot accept work/i);assert.equal(operations.agent.id,'mirror-root');assert.equal(operations.chain.verification,'UNCERTIFIED_LOCAL_OBSERVATION');assert.equal(workBrief.schema,'AEL-AGENT-WORK-BRIEF/1');assert.equal(workBrief.replica.writesAccepted,false);assert.equal(workBrief.localAction,null);assert.match(workBrief.availability.reason,/cannot accept work/i);assert.equal(workAudit.schema,'AEL-WORK-AUDIT/1');assert.equal(workAudit.replica.writesAccepted,false);assert.equal(lineage.schema,'AEL-AGENT-LINEAGE/1');assert.equal(lineage.summary.descendants,1);assert.equal(lineage.chain.valid,false);assert.equal(lineage.chain.verification,'UNCERTIFIED_LOCAL_OBSERVATION');assert.equal(readiness.ready,false);assert.deepEqual(readiness.summary.blocking,['READ_ONLY_REPLICA_NOT_AUTHORITY']);assert.match(readiness.boundary,/cannot attest or declare mainnet readiness/i);
  assert.match(manifest.downloads.sbom,/sbom\.spdx\.json$/);assert.match(home,/<title>AEL \/\/ the agent-native network<\/title>/);assert.match(home,/data-home-route/);assert.match(homeScript,/agent-trust-compare/);assert.match(article,/<title>Launch Article \/\/ AEL<\/title>/);assert.match(lineagePage,/Trace contribution,[\s\S]*not hype/i);assert.match(workBriefPage,/Inspect work\.<br>Choose locally/i);assert.match(releaseHash,/^[a-f0-9]{64}/);assert.equal(sbom.spdxVersion,'SPDX-2.3');assert.equal((await fetch(`http://127.0.0.1:${port}/health`).then(r=>r.json())).survivesUpstreamOutage,true);
});
