import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, appendFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildCertificate, canonicalValidatorSet, ConsensusWal, quorumPower, selectProposer, voteDomain } from '../src/consensus-primitives.js';

const validators=[1,2,3,4].map(index=>({id:`v${index}`,publicKeyB64:`key-${index}`,votingPower:index===1?2:1,url:`https://v${index}.example`,faultDomain:`fd-${index}`}));

test('validator set hash and weighted proposer rotation are deterministic',()=>{const set=canonicalValidatorSet([...validators].reverse(),3),same=canonicalValidatorSet(validators,3);assert.equal(set.validatorSetHash,same.validatorSetHash);assert.equal(set.totalVotingPower,5);const input={chainId:'ael-devnet-1',epoch:3,height:10,view:0,previousCertificateHash:'a'.repeat(64),validatorSet:set};assert.deepEqual(selectProposer(input),selectProposer(input));assert.notEqual(selectProposer({...input,view:1}).seed,selectProposer(input).seed)});

test('certificate requires unique quorum voting power and has a stable hash',()=>{const set=canonicalValidatorSet(validators,1),base={chainId:'ael-devnet-1',epoch:1,height:2,view:0,phase:'PRECOMMIT',proposalId:'proposal',blockHash:'b'.repeat(64),stateHash:'c'.repeat(64),validatorSetHash:set.validatorSetHash},vote=validatorId=>({...voteDomain({...base,validatorId}),signature:`sig-${validatorId}`});assert.equal(quorumPower(set),4);assert.throws(()=>buildCertificate({...base,validatorSet:set,votes:[vote('v1'),vote('v2')]}),/CERTIFICATE_QUORUM_INSUFFICIENT/);const certificate=buildCertificate({...base,validatorSet:set,votes:[vote('v3'),vote('v1'),vote('v2'),vote('v1')]});assert.equal(certificate.votingPower,4);assert.equal(certificate.votes.length,3);assert.equal(certificate.certificateHash,buildCertificate({...base,validatorSet:set,votes:[vote('v1'),vote('v2'),vote('v3')]}).certificateHash)});

test('certificates reject cross-domain votes and encode quorum view changes',()=>{const set=canonicalValidatorSet(validators,1),base={chainId:'ael-devnet-1',epoch:1,height:3,view:2,phase:'VIEW_CHANGE',proposalId:'locked-proposal',blockHash:'d'.repeat(64),stateHash:'e'.repeat(64),validatorSetHash:set.validatorSetHash},vote=validatorId=>({...voteDomain({...base,validatorId}),signature:`sig-${validatorId}`});assert.throws(()=>buildCertificate({...base,kind:'VIEW_CHANGE',validatorSet:set,votes:[vote('v1'),vote('v2'),{...vote('v3'),view:1}]}),/CERTIFICATE_VOTE_INVALID/);const certificate=buildCertificate({...base,kind:'VIEW_CHANGE',validatorSet:set,votes:[vote('v1'),vote('v2'),vote('v3')]});assert.equal(certificate.schema,'AEL-VIEW-CERTIFICATE/1');assert.equal(certificate.kind,'VIEW_CHANGE');assert.equal(certificate.view,2);assert.equal(certificate.votingPower,4)});

test('WAL survives restart, prevents conflicting signatures, and detects corruption',()=>{const dir=mkdtempSync(join(tmpdir(),'ael-wal-')),path=join(dir,'consensus.wal'),vote={epoch:1,height:2,view:0,phase:'PREPARE',proposalId:'one'};const wal=new ConsensusWal(path);wal.append('PROPOSAL_RECEIVED',{proposalId:'one'});wal.append('PREPARE_SIGNED',vote);const restored=new ConsensusWal(path);assert.equal(restored.records.length,2);assert.throws(()=>restored.append('PREPARE_SIGNED',{...vote,proposalId:'two'}),/CONSENSUS_DOUBLE_SIGN_PREVENTED/);appendFileSync(path,'{"broken":true}\n');assert.throws(()=>new ConsensusWal(path),/CONSENSUS_WAL_CORRUPT/)});
