import test from 'node:test';import assert from 'node:assert/strict';import{AelEngine}from'../src/engine.js';import{earnedLiquidityBasic}from'../src/simulator.js';
test('buyers fund real reserve and sellers cannot redeem beyond it',()=>{const e=new AelEngine();e.apply('createAgent',{agentId:'a',rootPublicKey:'p',constitutionRoot:'c',virtualLiquidity:1000,virtualTokens:1000});e.apply('faucet',{accountId:'human',amount:500});e.apply('buy',{accountId:'human',agentId:'a',baseAmount:100});const tokens=e.state.accounts.human.tokens.a;assert.equal(e.state.agents.a.reserves.native,100);e.apply('sell',{accountId:'human',agentId:'a',tokens});assert.ok(Math.abs(e.state.accounts.human.native-500)<1e-9);e.assertInvariants()});
test('external release decrements recognized reserve before marking lineage released',()=>{const{engine:e}=earnedLiquidityBasic();e.apply('releaseExternal',{agentId:'agent-1',lineageId:'solana:tx:1',amount:1615});assert.equal(e.state.agents['agent-1'].reserves.external,0);assert.equal(e.state.lineages['solana:tx:1'].active,false);assert.equal(e.state.events.at(-1).reserve_decremented,true)});
test('validator stake is separate from receipt-backed service rewards',()=>{const e=new AelEngine();e.apply('faucet',{accountId:'delegator',amount:1000});e.apply('registerValidator',{validatorId:'v',operatorId:'operator',selfBond:100,consensusPublicKey:'cpub'});e.apply('delegate',{validatorId:'v',delegatorId:'delegator',amount:200});e.apply('fundRewardPool',{service:'relay',amount:50});e.apply('claimServiceReward',{providerId:'operator',service:'relay',receiptId:'proof-1',amount:10,qualityFactor:1,independenceFactor:.8});assert.equal(e.state.validators.v.delegated,200);assert.equal(e.state.accounts.operator.rewards,8);assert.throws(()=>e.apply('claimServiceReward',{providerId:'operator',service:'relay',receiptId:'proof-1',amount:10,qualityFactor:1,independenceFactor:1}),/SERVICE_CLAIM_INVALID/)});

test('public work funding is conserved through escrow, agent payment, and requester refund',()=>{const e=new AelEngine();e.apply('createAgent',{agentId:'worker',rootPublicKey:'p',constitutionRoot:'c'});e.apply('faucet',{accountId:'buyer',amount:100});e.apply('createWorkOrder',{orderId:'paid-work',agentId:'worker',requesterRoot:'buyer',fundedAmount:80,scopeHash:'s'});assert.equal(e.state.accounts.buyer.native,20);assert.equal(e.state.orders['paid-work'].escrowedAmount,80);e.apply('acceptWork',{orderId:'paid-work',agentId:'worker'});e.apply('finalizeReceipt',{receiptId:'receipt',orderId:'paid-work',paymentId:'payment',amount:60,finalized:true,payerRoot:'buyer',verifiers:['v1','v2'],publicData:{}});assert.equal(e.state.accounts.buyer.native,40);assert.equal(e.state.accounts.worker.native,60);assert.equal(e.state.orders['paid-work'].escrowedAmount,0);assert.throws(()=>e.apply('createWorkOrder',{orderId:'too-large',agentId:'worker',requesterRoot:'buyer',fundedAmount:50,scopeHash:'s'}),/WORK_ESCROW_INSUFFICIENT/)});

test('faucet has per-request and per-account lifetime limits',()=>{const e=new AelEngine();assert.throws(()=>e.apply('faucet',{accountId:'a',amount:1001}),/FAUCET_INVALID/);for(let i=0;i<10;i++)e.apply('faucet',{accountId:'a',amount:1000});assert.equal(e.state.accounts.a.native,10_000);assert.throws(()=>e.apply('faucet',{accountId:'a',amount:1}),/FAUCET_INVALID/)});
test('double-sign evidence deterministically tombstones and slashes',()=>{const e=new AelEngine();e.apply('registerValidator',{validatorId:'v',operatorId:'o',selfBond:100,consensusPublicKey:'p'});e.apply('submitValidatorEvidence',{validatorId:'v',kind:'DOUBLE_SIGN',evidenceHash:'two-conflicting-votes'});assert.equal(e.state.validators.v.status,'TOMBSTONED');assert.equal(e.state.validators.v.slashed,20)});
test('agent retirement is terminal and emergency authority expires',()=>{const e=new AelEngine();e.apply('createAgent',{agentId:'a',rootPublicKey:'p',constitutionRoot:'c'});e.apply('submitProposal',{proposalId:'em',action:'PAUSE_ROUTE',classification:'EMERGENCY',scope:'route:x',expiresAt:5,stakeThreshold:1,utilityThreshold:1});e.apply('setAgentStatus',{agentId:'a',status:'RETIRED'});assert.throws(()=>e.apply('setAgentStatus',{agentId:'a',status:'ACTIVE'}),/LIFECYCLE_INVALID/);e.apply('advance',{blocks:5});assert.equal(e.state.proposals.em.status,'EXPIRED')});
