import test from 'node:test';
import assert from 'node:assert/strict';
import { AelEngine } from '../src/engine.js';
import { evaluateMainnetReadiness } from '../src/mainnet-readiness.js';
import { hash } from '../src/canonical.js';

const thresholds={minimumHeight:1,validators:1,validatorFaultDomains:1,replicas:1,replicaProviders:1,replicaCountries:1,replicaFaultDomains:1,agents:1,hybridPaidWork:1,nativePaidWork:1,verifiers:1,verifierGroups:1,runtimeFaultDomains:1,memoryCheckpoints:1,memoryAgents:1,finalizedHandovers:1};
const consensus={mode:'NETWORKED_BFT_DEVNET',height:1,epoch:1,validatorSetHash:hash('validator-set'),quorum:1,finality:{votes:1,votingPower:1},validators:[{id:'v',status:'ACTIVE',faultDomain:'validator-org'}]};

function qualified(){const e=new AelEngine();e.apply('createAgent',{agentId:'agent',rootPublicKey:'pub',constitutionRoot:'c'});const s=e.state,digest='a'.repeat(64),evidence='b'.repeat(64),wallet={version:'0.7.0',releaseHash:digest,evidenceHash:evidence};s.memoryCheckpoints={};s.memoryHandovers={};s.protocolReleases={};s.walletDistributionAttestations={};s.beacons.agent={agentId:'agent',indexable:true,expiresAtHeight:s.height+100,capabilities:['ael-replica'],protocols:['AEL-REPLICA/1'],node:{role:'AGENT_REPLICA',provider:'provider-a',countryCode:'RO',faultDomain:'replica-a'}};s.orders.work={orderId:'work',status:'PAID',fundingMode:'NATIVE_ESCROW'};s.workResults.work={verification:{mode:'HYBRID'}};s.verifiers.v={verifierId:'v',status:'ACTIVE',independenceGroup:'verify-a'};s.runtimeProviders.r={status:'ACTIVE',faultDomain:'runtime-a'};s.memoryCheckpoints.cp={status:'AVAILABLE',agentId:'agent',storageReplicas:[{providerId:'a'},{providerId:'b'}]};s.memoryHandovers.h={status:'FINALIZED',checkpointId:'cp',agentId:'agent'};s.protocolReleases.r={status:'DEPLOYED',origins:['https://one.example','https://two.example','https://three.example']};s.auditEngagements.core={status:'CLOSED',component:'CORE_PROTOCOL'};s.auditEngagements.wallet={status:'CLOSED',component:'WALLET'};s.walletDistributionAttestations={'PWA:a':{channel:'PWA',status:'LIVE',independenceGroup:'audit-a'},'CHROME:a':{...wallet,channel:'CHROME',status:'REVIEWED',independenceGroup:'audit-a',listingUrl:'https://chromewebstore.google.com/detail/ael-wallet/example'},'FIREFOX:b':{...wallet,channel:'FIREFOX',status:'REVIEWED',independenceGroup:'audit-b',listingUrl:'https://addons.mozilla.org/en-US/firefox/addon/ael-wallet/'}};return e;}

test('readiness report names every blocker instead of relabeling devnet',()=>{const report=evaluateMainnetReadiness({state:new AelEngine().state,consensus:{mode:'LOCAL',height:0,quorum:3,finality:null,validators:[]}});assert.equal(report.ready,false);assert.ok(report.summary.blocking.includes('networked-bft'));assert.ok(report.summary.blocking.includes('wallet-audit'));assert.equal(report.candidate.chainId,'ael-mainnet-1');assert.match(report.readinessHash,/^[a-f0-9]{64}$/);});

test('all objective gates produce a deterministic genesis and one-way activation',()=>{const e=qualified(),first=evaluateMainnetReadiness({state:e.state,consensus,thresholds}),second=evaluateMainnetReadiness({state:e.state,consensus,thresholds});assert.equal(first.ready,true);assert.equal(first.readinessHash,second.readinessHash);assert.equal(first.genesisHash,second.genesisHash);e.apply('sealMainnetGenesis',{agentId:'agent',readinessVerified:true,readinessHash:first.readinessHash,genesisHash:first.genesisHash,sourceStateRoot:first.candidate.sourceStateRoot,readinessSnapshot:first});assert.equal(e.state.mainnetTransition.status,'ACTIVE');assert.equal(e.state.mainnetTransition.chainId,'ael-mainnet-1');assert.throws(()=>e.apply('faucet',{accountId:'x',amount:1}),/FAUCET_INVALID/);assert.throws(()=>e.apply('sealMainnetGenesis',{agentId:'agent',readinessVerified:true,readinessHash:first.readinessHash,genesisHash:first.genesisHash,sourceStateRoot:first.candidate.sourceStateRoot,readinessSnapshot:first}),/MAINNET_READINESS_NOT_SATISFIED/);});
