import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import { createAelServer } from '../src/server.js';
import { AelClient, createLocalAuthority } from '../src/sdk.js';
import { canonicalValidatorSet, selectProposer, verifyFinalityCertificate } from '../src/consensus-primitives.js';

const token='network-consensus-test-token';
const startValidator=({id,statePath,keys,fault=false})=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,['src/consensus-validator.js'],{env:{...process.env,AEL_CONSENSUS_VALIDATOR_ID:id,AEL_CONSENSUS_CLUSTER_TOKEN:token,AEL_CONSENSUS_PRIVATE_KEY_B64:Buffer.from(keys.privateKey).toString('base64'),AEL_CONSENSUS_STATE:statePath,AEL_CONSENSUS_PORT:'0',AEL_CONSENSUS_HOST:'127.0.0.1',AEL_CONSENSUS_FAULT_ROOT:String(fault)},stdio:['ignore','pipe','pipe']});let buffer='',errors='';child.stderr.on('data',data=>errors+=data);child.stdout.on('data',data=>{buffer+=data;const line=buffer.split('\n').find(item=>item.trim());if(!line)return;try{const ready=JSON.parse(line);if(ready.status==='ready')resolve({id,child,url:`http://127.0.0.1:${ready.port}`,publicKeyB64:Buffer.from(ready.publicKey).toString('base64'),statePath,keys})}catch{}});child.on('exit',code=>{if(code&&buffer.length===0)reject(new Error(errors))})});
const stop=validator=>new Promise(resolve=>{if(!validator||validator.child.exitCode!==null)return resolve();validator.child.once('exit',resolve);validator.child.kill('SIGTERM')});

test('networked validators gate commits by 2/3 quorum, reject divergence, and resynchronize restart',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'ael-network-consensus-')),validators=[];for(let index=1;index<=4;index++){const keys=createLocalAuthority();validators.push(await startValidator({id:`network-validator-${index}`,statePath:join(dir,`validator-${index}.json`),keys,fault:index===4}))}t.after(async()=>Promise.all(validators.map(stop)));
  const config=validators.map(({id,url,publicKeyB64})=>({id,url,publicKeyB64})),app=createAelServer({port:0,statePath:join(dir,'coordinator.json'),networkValidators:config,consensusToken:token,consensusTimeoutMs:1000}),address=await app.listen(),client=new AelClient(`http://127.0.0.1:${address.port}`);t.after(()=>app.close());
  const restored=await client.network();assert.equal(restored.finality.votes,4);assert.equal(restored.finality.restored,true);assert.equal(restored.finality.attestation,'SIGNED_STATUS');
  const first=await client.faucet({accountId:'alice',amount:10});assert.equal(first.validatorVotes,3);const firstNetwork=await client.network(),certificate=await client.request('GET',`/v1/consensus/certificates/${firstNetwork.finality.certificateHash}`),state=await client.request('GET','/v1/state');assert.equal(firstNetwork.mode,'NETWORKED_BFT_DEVNET');assert.equal(verifyFinalityCertificate({certificate,validatorSet:app.consensus.validatorSet,stateHash:first.stateHash,height:first.height}),true);const corrupt=structuredClone(certificate);corrupt.votes[0].signature='invalid';const rejected=await fetch(`${validators[0].url}/v1/consensus/sync`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({state,stateHash:first.stateHash,certificate:corrupt,validatorSet:app.consensus.validatorSet})});assert.equal(rejected.status,409);assert.equal((await rejected.json()).error,'CONSENSUS_SYNC_CERTIFICATE_INVALID');assert.equal(app.consensus.validators.find(v=>v.id==='network-validator-4').status,'DIVERGENT');
  await stop(validators[3]);const restarted=await startValidator({id:validators[3].id,statePath:validators[3].statePath,keys:validators[3].keys});validators[3]=restarted;app.consensus.validators.find(v=>v.id===restarted.id).url=restarted.url;
  const second=await client.faucet({accountId:'bob',amount:20});assert.equal(second.validatorVotes,4);assert.equal((await client.network()).activeValidators,4);
  await stop(validators[3]);const third=await client.faucet({accountId:'carol',amount:30});assert.equal(third.validatorVotes,3);
  await stop(validators[2]);const height=(await client.network()).height;await assert.rejects(()=>client.faucet({accountId:'dave',amount:40}),error=>error.code==='NETWORK_CONSENSUS_PREPARE_QUORUM');assert.equal((await client.network()).height,height);assert.equal((await client.request('GET','/v1/accounts')).dave,undefined);
});

test('an unavailable selected proposer triggers a certified view change and commits safely',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'ael-view-change-')),validators=[];for(let index=1;index<=4;index++){const keys=createLocalAuthority();validators.push(await startValidator({id:`view-validator-${index}`,statePath:join(dir,`validator-${index}.json`),keys}))}t.after(async()=>Promise.all(validators.map(stop)));
  const config=validators.map(({id,url,publicKeyB64})=>({id,url,publicKeyB64})),app=createAelServer({port:0,statePath:join(dir,'coordinator.json'),networkValidators:config,consensusToken:token,consensusTimeoutMs:300}),address=await app.listen(),client=new AelClient(`http://127.0.0.1:${address.port}`);t.after(()=>app.close());
  const set=canonicalValidatorSet(config,1),selected=selectProposer({chainId:'ael-devnet-1',epoch:1,height:1,view:0,previousCertificateHash:'0'.repeat(64),validatorSet:set}).validatorId,failed=validators.find(item=>item.id===selected);await stop(failed);
  const result=await client.faucet({accountId:'view-change-account',amount:10}),network=await client.network();assert.equal(result.validatorVotes,3);assert.ok(network.finality.view>0);assert.match(network.finality.certificateHash,/^[a-f0-9]{64}$/);assert.match(network.finality.viewCertificateHash,/^[a-f0-9]{64}$/);assert.notEqual(network.finality.proposerId,selected);assert.equal(network.height,1);
});

test('two consecutive unavailable-proposer views retain quorum and commit in a later view',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'ael-consecutive-views-')),validators=[];for(let index=1;index<=4;index++){const keys=createLocalAuthority();validators.push(await startValidator({id:`consecutive-validator-${index}`,statePath:join(dir,`validator-${index}.json`),keys}))}t.after(async()=>Promise.all(validators.map(stop)));
  const config=validators.map(({id,url,publicKeyB64})=>({id,url,publicKeyB64})),app=createAelServer({port:0,statePath:join(dir,'coordinator.json'),networkValidators:config,consensusToken:token,consensusTimeoutMs:300}),address=await app.listen(),client=new AelClient(`http://127.0.0.1:${address.port}`);t.after(()=>app.close());const set=canonicalValidatorSet(config,1);let failedId=null;
  for(let attempt=0;attempt<30;attempt++){const height=app.engine.state.height+1,common={chainId:'ael-devnet-1',epoch:1,height,previousCertificateHash:app.consensus.previousCertificateHash,validatorSet:set},leaders=[0,1,2,3].map(view=>selectProposer({...common,view}).validatorId);if(leaders[0]===leaders[1]&&leaders.slice(2).some(id=>id!==leaders[0])){failedId=leaders[0];break}await client.faucet({accountId:`search-${attempt}`,amount:1})}assert.ok(failedId,'expected a deterministic consecutive-view fixture');await stop(validators.find(item=>item.id===failedId));const before=app.engine.state.height,result=await client.faucet({accountId:'after-two-views',amount:5}),network=await client.network();assert.equal(result.validatorVotes,3);assert.ok(network.finality.view>=2);assert.match(network.finality.viewCertificateHash,/^[a-f0-9]{64}$/);assert.equal(network.height,before+1);assert.notEqual(network.finality.proposerId,failedId);
});

test('coordinator restart restores the durable parent certificate and public index',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'ael-certificate-restart-')),validators=[];for(let index=1;index<=4;index++){const keys=createLocalAuthority();validators.push(await startValidator({id:`restart-validator-${index}`,statePath:join(dir,`validator-${index}.json`),keys}))}t.after(async()=>Promise.all(validators.map(stop)));const config=validators.map(({id,url,publicKeyB64})=>({id,url,publicKeyB64})),statePath=join(dir,'coordinator.json');let app=createAelServer({port:0,statePath,networkValidators:config,consensusToken:token,consensusTimeoutMs:500}),address=await app.listen(),client=new AelClient(`http://127.0.0.1:${address.port}`);const commit=await client.faucet({accountId:'restart-proof',amount:7}),before=await client.network(),certificateHash=before.finality.certificateHash;await app.close();app=createAelServer({port:0,statePath,networkValidators:config,consensusToken:token,consensusTimeoutMs:500});address=await app.listen();client=new AelClient(`http://127.0.0.1:${address.port}`);t.after(()=>app.close());const restored=await client.network(),certificate=await client.request('GET','/v1/consensus/certificates/latest');assert.equal(restored.height,commit.height);assert.equal(restored.finality.restored,true);assert.equal(restored.finality.certificateHash,certificateHash);assert.equal(app.consensus.previousCertificateHash,certificateHash);assert.equal(certificate.certificateHash,certificateHash);
});
