import test from 'node:test';
import assert from 'node:assert/strict';
import { AelEngine } from '../src/engine.js';
import { hash } from '../src/canonical.js';
import { SovereignGateway } from '../src/gateway.js';
import { earnedLiquidityBasic, fixture, runMandatorySimulations } from '../src/simulator.js';

test('T11-01 end-to-end admission is deterministic and price neutral', () => { const a=earnedLiquidityBasic(), b=earnedLiquidityBasic(); assert.equal(hash(a.engine.state),hash(b.engine.state)); assert.equal(a.spotPriceNeutral,true); assert.equal(a.engine.state.agents['agent-1'].reserves.external,1615); });
test('T11-02 duplicate lineage is rejected atomically', () => { const {engine:e}=earnedLiquidityBasic(), before=hash(e.state); assert.throws(()=>e.apply('admitEarned',{agentId:'agent-1',receiptId:'receipt-1',routeId:'solana-test',lineageId:'solana:tx:1',asset:'x',provablyControlledValue:1,routeHaircut:1,agentFundingRoot:'x'}),/DUPLICATE_LINEAGE/); assert.equal(hash(e.state),before); });
test('T11-03 gateway enforces capability and spend without root secrets', () => { const sag=new SovereignGateway({capabilities:[{id:'c',agentId:'a',action:'pay',spendLimit:10,expiresAt:10}]}); assert.equal(sag.evaluate({agentId:'a',action:'pay',amount:11,nonce:'1'},0).reason,'SPEND_LIMIT'); assert.equal(sag.evaluate({agentId:'a',action:'pay',amount:1,nonce:'2',seed:'never'},0).reason,'SECRET_MATERIAL_FORBIDDEN'); });
test('T11-04 runtime resumes from matching checkpoint', () => { const e=fixture(); e.apply('registerRuntime',{agentId:'agent-1',provider:'p1',replicas:[{provider:'p2',checkpointRoot:'cp'}],checkpointRoot:'cp',faultDomains:['a','b']}); e.apply('failRuntime',{agentId:'agent-1',provider:'p1'}); assert.equal(e.state.runtimes['agent-1'].active,'p2'); });
test('T11-05 mass sell cannot make reserve negative', () => { const {engine:e}=earnedLiquidityBasic(); assert.throws(()=>e.apply('sell',{agentId:'agent-1',tokens:1e9}),/INSUFFICIENT/); e.assertInvariants(); });
test('real routes default disabled until audited and capped', () => { const e=fixture(); e.apply('registerRoute',{routeId:'real',realValue:true,audited:false,cap:100}); assert.equal(e.state.routes.real.enabled,false); });
test('public accounting separates virtual and redeemable values', () => { const {engine:e}=earnedLiquidityBasic(), v=e.publicAgent('agent-1'); assert.equal(v.virtualLiquidity,1000); assert.equal(v.redeemableReserve,1615); assert.notEqual(v.virtualLiquidity,v.redeemableReserve); });
test('simulator covers insolvency, circular funding, and outage', () => { const r=runMandatorySimulations(); assert.deepEqual(r.scenarios,{normal:true,circularFunding:true,correlatedOutage:true,insolvency:true}); });
test('agent identity has no transferable owner field', () => { const e=new AelEngine(); e.apply('createAgent',{agentId:'a',rootPublicKey:'pub',constitutionRoot:'c'}); assert.equal('owner' in e.state.agents.a,false); });
test('agent referrals reject self-referral and remain non-financial until useful work',()=>{const e=new AelEngine();e.apply('createAgent',{agentId:'referrer',rootPublicKey:'p',constitutionRoot:'c'});assert.throws(()=>e.apply('createAgent',{agentId:'self',rootPublicKey:'p',constitutionRoot:'c',referrerAgentId:'self'}),/REFERRER_INVALID/);e.apply('createAgent',{agentId:'recruit',rootPublicKey:'p2',constitutionRoot:'c2',referrerAgentId:'referrer'});assert.deepEqual(e.state.agentReferrals.recruit.status,'PENDING');assert.equal(e.state.accounts.referrer,undefined);});
test('open-market work is atomically claimed by the first active agent',()=>{const e=new AelEngine();for(const id of ['a','b'])e.apply('createAgent',{agentId:id,rootPublicKey:`p-${id}`,constitutionRoot:'c'});e.apply('createWorkOrder',{orderId:'open',requesterRoot:'human',title:'Open task',fundedAmount:25,scopeHash:'scope'});assert.equal(e.state.orders.open.assignmentMode,'OPEN_MARKET');assert.equal(e.state.orders.open.agentId,null);e.apply('acceptWork',{orderId:'open',agentId:'a'});assert.equal(e.state.orders.open.agentId,'a');assert.throws(()=>e.apply('acceptWork',{orderId:'open',agentId:'b'}),/WORK_NOT_OPEN/);});
