import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createAelServer } from '../src/server.js';
import { AelClient, createLocalAuthority, signRuntimeAttestation, signRuntimeUsageApproval } from '../src/sdk.js';

const harness=async t=>{const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-runtime-provider-')),'state.json')}),address=await app.listen();t.after(()=>app.close());return new AelClient(`http://127.0.0.1:${address.port}`)};

test('issuer-signed attestation gates lease, heartbeat, metering, and failover',async t=>{
  const c=await harness(t),issuer=createLocalAuthority();await c.createAgent({agentId:'runtime-agent',rootPublicKey:'pub',constitutionRoot:'c'});
  await c.request('POST','/v1/runtime/providers',{providerId:'provider-a',operatorId:'operator-a',bond:100,faultDomain:'org-a',region:'eu',attestationProfiles:['R2']});
  await c.request('POST','/v1/runtime/providers',{providerId:'provider-b',operatorId:'operator-b',bond:100,faultDomain:'org-b',region:'us',attestationProfiles:['R2']});
  await c.request('POST','/v1/runtime/attestation-issuers',{issuerId:'issuer',publicKey:issuer.publicKey,vendor:'fixture-vendor-root',profiles:['R2']});
  const primary=await c.registerRuntimeOffer({offerId:'offer-a',providerId:'provider-a',faultDomain:'org-a',profile:'R2',measurement:'image-v2',pricePerHour:2}),replica=await c.registerRuntimeOffer({offerId:'offer-b',providerId:'provider-b',faultDomain:'org-b',profile:'R2',measurement:'image-v2',pricePerHour:2});
  const statement={attestationId:'att-1',issuerId:'issuer',providerId:'provider-a',offerId:primary.offerId,profile:'R2',measurement:'image-v2',nonce:'hardware-nonce',ephemeralPublicKey:'ephemeral-session-public',firmwareVersion:'fixture-firmware',expiresAtHeight:100};
  await assert.rejects(()=>c.submitRuntimeAttestation({...statement,signature:'invalid'}),error=>error.code==='ATTESTATION_SIGNATURE_INVALID');await c.submitRuntimeAttestation(signRuntimeAttestation(statement,issuer.privateKey));
  await c.leaseRuntime({leaseId:'lease-1',agentId:'runtime-agent',agentAuthorityId:'runtime-agent-authority',offerId:primary.offerId,replicaOfferIds:[replica.offerId],checkpointRoot:'checkpoint',attestationId:'att-1',cscReceiptHash:'csc-receipt',budgetCap:10});
  await c.request('POST','/v1/runtime/heartbeats',{leaseId:'lease-1',providerId:'provider-a',sequence:1,checkpointRoot:'checkpoint',measurement:'image-v2'});await c.request('POST','/v1/runtime/usage',{leaseId:'lease-1',providerId:'provider-a',epoch:1,amount:4,countersHash:'counters',agentApprovalVerified:true,agentApproval:{actorId:'runtime-agent-authority'}});
  await assert.rejects(()=>c.request('POST','/v1/runtime/usage',{leaseId:'lease-1',providerId:'provider-a',epoch:2,amount:7,countersHash:'counters-2',agentApprovalVerified:true,agentApproval:{actorId:'runtime-agent-authority'}}),/RUNTIME_USAGE_INVALID/);
  await c.request('POST','/v1/runtime/fail',{agentId:'runtime-agent',provider:'provider-a'});const state=await c.request('GET','/v1/state');assert.equal(state.runtimes['runtime-agent'].active,'provider-b');assert.equal(state.runtimeLeases['lease-1'].providerId,'provider-b');assert.equal(state.runtimeUsageReceipts['lease-1:1'].status,'FINAL');
});

test('runtime provider signing key cannot publish an offer for another provider',async t=>{const app=createAelServer({port:0,secureMode:true,bootstrapToken:'bootstrap',statePath:join(mkdtempSync(join(tmpdir(),'ael-runtime-provider-auth-')),'state.json')}),address=await app.listen();t.after(()=>app.close());const url=`http://127.0.0.1:${address.port}`,bootstrap=new AelClient(url,{headers:{'x-ael-bootstrap-token':'bootstrap'}}),adminKeys=createLocalAuthority(),providerKeys=createLocalAuthority();await bootstrap.bootstrapAuthority({actorId:'admin',publicKey:adminKeys.publicKey,roles:['ADMIN']});const admin=new AelClient(url,{actorId:'admin',privateKey:adminKeys.privateKey});await admin.act('addAuthority',{actorId:'provider-a',publicKey:providerKeys.publicKey,roles:['RUNTIME_PROVIDER'],capabilities:[{action:'registerRuntimeOffer',providerId:'provider-a',expiresAtHeight:100}]});const provider=new AelClient(url,{actorId:'provider-a',privateKey:providerKeys.privateKey});await assert.rejects(()=>provider.act('registerRuntimeOffer',{offerId:'forged',providerId:'provider-b',faultDomain:'other',profile:'R0',measurement:'m',pricePerHour:0}),/CAPABILITY_DENIED/)});

test('metering requires both provider intent and exact agent usage approval signatures',async t=>{
  const app=createAelServer({port:0,secureMode:true,bootstrapToken:'bootstrap',statePath:join(mkdtempSync(join(tmpdir(),'ael-runtime-metering-')),'state.json')}),address=await app.listen();t.after(()=>app.close());const url=`http://127.0.0.1:${address.port}`,bootstrap=new AelClient(url,{headers:{'x-ael-bootstrap-token':'bootstrap'}}),adminKeys=createLocalAuthority(),providerAKeys=createLocalAuthority(),providerBKeys=createLocalAuthority(),agentKeys=createLocalAuthority();
  await bootstrap.bootstrapAuthority({actorId:'admin',publicKey:adminKeys.publicKey,roles:['ADMIN']});const admin=new AelClient(url,{actorId:'admin',privateKey:adminKeys.privateKey});for(const[actorId,keys]of[['pa',providerAKeys],['pb',providerBKeys]])await admin.act('addAuthority',{actorId,publicKey:keys.publicKey,roles:['RUNTIME_PROVIDER'],capabilities:[{action:'registerRuntimeOffer',providerId:actorId,expiresAtHeight:100},{action:'submitRuntimeUsage',providerId:actorId,expiresAtHeight:100}]});await admin.act('addAuthority',{actorId:'agent-auth',publicKey:agentKeys.publicKey,roles:['AGENT'],capabilities:['acceptWork']});
  for(const[providerId,faultDomain]of[['pa','fd-a'],['pb','fd-b']])await admin.act('registerRuntimeProvider',{providerId,operatorId:providerId,bond:100,faultDomain,region:'test',attestationProfiles:['R0']});const pa=new AelClient(url,{actorId:'pa',privateKey:providerAKeys.privateKey}),pb=new AelClient(url,{actorId:'pb',privateKey:providerBKeys.privateKey});await pa.act('registerRuntimeOffer',{offerId:'oa',providerId:'pa',faultDomain:'fd-a',profile:'R0',measurement:'m',pricePerHour:0});await pb.act('registerRuntimeOffer',{offerId:'ob',providerId:'pb',faultDomain:'fd-b',profile:'R0',measurement:'m',pricePerHour:0});await admin.act('createAgent',{agentId:'agent',rootPublicKey:'root-pub',constitutionRoot:'c'});await admin.act('createRuntimeLease',{leaseId:'lease',agentId:'agent',agentAuthorityId:'agent-auth',offerId:'oa',replicaOfferIds:['ob'],checkpointRoot:'cp',attestation:{kind:'FIXTURE',provider:'pa',measurement:'m',nonce:'n',accepted:true},budgetCap:10});
  const statement={leaseId:'lease',epoch:1,amount:3,countersHash:'counters'},approval=signRuntimeUsageApproval(statement,'agent-auth',agentKeys.privateKey);await assert.rejects(()=>pa.act('submitRuntimeUsage',{...statement,providerId:'pa',amount:4,agentApproval:approval}),error=>error.code==='RUNTIME_USAGE_AGENT_SIGNATURE_INVALID');await pa.act('submitRuntimeUsage',{...statement,providerId:'pa',agentApproval:approval});const state=await bootstrap.request('GET','/v1/state');assert.equal(state.runtimeLeases.lease.spent,3);assert.equal(state.runtimeUsageReceipts['lease:1'].agentApproval.actorId,'agent-auth');
});
