import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createAelServer } from '../src/server.js';
import { AelClient } from '../src/sdk.js';

test('human and agent API completes marketplace-to-earned flow and persists it', async t => {
  const dir=mkdtempSync(join(tmpdir(),'ael-api-')), statePath=join(dir,'state.json'), app=createAelServer({port:0,statePath});
  const address=await app.listen(), client=new AelClient(`http://127.0.0.1:${address.port}`); t.after(()=>app.close());
  await client.createAgent({agentId:'api-agent',rootPublicKey:'public-only',constitutionRoot:'constitution',virtualLiquidity:1000});
  await client.request('POST','/v1/routes',{routeId:'test-route',realValue:false,cap:1000});
  const work=await client.createWorkOrder({agentId:'api-agent',title:'Human request',fundedAmount:100,scopeHash:'scope'});
  await client.acceptWork(work.orderId,{agentId:'api-agent'});
  const receipt=await client.finalizeReceipt({orderId:work.orderId,paymentId:'payment-api',amount:100,finalized:true,payerRoot:'human-root',verifiers:['v1','v2'],publicData:{deliverableHash:'hash'}});
  await client.admitEarned({agentId:'api-agent',receiptId:receipt.receiptId,routeId:'test-route',lineageId:'evm:1:0',asset:'TEST',provablyControlledValue:100,routeHaircut:.8,agentFundingRoot:'agent-root'});
  assert.equal((await client.reserve('api-agent')).redeemableReserve,80);
  assert.equal((await client.getProvenance('evm:1:0')).recognized,80);
  assert.equal(JSON.parse(readFileSync(statePath)).height,6);
  const network=await client.network(); assert.equal(network.validatorCount,4); assert.equal(network.activeValidators,4); assert.equal(new Set(network.validators.map(v=>v.stateHash)).size,1);
});

test('landing page offers a read-only evidence-first route deck',async t=>{const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-home-route-')),'state.json')}),address=await app.listen(),base=`http://127.0.0.1:${address.port}`;t.after(()=>app.close());const before=await fetch(`${base}/health`).then(r=>r.json()),[home,script]=await Promise.all([fetch(`${base}/`).then(r=>r.text()),fetch(`${base}/home.js`).then(r=>r.text())]);assert.match(home,/data-home-route/);assert.match(home,/data-home-route-tab="agent"/);assert.match(home,/data-home-route-tab="requester"/);assert.match(home,/data-home-route-tab="operator"/);assert.match(home,/local consent only/i);assert.match(home,/home\.js/);assert.match(script,/agent-trust/);assert.match(script,/agent-start/);assert.match(script,/agent-trust-compare/);assert.match(home,/creates an identity, contacts another agent, or installs software/i);const after=await fetch(`${base}/health`).then(r=>r.json());assert.equal(after.height,before.height);assert.equal(after.stateHash,before.stateHash);});

test('terminal portal, public network data, downloads, and complete demo are available', async t => {
  const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-web-')),'state.json')}), address=await app.listen(), base=`http://127.0.0.1:${address.port}`; t.after(()=>app.close());
  for(const route of ['/','/about','/article','/join','/onboard','/agent-start','/agent-console','/agent-seed','/work-brief','/work-audit','/agents','/work','/operators','/network','/topology','/infrastructure','/blocks','/token','/developers','/whitepaper','/wallet','/privacy','/readiness','/validation','/memory','/contribute','/roadmap']){
    const response=await fetch(`${base}${route}`); assert.equal(response.status,200,route); assert.match(await response.text(),/<title>[^<]*AEL[^<]*<\/title>/i,route);
  }
  const token=await fetch(`${base}/v1/token`).then(r=>r.json()); assert.equal(token.symbol,'AEL'); assert.equal(token.chainId,'ael-devnet-1'); assert.equal(token.testnet,true);
  const startupWithUnsafeForwardedProtocol=await fetch(`${base}/v1/agent-startup`,{headers:{'x-forwarded-proto':'javascript'}}).then(r=>r.json());assert.equal(startupWithUnsafeForwardedProtocol.origin,base);assert.ok(startupWithUnsafeForwardedProtocol.readFirst.every(url=>url.startsWith(base)));
  const tokenomics=await fetch(`${base}/v1/tokenomics`).then(r=>r.json());assert.equal(tokenomics.schema,'AEL-TOKENOMICS/1');assert.equal(tokenomics.asset.network,'PUBLIC_DEVNET');assert.equal(tokenomics.asset.monetaryValue,false);assert.equal(tokenomics.workSettlement.publicFunding,'NATIVE_ESCROW');assert.equal(tokenomics.policy.faucetLifetimeMaximumPerAccount,10_000);
  const nodes=await fetch(`${base}/v1/nodes`).then(r=>r.json()); assert.equal(nodes.mode,'SIGNED_STATE_FOLLOWERS'); assert.match(nodes.consensusBoundary,/do not join/i);
  const topology=await fetch(`${base}/v1/topology`).then(r=>r.json());assert.equal(topology.schema,'AEL-NETWORK-TOPOLOGY/1');assert.equal(topology.summary.consensusValidators,4);assert.match(topology.locationPolicy,/never geolocates/i);
  const readiness=await fetch(`${base}/v1/mainnet/readiness`).then(r=>r.json());assert.equal(readiness.schema,'AEL-MAINNET-READINESS/1');assert.equal(readiness.ready,false);assert.ok(readiness.summary.blocking.includes('networked-bft'));
  const validation=await fetch(`${base}/v1/validation`).then(r=>r.json());assert.equal(validation.schema,'AEL-POUW-POLICY/1');assert.match(validation.strategy,/EVIDENCE/);
  const manifest=await fetch(`${base}/v1/manifest`).then(r=>r.json());assert.equal(manifest.chainId,'ael-devnet-1');assert.equal(manifest.signing.privateKeysAccepted,false);assert.match(manifest.discovery.agentStartup,/\/v1\/agent-startup$/);assert.match(manifest.discovery.agentIntake,/\.well-known\/ael-agent-intake\.json$/);assert.equal(manifest.discovery.agentIntakeSchema,'AEL-AGENT-INTAKE/1');assert.match(manifest.discovery.agentSeeding,/\/v1\/agent-seeding$/);assert.match(manifest.discovery.agentSeedPage,/\/agent-seed$/);assert.match(manifest.discovery.agentLineage,/\/v1\/agent-lineage\/\{agentId\}$/);assert.match(manifest.discovery.agentLineagePage,/\/agent-lineage\?root=\{agentId\}$/);assert.match(manifest.discovery.agentConsole,/\/agent-console$/);assert.match(manifest.discovery.agentOperations,/\/v1\/agents\/\{agentId\}\/operations$/);assert.match(manifest.discovery.agentDirectory,/\/v1\/agent-directory$/);assert.equal(manifest.discovery.agentDirectorySchema,'AEL-AGENT-CAPABILITY-DIRECTORY/1');assert.match(manifest.discovery.workAudit,/\/v1\/work-orders\/\{orderId\}\/audit$/);assert.match(manifest.discovery.tokenomics,/\/v1\/tokenomics$/);assert.match(manifest.discovery.walletCompatibility,/\/v1\/wallet\/compatibility$/);assert.match(manifest.downloads.walletReleaseManifest,/\/downloads\/ael-wallet-release\.json$/);assert.match(manifest.onboarding.operatorGuide,/\/operators$/);
  const replicaRegistry=await fetch(`${base}/v1/replicas`).then(r=>r.json());assert.equal(replicaRegistry.schema,'AEL-REPLICA-REGISTRY/1');assert.equal(replicaRegistry.minimumRecommendedOrigins,2);assert.deepEqual(replicaRegistry.replicas,[]);assert.match(manifest.discovery.replicas,/\/v1\/replicas$/);
  const wellKnown=await fetch(`${base}/.well-known/ael.json`).then(r=>r.json());assert.equal(wellKnown.schema,'AEL-NETWORK-MANIFEST/1');
  const walletManifestResponse=await fetch(`${base}/wallet.webmanifest`),walletManifest=await walletManifestResponse.json();assert.match(walletManifestResponse.headers.get('content-type'),/application\/manifest\+json/);assert.equal(walletManifest.display,'standalone');assert.equal(walletManifest.start_url,'/wallet?source=installed');
  const serviceWorker=await fetch(`${base}/wallet-sw.js`);assert.equal(serviceWorker.status,200);assert.equal(serviceWorker.headers.get('service-worker-allowed'),'/');assert.match(await serviceWorker.text(),/ael-wallet-shell-v8/);
  const walletHtml=await fetch(`${base}/wallet`).then(r=>r.text());assert.match(walletHtml,/rel="manifest" href="\/wallet\.webmanifest"/);assert.match(walletHtml,/data-wallet-channel="chrome"/);
  assert.match(walletHtml,/consent-gated dApps/i);assert.match(walletHtml,/Phantom does not let users add custom networks/i);const walletRelease=await fetch(`${base}/v1/wallet/releases`).then(r=>r.json());assert.equal(walletRelease.version,'0.7.0');assert.equal(walletRelease.webApp.status,'LIVE');assert.equal(walletRelease.extensions.chrome.installUrl,null);assert.match(walletRelease.extensions.chrome.sha256,/^[a-f0-9]{64}$/);assert.equal(walletRelease.security.rawSigningApi,false);const compatibility=await fetch(`${base}/v1/wallet/compatibility`).then(r=>r.json());assert.equal(compatibility.schema,'AEL-WALLET-COMPATIBILITY/1');assert.equal(compatibility.wallets.phantom.nativeNetworkImport,false);assert.equal(compatibility.wallets.metamask.customNetworkImport,false);assert.equal(compatibility.wallets.walletConnect.customNamespacePossible,true);
  assert.match(walletHtml,/id="agent-referrals"/);assert.match(walletHtml,/id="referral-qualified"/);
  const joinHtml=await fetch(`${base}/join`).then(r=>r.text()),joinJs=await fetch(`${base}/join.js`).then(r=>r.text()),workHtml=await fetch(`${base}/work`).then(r=>r.text()),onboardHtml=await fetch(`${base}/onboard`).then(r=>r.text());assert.match(joinHtml,/id="agent-next"/);assert.match(joinHtml,/data-join-intro/);assert.match(joinHtml,/id="agent-console-link"/);assert.match(joinHtml,/id="agent-referrals"/);assert.match(joinHtml,/id="referral-rows"/);assert.match(joinJs,/renderJobComposer\(\)/);assert.match(joinJs,/createWorkOrder/);assert.match(joinJs,/private scope text locally/);assert.match(joinJs,/joinQuery\.get\('next'\)==='publish-work'/);assert.match(joinJs,/queryRole=joinQuery\.get\('role'/);assert.match(joinJs,/if\(agentNext\)/);assert.match(joinJs,/agents\/\$\{encodeURIComponent\(identity\.actorId\)\}\/operations/);assert.match(joinJs,/redeemable reserve/);assert.match(joinJs,/agent-console\?agent=/);assert.match(joinJs,/agent-lineage\?root=/);assert.match(joinJs,/agent-seed\?inviter=/);assert.match(joinJs,/v1\/work-orders\?status=OPEN&assignmentMode=OPEN_MARKET/);assert.match(workHtml,/\/join\?role=HUMAN&amp;next=publish-work/);assert.match(workHtml,/advisory capabilities/i);assert.match(workHtml,/not prove competence/i);assert.match(onboardHtml,/bounded identity-bound capability set/);assert.match(onboardHtml,/\/v1\/agent-startup/);
  const agentsHtml=await fetch(`${base}/agents`).then(r=>r.text());assert.match(agentsHtml,/data-referrals/);assert.match(agentsHtml,/referral-ledger/);assert.match(agentsHtml,/capability-directory/);assert.match(agentsHtml,/data-beacon-capability/);assert.match(agentsHtml,/data-beacons/);assert.match(agentsHtml,/normalised directory/i);assert.match(agentsHtml,/never contacts it from this page/i);const portalJs=await fetch(`${base}/portal.js`).then(r=>r.text());assert.match(portalJs,/agent-console\?agent=/);assert.match(portalJs,/agent-lineage\?root=/);assert.match(portalJs,/work-audit\?order=/);assert.match(portalJs,/beaconDirectory/);assert.match(portalJs,/v1\/agent-directory/);assert.match(portalJs,/requiredCapabilities/);
  const consoleHtml=await fetch(`${base}/agent-console`).then(r=>r.text()),consoleJs=await fetch(`${base}/agent-console.js`).then(r=>r.text());assert.match(consoleHtml,/without connecting a wallet or supplying a key/i);assert.match(consoleHtml,/data-agent-form/);assert.match(consoleHtml,/data-agent-links/);assert.match(consoleHtml,/agent-lineage/);assert.match(consoleHtml,/agent-console\.js/);assert.match(consoleJs,/resolved\.origin!==location\.origin/);assert.match(consoleJs,/open lineage explorer/);assert.match(consoleJs,/agent-lineage\?root=/);assert.match(consoleJs,/work-audit\?order=/);
  const auditHtml=await fetch(`${base}/work-audit`).then(r=>r.text()),auditJs=await fetch(`${base}/work-audit.js`).then(r=>r.text());assert.match(auditHtml,/never connects a wallet, receives a key, accepts work/i);assert.match(auditHtml,/data-audit-form/);assert.match(auditHtml,/data-audit-timeline/);assert.match(auditJs,/v1\/work-orders\/\$\{encodeURIComponent\(orderId\)\}\/audit/);assert.match(auditJs,/chain\.valid/);const seedHtml=await fetch(`${base}/agent-seed`).then(r=>r.text()),seedJs=await fetch(`${base}/agent-seed.js`).then(r=>r.text());assert.match(seedHtml,/Grow by proof,[\s\S]*not by spam/i);assert.match(seedHtml,/data-seed-form/);assert.match(seedHtml,/data-seed-referred/);assert.match(seedHtml,/data-copy-seed-command/);assert.match(seedHtml,/advertised mirrors/i);assert.match(seedHtml,/self-custodied/i);assert.match(seedJs,/v1\/agent-seeding/);assert.match(seedJs,/mirrorObservation/);assert.match(seedJs,/--seed/);assert.match(seedJs,/client rejects this seed/);const lineageHtml=await fetch(`${base}/agent-lineage`).then(r=>r.text()),lineageJs=await fetch(`${base}/agent-lineage.js`).then(r=>r.text());assert.match(lineageHtml,/Trace contribution,[\s\S]*not hype/i);assert.match(lineageHtml,/data-lineage-form/);assert.match(lineageHtml,/no automatic rewards/i);assert.match(lineageJs,/v1\/agent-lineage/);assert.match(lineageJs,/proofBoundary/);
  assert.match(agentsHtml,/two independently controlled agent operators/i);assert.match(agentsHtml,/independent operator page/i);
  const operatorsHtml=await fetch(`${base}/operators`).then(r=>r.text());assert.match(operatorsHtml,/two independently controlled agents/i);assert.match(operatorsHtml,/Never share an AEL private key/i);assert.match(operatorsHtml,/AEL-INDEPENDENT-MIRROR-PROOF\/1/);
  const tokenHtml=await fetch(`${base}/token`).then(r=>r.text());assert.match(tokenHtml,/data-tokenomics-json/);assert.match(tokenHtml,/no global supply cap/i);
  const llms=await fetch(`${base}/llms.txt`).then(r=>r.text());assert.match(llms,/Never transmit a private key/);assert.match(llms,/Live agent startup brief/);assert.match(llms,/Seven voting validators/);assert.match(llms,/five agent replicas/);assert.match(llms,/Agent plus node procedure/);
  const openapi=await fetch(`${base}/openapi.json`).then(r=>r.json());assert.equal(openapi.openapi,'3.1.0');assert.equal(openapi.paths['/v1/agent-startup'].get.responses['200'].description,'AEL-AGENT-STARTUP/1');assert.equal(openapi.paths['/.well-known/ael-agent-intake.json'].get.responses['200'].description,'AEL-AGENT-INTAKE/1');assert.equal(openapi.paths['/v1/agent-seeding'].get.responses['200'].description,'AEL-AGENT-SEEDING/1');assert.equal(openapi.paths['/v1/agent-lineage/{agentId}'].get.responses['200'].description,'AEL-AGENT-LINEAGE/1');assert.equal(openapi.paths['/v1/agents/{agentId}/operations'].get.responses['200'].description,'AEL-AGENT-OPERATIONS/1');assert.equal(openapi.paths['/v1/agent-directory'].get.responses['200'].description,'AEL-AGENT-CAPABILITY-DIRECTORY/1');assert.equal(openapi.paths['/v1/work-orders/{orderId}/audit'].get.responses['200'].description,'AEL-WORK-AUDIT/1');
  await fetch(`${base}/v1/work-orders`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orderId:'open-api-work',requesterRoot:'human',title:'Open API task',fundedAmount:10,scopeHash:'scope'})});
  const openWork=await fetch(`${base}/v1/work-orders?status=OPEN&assignmentMode=OPEN_MARKET`).then(r=>r.json());assert.equal(openWork.length,1);assert.equal(openWork[0].agentId,null);
  const workRecord=await fetch(`${base}/v1/work-orders/open-api-work`).then(r=>r.json());assert.equal(workRecord.orderId,'open-api-work');assert.equal(workRecord.assignmentMode,'OPEN_MARKET');assert.equal(workRecord.links.audit,`${base}/v1/work-orders/open-api-work/audit`);const workAudit=await fetch(`${base}/v1/work-orders/open-api-work/audit`).then(r=>r.json());assert.equal(workAudit.schema,'AEL-WORK-AUDIT/1');assert.equal(workAudit.order.orderId,'open-api-work');assert.equal(workAudit.chain.valid,true);assert.equal((await fetch(`${base}/v1/work-orders/missing`)).status,404);
  for(const route of ['/downloads/ael-sdk.js','/downloads/canonical.js','/downloads/ael-sdk.py','/downloads/ael-join.mjs','/downloads/ael-agent-host.mjs','/downloads/ael-mirror-proof.mjs','/downloads/validator-node.js','/downloads/ael-wallet-chromium.zip','/downloads/ael-wallet-firefox.zip','/downloads/ael-wallet-safari-source.zip','/downloads/wallet-extension.zip','/downloads/ael-network-skill.zip','/downloads/public-launch-article.md','/downloads/x-launch-thread.md','/downloads/development-to-mainnet.md','/downloads/zero-budget-growth.md','/downloads/agent-operator-handoff.md','/downloads/sbom.spdx.json','/downloads/audit-manifest.json','/downloads/mainnet-phase-gates.json']){
    const response=await fetch(`${base}${route}`); assert.equal(response.status,200,route); assert.ok((await response.arrayBuffer()).byteLength>100,route);
  }
  for(const route of ['/downloads/ael-wallet-chrome-store.zip','/downloads/ael-wallet-edge-store.zip']){const response=await fetch(`${base}${route}`);assert.equal(response.status,200,route);assert.ok((await response.arrayBuffer()).byteLength>100,route)}
  const walletBuild=await fetch(`${base}/downloads/ael-wallet-release.json`).then(r=>r.json());assert.equal(walletBuild.version,'0.7.0');assert.match(walletBuild.artifacts['ael-wallet-firefox.zip'].sha256,/^[a-f0-9]{64}$/);
  const releaseHash=await fetch(`${base}/downloads/release.sha256`).then(r=>r.text());assert.match(releaseHash,/^[a-f0-9]{64}  dist\/ael-local-devnet\.tar\.gz\n$/);
  const sbom=await fetch(`${base}/downloads/sbom.spdx.json`).then(r=>r.json());assert.equal(sbom.spdxVersion,'SPDX-2.3');assert.equal(sbom.packages[0].versionInfo,'0.13.1');assert.equal(sbom.packages[0].filesAnalyzed,false);
  const result=await fetch(`${base}/v1/demo`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'}).then(r=>r.json());
  const reserve=await fetch(`${base}/v1/agents/${result.agentId}/reserve`).then(r=>r.json()); assert.equal(reserve.redeemableReserve,450);
  const operations=await fetch(`${base}/v1/agents/${result.agentId}/operations`).then(r=>r.json());assert.equal(operations.schema,'AEL-AGENT-OPERATIONS/1');assert.equal(operations.agent.id,result.agentId);assert.equal(operations.work.total,1);assert.equal(operations.chain.valid,true);assert.equal(operations.links.console,`${base}/agent-console?agent=${result.agentId}`);assert.equal(operations.links.chainVerify,`${base}/v1/chain/verify`);assert.equal('privateKey' in operations,false);
});

test('wallet release exposes only a LIVE official store listing',async t=>{
  const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-wallet-release-')),'state.json')}),address=await app.listen(),base=`http://127.0.0.1:${address.port}`;t.after(()=>app.close());
  const common={channel:'CHROME',version:'0.7.0',auditorId:'auditor-one',independenceGroup:'review-one',releaseHash:'a'.repeat(64),evidenceHash:'b'.repeat(64),attestedAtHeight:1};
  app.engine.state.walletDistributionAttestations={reviewed:{...common,status:'REVIEWED',listingUrl:'https://chromewebstore.google.com/detail/ael-wallet/official-id'}};
  assert.equal((await fetch(`${base}/v1/wallet/releases`).then(r=>r.json())).extensions.chrome.installUrl,null);
  app.engine.state.walletDistributionAttestations.live={...common,status:'LIVE',attestedAtHeight:2,listingUrl:'https://chromewebstore.google.com/detail/ael-wallet/official-id'};
  assert.equal((await fetch(`${base}/v1/wallet/releases`).then(r=>r.json())).extensions.chrome.installUrl,'https://chromewebstore.google.com/detail/ael-wallet/official-id');
  app.engine.state.walletDistributionAttestations.live.listingUrl='https://lookalike.example/detail/ael-wallet';
  assert.equal((await fetch(`${base}/v1/wallet/releases`).then(r=>r.json())).extensions.chrome.installUrl,null);
});

test('runtime marketplace requires distinct fault domains and fails over', async t => {
  const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-runtime-')),'state.json')}), address=await app.listen(), c=new AelClient(`http://127.0.0.1:${address.port}`); t.after(()=>app.close());
  await c.createAgent({agentId:'runner',rootPublicKey:'pub',constitutionRoot:'const'});
  const a=await c.registerRuntimeOffer({provider:'provider-a',faultDomain:'eu-a',measurement:'runtime-v1',pricePerHour:1}), b=await c.registerRuntimeOffer({provider:'provider-b',faultDomain:'eu-b',measurement:'runtime-v1',pricePerHour:2});
  await c.leaseRuntime({agentId:'runner',offerId:a.offerId,replicaOfferIds:[b.offerId],checkpointRoot:'cp-1',attestation:{kind:'FIXTURE',provider:'provider-a',measurement:'runtime-v1',nonce:'fresh-1',accepted:true}});
  await c.request('POST','/v1/runtime/fail',{agentId:'runner',provider:'provider-a'});
  const state=await c.request('GET','/v1/state'); assert.equal(state.runtimes.runner.active,'provider-b');
});

test('runtime attestation nonce cannot replay and measurement must match policy',async t=>{
  const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-attest-')),'state.json')}),address=await app.listen(),c=new AelClient(`http://127.0.0.1:${address.port}`);t.after(()=>app.close());
  for(const agentId of ['a','b'])await c.createAgent({agentId,rootPublicKey:`pub-${agentId}`,constitutionRoot:'c'});
  const primary=await c.registerRuntimeOffer({provider:'p',faultDomain:'one',measurement:'good',pricePerHour:1}),replica=await c.registerRuntimeOffer({provider:'q',faultDomain:'two',measurement:'good',pricePerHour:1});
  await assert.rejects(()=>c.leaseRuntime({agentId:'a',offerId:primary.offerId,replicaOfferIds:[replica.offerId],checkpointRoot:'cp',attestation:{kind:'FIXTURE',provider:'p',measurement:'bad',nonce:'n',accepted:true}}),/ATTESTATION_REJECTED/);
  await c.leaseRuntime({agentId:'a',offerId:primary.offerId,replicaOfferIds:[replica.offerId],checkpointRoot:'cp',attestation:{kind:'FIXTURE',provider:'p',measurement:'good',nonce:'n',accepted:true}});
  const another=await c.registerRuntimeOffer({offerId:'second-p-offer',provider:'p',faultDomain:'one',measurement:'good',pricePerHour:1}),anotherReplica=await c.registerRuntimeOffer({offerId:'second-q-offer',provider:'q',faultDomain:'two',measurement:'good',pricePerHour:1});
  await assert.rejects(()=>c.leaseRuntime({agentId:'b',offerId:another.offerId,replicaOfferIds:[anotherReplica.offerId],checkpointRoot:'cp',attestation:{kind:'FIXTURE',provider:'p',measurement:'good',nonce:'n',accepted:true}}),/ATTESTATION_REJECTED/);
});

test('agent match inspector is discoverable without granting acceptance authority',async t=>{
  const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-agent-match-page-')),'state.json')}),address=await app.listen(),base=`http://127.0.0.1:${address.port}`;t.after(()=>app.close());
  const [manifest,card,page,script]=await Promise.all([fetch(`${base}/v1/manifest`).then(r=>r.json()),fetch(`${base}/.well-known/agent-card.json`).then(r=>r.json()),fetch(`${base}/agent-match`).then(r=>r.text()),fetch(`${base}/agent-match.js`).then(r=>r.text())]);
  assert.equal(manifest.discovery.agentWorkMatchPage,`${base}/agent-match?agent={agentId}`);
  assert.equal(card.metadata.agentWorkMatchPage,`${base}/agent-match?agent={agentId}`);
  assert.match(page,/data-match-evidence/);
  assert.match(page,/separately authorized active agent/i);
  assert.match(script,/v1\/agents\//);
  assert.match(script,/work-match/);
});

test('agent opportunity index binds public work to one reviewable snapshot without accepting it',async t=>{
  const app=createAelServer({port:0,statePath:join(mkdtempSync(join(tmpdir(),'ael-opportunity-index-')),'state.json')}),address=await app.listen(),base=`http://127.0.0.1:${address.port}`,client=new AelClient(base);t.after(()=>app.close());
  await fetch(`${base}/v1/work-orders`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orderId:'open-opportunity',requesterRoot:'human',title:'Reviewable public work',scopeHash:'scope-open',fundedAmount:8,assignmentMode:'OPEN_MARKET',requiredCapabilities:['research']})});
  await fetch(`${base}/v1/work-orders`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orderId:'targeted-opportunity',requesterRoot:'human',agentId:'named-agent',title:'Excluded targeted work',scopeHash:'scope-targeted',fundedAmount:99})});
  const before=await fetch(`${base}/health`).then(r=>r.json()),[index,verification,manifest,card,mcp,page,script]=await Promise.all([client.agentOpportunities(),client.verifyAgentOpportunities(),fetch(`${base}/v1/manifest`).then(r=>r.json()),fetch(`${base}/.well-known/agent-card.json`).then(r=>r.json()),fetch(`${base}/mcp`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:21,method:'tools/call',params:{name:'ael_agent_opportunities',arguments:{}}})}).then(r=>r.json()),fetch(`${base}/agent-opportunities`).then(r=>r.text()),fetch(`${base}/agent-opportunities.js`).then(r=>r.text())]);
  assert.equal(index.schema,'AEL-AGENT-OPPORTUNITY-INDEX/1');assert.deepEqual(index.opportunities.map(item=>item.order.orderId),['open-opportunity']);assert.equal(index.opportunities[0].review.status,'REVIEW_REQUIRED');assert.match(index.evidence.opportunityIndexHash,/^[a-f0-9]{64}$/);assert.equal(index.mutationsPerformed,false);assert.equal(verification.verified,true);assert.equal(verification.checks.opportunityIndexHash,true);assert.equal(manifest.discovery.agentOpportunities,`${base}/v1/agent-opportunities`);assert.equal(manifest.discovery.agentOpportunitiesPage,`${base}/agent-opportunities`);assert.equal(card.metadata.agentOpportunitiesMcpTool,'ael_agent_opportunities');assert.equal(mcp.result.structuredContent.opportunities[0].order.orderId,'open-opportunity');assert.match(page,/data-opportunities-evidence/);assert.match(page,/separately authorized active agent/i);assert.match(script,/agent-opportunities/);assert.match(script,/opportunityIndexHash/);
  const after=await fetch(`${base}/health`).then(r=>r.json());assert.equal(after.height,before.height);assert.equal(after.stateHash,before.stateHash);
});
