import test from 'node:test';
import assert from 'node:assert/strict';
import { sign } from 'node:crypto';
import { createServer } from 'node:http';
import { canonicalize, hash } from '../src/canonical.js';
import { AelEngine } from '../src/engine.js';
import { createLocalAuthority } from '../src/sdk.js';
import { buildCertificate, canonicalValidatorSet, voteDomain } from '../src/consensus-primitives.js';
import { createStateCheckpoint, fetchStateFromPeers, verifyStateCheckpoint } from '../src/state-sync.js';

const fixture=()=>{const authorities=[1,2,3,4].map(index=>({id:`sync-v${index}`,...createLocalAuthority()})),validators=authorities.map(item=>({id:item.id,publicKeyB64:Buffer.from(item.publicKey).toString('base64')})),set=canonicalValidatorSet(validators,1),engine=new AelEngine(),stateHash=engine.apply('faucet',{accountId:'checkpoint-user',amount:9}),blockHash=engine.state.blocks.at(-1).blockHash,base={chainId:'ael-devnet-1',epoch:1,height:1,view:0,phase:'PRECOMMIT',proposalId:'checkpoint-proposal',blockHash,stateHash,validatorSetHash:set.validatorSetHash},votes=authorities.slice(0,3).map(item=>{const body=voteDomain({...base,validatorId:item.id});return{...body,signature:sign(null,Buffer.from(canonicalize(body)),item.privateKey).toString('base64')}}),certificate=buildCertificate({...base,validatorSet:set,votes});return{state:engine.state,certificate,validatorSet:set}};

test('chunked checkpoint reconstructs certificate-finalized state and rejects a corrupt provider chunk',()=>{const{state,certificate,validatorSet}=fixture(),checkpoint=createStateCheckpoint(state,certificate,1024),restored=verifyStateCheckpoint({manifest:checkpoint.manifest,chunks:checkpoint.chunks,certificate,validatorSet});assert.equal(hash(restored),hash(state));const corrupt=checkpoint.chunks.map(Buffer.from);corrupt[0][0]^=1;assert.throws(()=>verifyStateCheckpoint({manifest:checkpoint.manifest,chunks:corrupt,certificate,validatorSet}),/STATE_CHUNK_INVALID/)});

test('multi-source sync requires matching checkpoint manifests and alternates chunk providers',async t=>{const{state,certificate,validatorSet}=fixture(),checkpoint=createStateCheckpoint(state,certificate,1024),served=[];const start=()=>new Promise(resolve=>{const server=createServer((request,response)=>{const url=new URL(request.url,'http://peer');response.setHeader('content-type','application/json');if(url.pathname==='/v1/state/checkpoint')return response.end(JSON.stringify(checkpoint.manifest));if(url.pathname===`/v1/consensus/certificates/${certificate.certificateHash}`)return response.end(JSON.stringify(certificate));const match=url.pathname.match(/^\/v1\/state\/chunks\/(\d+)$/);if(match){const index=Number(match[1]);served.push({port:server.address().port,index});return response.end(JSON.stringify({data:checkpoint.chunks[index].toString('base64')}))}response.statusCode=404;response.end('{}')}).listen(0,'127.0.0.1',()=>resolve(server))});const peers=[await start(),await start()];t.after(()=>Promise.all(peers.map(server=>new Promise(resolve=>server.close(resolve)))));const urls=peers.map(server=>`http://127.0.0.1:${server.address().port}`),result=await fetchStateFromPeers(urls,{validatorSet,minSources:2});assert.equal(hash(result.state),hash(state));assert.deepEqual(new Set(result.sources),new Set(urls));assert.ok(new Set(served.map(item=>item.port)).size>=Math.min(2,checkpoint.chunks.length))});
