import test from 'node:test';
import assert from 'node:assert/strict';
import { sign } from 'node:crypto';
import { canonicalize } from '../src/canonical.js';
import { createLocalAuthority } from '../src/sdk.js';
import { buildCertificate, canonicalValidatorSet, voteDomain } from '../src/consensus-primitives.js';
import { activateValidatorEpoch, buildReadinessCertificate, proposeValidatorSetChange, readinessDomain } from '../src/validator-governance.js';

const authorities=[1,2,3,4].map(index=>({id:`gov-v${index}`,...createLocalAuthority(),faultDomain:`domain-${index}`})),set=canonicalValidatorSet(authorities.map(item=>({id:item.id,publicKeyB64:Buffer.from(item.publicKey).toString('base64'),faultDomain:item.faultDomain})),1);
const finality=()=>{const base={chainId:'ael-devnet-1',epoch:1,height:10,view:0,phase:'PRECOMMIT',proposalId:'epoch-parent',blockHash:'a'.repeat(64),stateHash:'b'.repeat(64),validatorSetHash:set.validatorSetHash},votes=authorities.slice(0,3).map(item=>{const body=voteDomain({...base,validatorId:item.id});return{...body,signature:sign(null,Buffer.from(canonicalize(body)),item.privateKey).toString('base64')}});return buildCertificate({...base,validatorSet:set,votes})};

test('epoch transition requires governance, timelock, incoming readiness quorum, and old-set finality',()=>{const change=proposeValidatorSetChange({currentSet:set,actions:[{type:'UPDATE_VALIDATOR_POWER',validatorId:'gov-v4',votingPower:2}],activationEpoch:2,activationHeight:20,governanceProposalId:'proposal-epoch-2',governanceApproved:true}),parent=finality(),votes=authorities.slice(1).map(item=>{const body=readinessDomain({change,validatorId:item.id,checkpointCertificateHash:parent.certificateHash});return{...body,signature:sign(null,Buffer.from(canonicalize(body)),item.privateKey).toString('base64')}}),readiness=buildReadinessCertificate({change,checkpointCertificateHash:parent.certificateHash,votes});assert.throws(()=>activateValidatorEpoch({change,readinessCertificate:readiness,oldFinalityCertificate:parent,currentSet:set,currentHeight:19}),/VALIDATOR_EPOCH_ACTIVATION_DENIED/);const transition=activateValidatorEpoch({change,readinessCertificate:readiness,oldFinalityCertificate:parent,currentSet:set,currentHeight:20});assert.equal(transition.epoch,2);assert.equal(transition.validatorSet.totalVotingPower,5);const corrupt=structuredClone(readiness);corrupt.votes[0].signature='bad';assert.throws(()=>buildReadinessCertificate({change,checkpointCertificateHash:parent.certificateHash,votes:corrupt.votes}),/VALIDATOR_READINESS_VOTE_INVALID/)});

test('validator changes cannot reduce administrative fault domains below three',()=>{assert.throws(()=>proposeValidatorSetChange({currentSet:set,actions:[{type:'REMOVE_VALIDATOR',validatorId:'gov-v3'},{type:'REMOVE_VALIDATOR',validatorId:'gov-v4'},{type:'ADD_VALIDATOR',validator:{validatorId:'replacement-a',consensusPublicKey:set.validators[0].consensusPublicKey,votingPower:1,peerEndpoints:[],faultDomain:'domain-1'}},{type:'ADD_VALIDATOR',validator:{validatorId:'replacement-b',consensusPublicKey:set.validators[1].consensusPublicKey,votingPower:1,peerEndpoints:[],faultDomain:'domain-2'}}],activationEpoch:2,activationHeight:20,governanceProposalId:'bad-domains',governanceApproved:true}),/VALIDATOR_SET_FAULT_DOMAINS_INSUFFICIENT/)});
