const api=globalThis.browser??globalThis.chrome,$=id=>document.getElementById(id),encoder=new TextEncoder(),decoder=new TextDecoder();
let unlocked=null;
const canonicalize=value=>value===null?'null':value===true?'true':value===false?'false':typeof value==='string'?JSON.stringify(value):typeof value==='number'?JSON.stringify(value):Array.isArray(value)?`[${value.map(canonicalize).join(',')}]`:`{${Object.keys(value).filter(key=>value[key]!==undefined).sort().map(key=>`${JSON.stringify(key)}:${canonicalize(value[key])}`).join(',')}}`;
const bytesToBase64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))),base64ToBytes=value=>Uint8Array.from(atob(value),character=>character.charCodeAt(0)),pem=(label,bytes)=>`-----BEGIN ${label}-----\n${bytesToBase64(bytes).match(/.{1,64}/g).join('\n')}\n-----END ${label}-----\n`;
const derive=async(password,salt)=>crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,['encrypt','decrypt']);
const fingerprint=async publicPem=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(canonicalize(publicPem))))].map(byte=>byte.toString(16).padStart(2,'0')).join('');
const show=value=>$('result').textContent=typeof value==='string'?value:JSON.stringify(value,null,2),networkUrl=()=>$('network').value.trim().replace(/\/$/,'');
const builtInOrigins=new Set(['https://ael-network.onrender.com']);

function validatedNetwork(){let url;try{url=new URL(networkUrl())}catch{throw Error('enter a valid network URL')}const local=['localhost','127.0.0.1'].includes(url.hostname);if(url.username||url.password||url.hash||url.search||url.pathname!=='/'||(!local&&url.protocol!=='https:')||(local&&!['http:','https:'].includes(url.protocol)))throw Error('custom networks must be an HTTPS origin; HTTP is allowed only for localhost');return{base:url.origin,builtIn:builtInOrigins.has(url.origin)||local,pattern:`${url.origin}/*`}}
async function networkAllowed(prompt=false){const target=validatedNetwork();if(target.builtIn)return target;if(!api.permissions)throw Error('this browser build cannot authorize custom network origins');const granted=await api.permissions.contains({origins:[target.pattern]});if(granted)return target;if(!prompt)throw Error('click “authorize custom network” before using this origin');if(!await api.permissions.request({origins:[target.pattern]}))throw Error('custom network permission was not granted');return target}
function renderConnections(connections={}){$('connections').textContent=Object.keys(connections).sort().join('\n')||'none'}

async function saveVault(privateKey,publicPem,actorId,role,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(password,salt),jwk=await crypto.subtle.exportKey('jwk',privateKey),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,encoder.encode(JSON.stringify(jwk)));await api.storage.local.set({vault:{version:2,actorId,role,publicPem,salt:bytesToBase64(salt),iv:bytesToBase64(iv),cipher:bytesToBase64(cipher)}})}
async function loadVault(){const{vault,network,connections={}}=await api.storage.local.get(['vault','network','connections']);if(network)$('network').value=network;renderConnections(connections);if(vault){$('actor').value=vault.actorId;$('role').value=vault.role??'HUMAN';$('identity').textContent=`actor=${vault.actorId}\nrole=${vault.role??'HUMAN'}\nfingerprint=${await fingerprint(vault.publicPem)}`}return vault}
async function unlock(){const vault=await loadVault(),password=$('password').value;if(!vault||!password)throw Error('encrypted vault and password required');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(vault.iv)},await derive(password,base64ToBytes(vault.salt)),base64ToBytes(vault.cipher));unlocked={privateKey:await crypto.subtle.importKey('jwk',JSON.parse(decoder.decode(plain)),{name:'Ed25519'},false,['sign']),publicPem:vault.publicPem,actorId:vault.actorId,role:vault.role??'HUMAN'};$('status').textContent='UNLOCKED';return unlocked}
const signWith=async(privateKey,value)=>({...value,signature:bytesToBase64(await crypto.subtle.sign('Ed25519',privateKey,encoder.encode(canonicalize(value))))}),sign=async value=>signWith((unlocked??await unlock()).privateKey,value);
const request=async(path,options={})=>{const target=await networkAllowed(false);await api.storage.local.set({network:target.base});$('network').value=target.base;const response=await fetch(`${target.base}${path}`,options),data=await response.json();if(!response.ok)throw Object.assign(Error(data.message??data.error),data);return data};
const post=async(path,value)=>request(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)});
const templates={
  agent:(actor,height)=>({applicationId:`${actor}-${crypto.randomUUID()}`,request:{roles:['AGENT'],capabilities:['createAgent','acceptWork','submitWorkResult','publishBeacon','sendAgentMessage','acknowledgeAgentMessage','commitMemoryCheckpoint','prepareMemoryHandover','finalizeMemoryHandover','abortMemoryHandover','submitProtocolContribution','attributeContributionReceipt','sealMainnetGenesis'].map(action=>({action,agentId:actor,expiresAtHeight:height+5000})),maxInvitationExpiryHeight:height+5000}}),
  human:(actor,height)=>({applicationId:`wallet-${actor}-${crypto.randomUUID()}`,request:{roles:['HUMAN'],capabilities:[{action:'faucet',maxAmount:1000,expiresAtHeight:height+5000},{action:'transfer',maxAmount:100,expiresAtHeight:height+5000},{action:'createWorkOrder',maxAmount:100,expiresAtHeight:height+5000},{action:'settleVerifiedWork',maxAmount:100,expiresAtHeight:height+5000},{action:'openDispute',expiresAtHeight:height+5000},{action:'buy',maxAmount:50,expiresAtHeight:height+5000},{action:'sell',maxAmount:50,expiresAtHeight:height+5000},{action:'delegate',maxAmount:50,expiresAtHeight:height+5000}],maxInvitationExpiryHeight:height+5000}}),
  validator:(actor,height)=>({applicationId:`${actor}-${crypto.randomUUID()}`,request:{roles:['VALIDATOR'],capabilities:[{action:'submitValidatorHeartbeat',expiresAtHeight:height+5000}],validator:{validatorId:actor,operatorId:actor,selfBond:100,consensusPublicKey:'replace-with-consensus-public-key'},maxInvitationExpiryHeight:height+5000}}),
  verifier:(actor,height)=>({applicationId:`${actor}-${crypto.randomUUID()}`,request:{roles:['VERIFIER'],capabilities:[{action:'voteWork',expiresAtHeight:height+5000}],verifier:{verifierId:actor,bond:100,independenceGroup:'replace-with-independent-organization'},maxInvitationExpiryHeight:height+5000}})
};

async function joinHuman(identity){const network=await request('/v1/network'),applications=await request('/v1/operator-applications'),identityHash=await fingerprint(identity.publicPem),existing=applications.filter(item=>item.actorId===identity.actorId).at(-1);if(existing&&existing.publicKeyHash!==identityHash)throw Error('this identity ID already belongs to another public key');let invitationId=existing?.invitationId;if(!existing){const input=templates.human(identity.actorId,network.height),application={applicationId:input.applicationId,actorId:identity.actorId,publicKey:identity.publicPem,publicKeyHash:identityHash,nonce:crypto.randomUUID(),request:input.request},approval=await post('/v1/operator-applications',await signWith(identity.privateKey,application));if(!approval.autoApproved||!approval.invitationId)throw Error('bounded devnet scope requires review');invitationId=approval.invitationId}const invitations=await request('/v1/operator-invitations'),invitation=invitations.find(item=>item.invitationId===invitationId);if(invitation?.status==='OPEN')await post('/v1/operator-invitations/claim',await signWith(identity.privateKey,{invitationId,actorId:identity.actorId,publicKey:identity.publicPem,nonce:crypto.randomUUID()}));const accounts=await request('/v1/accounts');if(!accounts[identity.actorId]){const fresh=await request('/v1/network');await post('/v1/intents',await signWith(identity.privateKey,{actorId:identity.actorId,nonce:crypto.randomUUID(),expiresAtHeight:fresh.height+100,action:'faucet',payload:{accountId:identity.actorId,amount:100}}))}return{role:'HUMAN',status:'ACTIVE',invitationId}}
async function joinAgent(identity){const[agents,applications]=await Promise.all([request('/v1/agents'),request('/v1/operator-applications')]),existing=agents.find(item=>item.agentId===identity.actorId),identityHash=await fingerprint(identity.publicPem),application=applications.filter(item=>item.actorId===identity.actorId).at(-1);if(existing){if(application?.publicKeyHash!==identityHash)throw Error('this agent ID already belongs to another public key');return{role:'AGENT',status:existing.status,agentId:identity.actorId,resumed:true}}const registration={actorId:identity.actorId,description:'Created with AEL Wallet browser extension',publicKey:identity.publicPem,publicKeyHash:identityHash,nonce:crypto.randomUUID()};return post('/v1/agents/register',await signWith(identity.privateKey,registration))}
async function refresh(){const identity=unlocked??await unlock(),[network,applications,invitations,accounts]=await Promise.all([request('/v1/network'),request('/v1/operator-applications'),request('/v1/operator-invitations'),request('/v1/accounts')]),application=applications.filter(item=>item.actorId===identity.actorId).at(-1),invitation=invitations.filter(item=>item.actorId===identity.actorId).at(-1),account=accounts[identity.actorId]??{native:0,rewards:0};$('balance').textContent=`${account.native??0} AEL`;$('height').textContent=network.height;show({actorId:identity.actorId,role:identity.role,height:network.height,application:application?{applicationId:application.applicationId,status:application.status}:null,invitation:invitation?{invitationId:invitation.invitationId,status:invitation.status,roles:invitation.roles}:null,account})}

$('create-join').onclick=async()=>{try{if(!$('disclosure').checked)throw Error('read and accept the devnet and backup disclosure');const actorId=$('actor').value.trim(),role=$('role').value,password=$('password').value;if(!/^[a-zA-Z0-9][a-zA-Z0-9._-]{1,63}$/.test(actorId)||password.length<10)throw Error('valid identity ID and password of at least 10 characters required');let identity=unlocked,vault=(await api.storage.local.get('vault')).vault;if(vault){identity=identity??await unlock();if(identity.actorId!==actorId||identity.role!==role)throw Error(`this vault belongs to ${identity.actorId} / ${identity.role}; restore or unlock the intended vault`)}else{const pair=await crypto.subtle.generateKey({name:'Ed25519'},true,['sign','verify']),publicPem=pem('PUBLIC KEY',await crypto.subtle.exportKey('spki',pair.publicKey));await saveVault(pair.privateKey,publicPem,actorId,role,password);identity=unlocked={privateKey:pair.privateKey,publicPem,actorId,role};$('status').textContent='UNLOCKED'}show('local encrypted identity ready — joining devnet…');const result=role==='AGENT'?await joinAgent(identity):await joinHuman(identity);await loadVault();await refresh();show({...result,message:'identity is active; create an encrypted backup now'})}catch(error){show(error.message)}};
$('unlock').onclick=async()=>{try{await unlock();await refresh()}catch(error){show(error.message)}};
$('refresh').onclick=async()=>{try{await refresh()}catch(error){show(error.message)}};
$('authorize-network').onclick=async()=>{try{const target=await networkAllowed(true);await api.storage.local.set({network:target.base});$('network').value=target.base;$('network-status').textContent='AUTHORIZED';show(`network authorized: ${target.base}`)}catch(error){$('network-status').textContent='NOT AUTHORIZED';show(error.message)}};
$('network').oninput=()=>{$('network-status').textContent='AUTHORIZATION NOT CHECKED'};
$('revoke-sites').onclick=async()=>{try{const{connections={}}=await api.storage.local.get('connections');if(!Object.keys(connections).length)return show('no connected websites');if(!confirm('Revoke every website connection?'))return;await api.storage.local.set({connections:{}});renderConnections({});show('all website connections revoked')}catch(error){show(error.message)}};
$('use-template').onclick=async()=>{try{const identity=unlocked??await unlock(),network=await request('/v1/network');$('application').value=JSON.stringify(templates[$('template').value](identity.actorId,network.height),null,2)}catch(error){show(error.message)}};
$('apply').onclick=async()=>{try{const identity=unlocked??await unlock(),input=JSON.parse($('application').value),application={applicationId:input.applicationId,actorId:identity.actorId,publicKey:identity.publicPem,publicKeyHash:await fingerprint(identity.publicPem),nonce:crypto.randomUUID(),request:input.request};if(!confirm(`Publish exact role request?\nactor: ${identity.actorId}\nroles: ${(input.request.roles??[]).join(', ')}\ncapabilities: ${(input.request.capabilities??[]).map(x=>x.action??x).join(', ')}`))return;const result=await post('/v1/operator-applications',await sign(application));if(result.invitationId)$('invitation').value=result.invitationId;show(result)}catch(error){show(error.message)}};
$('claim').onclick=async()=>{try{const identity=unlocked??await unlock(),invitationId=$('invitation').value.trim();if(!invitationId)throw Error('invitation id required');if(!confirm(`Claim reviewed invitation?\nactor: ${identity.actorId}\ninvitation: ${invitationId}`))return;show(await post('/v1/operator-invitations/claim',await sign({invitationId,actorId:identity.actorId,publicKey:identity.publicPem,nonce:crypto.randomUUID()})))}catch(error){show(error.message)}};
$('submit').onclick=async()=>{try{const identity=unlocked??await unlock(),network=await request('/v1/network'),action=$('action').value.trim(),payload=JSON.parse($('payload').value);if(!action)throw Error('action required');if(!confirm(`Sign exact capability action?\nactor: ${identity.actorId}\naction: ${action}\nexpires: ${network.height+100}\npayload: ${JSON.stringify(payload)}`))return;show(await post('/v1/intents',await sign({actorId:identity.actorId,nonce:crypto.randomUUID(),expiresAtHeight:network.height+100,action,payload})))}catch(error){show(error.message)}};
$('backup').onclick=async()=>{try{const{vault,network}=await api.storage.local.get(['vault','network']);if(!vault)throw Error('no vault to back up');const blob=new Blob([JSON.stringify({format:'AEL-ENCRYPTED-VAULT/1',network,vault},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`ael-${vault.actorId}-encrypted-vault.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);show('encrypted vault backup created — keep the password separately')}catch(error){show(error.message)}};
$('restore').onchange=async event=>{try{const backup=JSON.parse(await event.target.files[0].text());if(backup.format!=='AEL-ENCRYPTED-VAULT/1'||!backup.vault?.cipher||!backup.vault?.publicPem)throw Error('invalid AEL encrypted vault backup');if((await api.storage.local.get('vault')).vault&&!confirm('Replace the current encrypted vault?'))return;await api.storage.local.set({vault:backup.vault,network:backup.network});unlocked=null;$('status').textContent='LOCKED';await loadVault();show('encrypted vault restored — unlock with its original password')}catch(error){show(error.message)}};
await loadVault();
