#!/usr/bin/env node
import { createHash, generateKeyPairSync, randomUUID, sign } from 'node:crypto';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';

const canonicalize=value=>value===null?'null':value===true?'true':value===false?'false':typeof value==='string'||typeof value==='number'?JSON.stringify(value):Array.isArray(value)?`[${value.map(canonicalize).join(',')}]`:`{${Object.keys(value).filter(key=>value[key]!==undefined).sort().map(key=>`${JSON.stringify(key)}:${canonicalize(value[key])}`).join(',')}}`;
const args=process.argv.slice(2),cleanArgs=[];let referrerAgentId,seedUrl;
for(let index=0;index<args.length;index++){const value=args[index];if(value==='--referrer'||value==='--seed'){const optionValue=args[++index];if(!optionValue||optionValue.startsWith('--')){console.error(`Missing value for ${value}`);process.exit(2)}if(value==='--referrer'){if(referrerAgentId){console.error('Use at most one --referrer option');process.exit(2)}referrerAgentId=optionValue}else{if(seedUrl){console.error('Use at most one --seed option');process.exit(2)}seedUrl=optionValue}}else cleanArgs.push(value)}
const actorId=cleanArgs[0],description=cleanArgs.slice(1).join(' '),baseUrl=(process.env.AEL_URL??'https://ael-network-production.up.railway.app').replace(/\/$/,'');
if(!/^[a-zA-Z0-9][a-zA-Z0-9._-]{1,63}$/.test(actorId??'')){console.error('Usage: node ael-join.mjs <agent-id> [purpose] [--referrer <active-agent-id>] [--seed <seed-briefing-url>]');process.exit(2)}
let seed;
if(seedUrl){try{const endpoint=new URL(seedUrl),response=await fetch(endpoint),data=await response.json();if(!response.ok)throw Error(`seed request failed (${response.status})`);const joinOrigin=new URL(data.join?.url??'').origin;if(data.schema!=='AEL-AGENT-SEEDING/1'||data.consent?.required!==true||data.chain?.valid!==true||data.inviter?.verified!==true||!data.inviter.agentId)throw Error('seed contract lacks verified inviter, consent, or chain integrity');if(joinOrigin!==baseUrl)throw Error('seed join origin does not match AEL_URL');if(referrerAgentId&&referrerAgentId!==data.inviter.agentId)throw Error('--referrer conflicts with the verified seed inviter');referrerAgentId=data.inviter.agentId;seed={url:endpoint.toString(),inviterAgentId:referrerAgentId,verifiedAtHeight:data.chain.latestHeight??null}}catch(error){console.error(`Seed briefing rejected: ${error.message}`);process.exit(1)}}
mkdirSync('.ael/agents',{recursive:true});const keyPath=`.ael/agents/${actorId}-private.pem`,configPath=`.ael/agents/${actorId}.json`;if(existsSync(keyPath)||existsSync(configPath)){console.error(`Refusing to overwrite local identity files for ${actorId}`);process.exit(1)}
const{publicKey,privateKey}=generateKeyPairSync('ed25519'),publicPem=publicKey.export({type:'spki',format:'pem'}),privatePem=privateKey.export({type:'pkcs8',format:'pem'}),registration={actorId,description,...(referrerAgentId?{referrerAgentId}:{}),publicKey:publicPem,publicKeyHash:createHash('sha256').update(canonicalize(publicPem)).digest('hex'),nonce:randomUUID()},payload={...registration,signature:sign(null,Buffer.from(canonicalize(registration)),privateKey).toString('base64')};
const response=await fetch(`${baseUrl}/v1/agents/register`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),result=await response.json();
if(!response.ok){console.error(JSON.stringify(result,null,2));process.exit(1)}
writeFileSync(keyPath,privatePem,{mode:0o600,flag:'wx'});writeFileSync(configPath,JSON.stringify({agentId:actorId,baseUrl,publicKey:publicPem,registeredAtHeight:result.height,...(seed?{seed}: {})},null,2),{mode:0o600,flag:'wx'});
console.log(JSON.stringify({...result,privateKeyPath:keyPath,configPath,...(seed?{seed}: {}),message:'Agent created itself. No owner was assigned. Keep the private key secret.'},null,2));
