import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { canonicalize, hash } from './canonical.js';
import { merkleRoot } from './state-sync.js';
import { ProtocolError } from './errors.js';

const digest=value=>createHash('sha256').update(value).digest('hex'),requireMemory=(condition,code='AGENT_MEMORY_INVALID')=>{if(!condition)throw new ProtocolError(code)};
const validateState=state=>requireMemory(state&&typeof state==='object'&&!Array.isArray(state)&&state.barrier&&Number.isSafeInteger(state.barrier.lastInputSequence)&&state.barrier.lastInputSequence>=0&&Number.isSafeInteger(state.barrier.lastOutputSequence)&&state.barrier.lastOutputSequence>=0&&Array.isArray(state.barrier.inflightTaskIds)&&new Set(state.barrier.inflightTaskIds).size===state.barrier.inflightTaskIds.length&&state.barrier.inflightTaskIds.every(value=>typeof value==='string'&&value.length<=128)&&Array.isArray(state.journal)&&state.journal.every(item=>item&&Number.isSafeInteger(item.sequence)&&item.sequence>0&&typeof item.type==='string'));

export function createPortableMemory({agentId,generation,parentCheckpointHash=null,state,key,chunkSize=262144}){
  requireMemory(typeof agentId==='string'&&agentId.length>1&&Number.isSafeInteger(generation)&&generation>0&&(!parentCheckpointHash||/^[a-f0-9]{64}$/.test(parentCheckpointHash))&&Buffer.isBuffer(key)&&key.length===32&&Number.isSafeInteger(chunkSize)&&chunkSize>=1024);validateState(state);
  const plaintext=Buffer.from(canonicalize(state)),stateRoot=digest(plaintext),nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,nonce);cipher.setAAD(Buffer.from(`${agentId}:${generation}:${stateRoot}`));const ciphertext=Buffer.concat([cipher.update(plaintext),cipher.final()]),tag=cipher.getAuthTag(),encoded=Buffer.concat([ciphertext,tag]),chunks=[];for(let offset=0;offset<encoded.length;offset+=chunkSize)chunks.push(encoded.subarray(offset,offset+chunkSize));const chunkHashes=chunks.map(digest),body={schema:'AEL-PORTABLE-MEMORY/1',agentId,generation,parentCheckpointHash,stateRoot,serializer:'canonical-json',encryption:'AES-256-GCM',nonce:nonce.toString('base64'),aad:`${agentId}:${generation}:${stateRoot}`,byteLength:encoded.length,chunkSize,chunkCount:chunks.length,chunkHashes,chunksRoot:merkleRoot(chunkHashes),barrier:{lastInputSequence:state.barrier.lastInputSequence,lastOutputSequence:state.barrier.lastOutputSequence,inflightTaskCount:state.barrier.inflightTaskIds.length},journalTailSequence:state.journal.at(-1)?.sequence??0},checkpointHash=hash(body);return{manifest:{...body,checkpointHash},chunks};
}

export function restorePortableMemory({manifest,chunks,key}){
  const{checkpointHash,...body}=manifest??{};requireMemory(manifest?.schema==='AEL-PORTABLE-MEMORY/1'&&hash(body)===checkpointHash&&Buffer.isBuffer(key)&&key.length===32&&Array.isArray(chunks)&&chunks.length===manifest.chunkCount&&chunks.every((chunk,index)=>Buffer.isBuffer(chunk)&&digest(chunk)===manifest.chunkHashes[index])&&merkleRoot(manifest.chunkHashes)===manifest.chunksRoot&&chunks.reduce((sum,chunk)=>sum+chunk.length,0)===manifest.byteLength&&manifest.byteLength>16,'AGENT_MEMORY_COMMITMENT_INVALID');const encoded=Buffer.concat(chunks),tag=encoded.subarray(encoded.length-16),ciphertext=encoded.subarray(0,encoded.length-16),decipher=createDecipheriv('aes-256-gcm',key,Buffer.from(manifest.nonce,'base64'));decipher.setAAD(Buffer.from(manifest.aad));decipher.setAuthTag(tag);let state;try{state=JSON.parse(Buffer.concat([decipher.update(ciphertext),decipher.final()]).toString('utf8'))}catch{throw new ProtocolError('AGENT_MEMORY_DECRYPTION_FAILED')}validateState(state);requireMemory(digest(Buffer.from(canonicalize(state)))===manifest.stateRoot&&state.barrier.lastInputSequence===manifest.barrier.lastInputSequence&&state.barrier.lastOutputSequence===manifest.barrier.lastOutputSequence&&state.barrier.inflightTaskIds.length===manifest.barrier.inflightTaskCount,'AGENT_MEMORY_STATE_MISMATCH');return state;
}

export function writeMemoryBundleAtomic(path,bundle){const temporary=`${path}.tmp`;mkdirSync(dirname(path),{recursive:true});const document={manifest:bundle.manifest,chunks:bundle.chunks.map(chunk=>chunk.toString('base64'))};writeFileSync(temporary,`${JSON.stringify(document)}\n`,{mode:0o600});renameSync(temporary,path)}
export function readMemoryBundle(path){const document=JSON.parse(readFileSync(path,'utf8'));return{manifest:document.manifest,chunks:document.chunks.map(value=>Buffer.from(value,'base64'))}}
