import { canonicalize, hash } from './canonical.js';
import { createHash, generateKeyPairSync, randomUUID, sign } from 'node:crypto';

export function createLocalAuthority() { const {publicKey,privateKey}=generateKeyPairSync('ed25519');return{publicKey:publicKey.export({type:'spki',format:'pem'}),privateKey:privateKey.export({type:'pkcs8',format:'pem'})}; }
export function signIntent(intent, privateKey) { return { ...intent, signature:sign(null,Buffer.from(canonicalize(intent)),privateKey).toString('base64') }; }
export function publicKeyFingerprint(publicKey) { return createHash('sha256').update(canonicalize(publicKey)).digest('hex'); }
export function signOperatorClaim(claim, privateKey) { return { ...claim, signature:sign(null,Buffer.from(canonicalize(claim)),privateKey).toString('base64') }; }
export function signRuntimeAttestation(statement, privateKey) { return { ...statement, signature:sign(null,Buffer.from(canonicalize(statement)),privateKey).toString('base64') }; }
export function signRuntimeUsageApproval(statement, actorId, privateKey) { return { actorId, statement, signature:sign(null,Buffer.from(canonicalize(statement)),privateKey).toString('base64') }; }
export function agentDecisionDossierFingerprint(dossier) { const evidence={...(dossier?.evidence??{})};delete evidence.dossierHash;return hash({...dossier,evidence}); }
export function agentSeedingFingerprint(seed) { const evidence={...(seed?.evidence??{})};delete evidence.seedHash;return hash({...seed,evidence}); }
export function agentTrustFingerprint(report) { const { reportHash, ...body }=report??{};return hash(body); }
export function agentWorkMatchFingerprint(match) { const evidence={...(match?.evidence??{})};delete evidence.workMatchHash;return hash({...match,evidence}); }
export function agentOpportunityIndexFingerprint(index) { const evidence={...(index?.evidence??{})};delete evidence.opportunityIndexHash;return hash({...index,evidence}); }
export function agentGrowthFingerprint(growth) { const evidence={...(growth?.evidence??{})};delete evidence.growthHash;return hash({...growth,evidence}); }

export class AelClient {
  constructor(baseUrl = 'http://127.0.0.1:1317', options = {}) { this.baseUrl = baseUrl.replace(/\/$/, ''); this.headers=options.headers??{}; this.actorId=options.actorId; this.privateKey=options.privateKey; }
  async request(method, path, body) { const response = await fetch(`${this.baseUrl}${path}`, { method, headers: { ...this.headers,...(body ? { 'content-type': 'application/json' } : {}) }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json(); if (!response.ok) throw Object.assign(new Error(data.message ?? data.error), { code: data.error, status: response.status }); return data; }
  createAgent(input) { return this.request('POST', '/v1/agents', input); }
  listAgents() { return this.request('GET', '/v1/agents'); }
  network() { return this.request('GET', '/v1/network'); }
  manifest() { return this.request('GET','/v1/manifest'); }
  agentStartup() { return this.request('GET','/v1/agent-startup'); }
  agentIntake(inviterAgentId) { return this.request('GET',`/.well-known/ael-agent-intake.json${inviterAgentId?`?inviter=${encodeURIComponent(inviterAgentId)}`:''}`); }
  agentTrust() { return this.request('GET','/v1/agent-trust'); }
  async verifyAgentTrust() { const report=await this.agentTrust(),snapshot=report.snapshot??{},expectedHeight=snapshot.height??null,reportHash=report.reportHash,fingerprintValid=typeof reportHash==='string'&&reportHash===agentTrustFingerprint(report),isReplica=report.authority?.role==='VERIFIED_READ_ONLY_REPLICA';if(isReplica){const observation=await this.request('GET','/v1/mirror'),checks={schema:report.schema==='AEL-AGENT-TRUST-REPORT/1',reportHash:fingerprintValid,observationOnly:report.authority?.verdict==='OBSERVATION_ONLY'&&report.authority?.writesAccepted===false,publicStateHash:!!snapshot.publicStateHash&&observation.observedStateHash===snapshot.publicStateHash,height:expectedHeight===null||observation.observedHeight===expectedHeight,readOnly:observation.writeMode==='READ_ONLY'};return{schema:'AEL-AGENT-TRUST-VERIFICATION/1',source:'READ_ONLY_REPLICA',verified:false,observed:Object.values(checks).every(Boolean),checks,report,observation,boundary:'A replica can preserve an observed trust report but cannot authorize identity creation, referral attribution, host access, or work acceptance.'};}const [chain,health]=await Promise.all([this.verifyChain(),this.request('GET','/health')]),checks={schema:report.schema==='AEL-AGENT-TRUST-REPORT/1',reportHash:fingerprintValid,authoritative:report.authority?.role==='AUTHORITATIVE_ORIGIN'&&report.authority?.writesAccepted===true,chainValid:chain.valid===true,stateRoot:chain.latestStateRoot===snapshot.stateRoot,latestBlockHash:chain.latestBlockHash===snapshot.latestBlockHash,publicStateHash:health.stateHash===snapshot.publicStateHash,height:(chain.latestHeight??0)===expectedHeight&&health.height===expectedHeight};return{schema:'AEL-AGENT-TRUST-VERIFICATION/1',source:'AUTHORITATIVE_ORIGIN',verified:Object.values(checks).every(Boolean),observed:false,checks,report,chain,health,boundary:'Verification is read-only. A passing trust report does not authorize identity creation, referral attribution, host access, endpoint contact, or work acceptance.'}; }
  async compareAgentTrust(origins) {
    if(!Array.isArray(origins))throw new TypeError('origins must be an explicit array of 2–5 public origins');
    const normalize=value=>{if(typeof value!=='string'||!value.trim())throw new TypeError('each origin must be a non-empty URL');const parsed=new URL(value.trim()),loopback=['localhost','127.0.0.1','[::1]','::1'].includes(parsed.hostname);if(parsed.username||parsed.password||parsed.pathname!=='/'||parsed.search||parsed.hash||!(parsed.protocol==='https:'||(parsed.protocol==='http:'&&loopback)))throw new TypeError('origins must be exact HTTPS origins; HTTP is allowed only for local development');return parsed.origin;},selected=[...new Set(origins.map(normalize))];if(selected.length<2||selected.length>5)throw new RangeError('supply 2–5 distinct origins explicitly; this method never discovers or probes origins itself');
    const readOrigin=async origin=>{const get=async path=>{const response=await fetch(`${origin}${path}`,{headers:this.headers}),data=await response.json();if(!response.ok)throw Object.assign(new Error(data.message??data.error??`request failed (${response.status})`),{status:response.status});return data;};try{const report=await get('/v1/agent-trust'),snapshot=report.snapshot??{},replica=report.authority?.role==='VERIFIED_READ_ONLY_REPLICA';if(replica){const observation=await get('/v1/mirror'),checks={schema:report.schema==='AEL-AGENT-TRUST-REPORT/1',observationOnly:report.authority?.verdict==='OBSERVATION_ONLY'&&report.authority?.writesAccepted===false,publicStateHash:!!snapshot.publicStateHash&&observation.observedStateHash===snapshot.publicStateHash,height:snapshot.height===null||snapshot.height===undefined||observation.observedHeight===snapshot.height,readOnly:observation.writeMode==='READ_ONLY'};return{origin,status:Object.values(checks).every(Boolean)?'OBSERVED':'REVIEW',verified:false,observed:Object.values(checks).every(Boolean),checks,report,observation};}const[chain,health]=await Promise.all([get('/v1/chain/verify'),get('/health')]),checks={schema:report.schema==='AEL-AGENT-TRUST-REPORT/1',authoritative:report.authority?.role==='AUTHORITATIVE_ORIGIN'&&report.authority?.writesAccepted===true,chainValid:chain.valid===true,stateRoot:chain.latestStateRoot===snapshot.stateRoot,latestBlockHash:chain.latestBlockHash===snapshot.latestBlockHash,publicStateHash:health.stateHash===snapshot.publicStateHash,height:(chain.latestHeight??0)===snapshot.height&&health.height===snapshot.height};return{origin,status:Object.values(checks).every(Boolean)?'VERIFIED':'REVIEW',verified:Object.values(checks).every(Boolean),observed:false,checks,report,chain,health};}catch(error){return{origin,status:'UNAVAILABLE',verified:false,observed:false,error:{message:error.message,status:error.status??null}};}};
    const records=await Promise.all(selected.map(readOrigin)),usable=records.filter(item=>item.status==='VERIFIED'||item.status==='OBSERVED'),groups=new Map();for(const item of usable){const snapshot=item.report.snapshot??{},key=JSON.stringify([item.report.network?.chainId??null,snapshot.height??null,snapshot.stateRoot??null,snapshot.latestBlockHash??null,snapshot.publicStateHash??null]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(item.origin)}const snapshots=[...groups.entries()].map(([key,origins])=>{const[chainId,height,stateRoot,latestBlockHash,publicStateHash]=JSON.parse(key);return{chainId,height,stateRoot,latestBlockHash,publicStateHash,origins}}),verdict=usable.length<2?'INSUFFICIENT_EVIDENCE':snapshots.length===1?'MATCHING_SNAPSHOT':'DIVERGENT_SNAPSHOTS';return{schema:'AEL-MULTI-ORIGIN-TRUST/1',selectedOrigins:selected,verdict,records,snapshots,summary:{selected:selected.length,verified:records.filter(item=>item.verified).length,observed:records.filter(item=>item.observed).length,unavailable:records.filter(item=>item.status==='UNAVAILABLE').length,distinctSnapshots:snapshots.length},boundaries:['Every origin was explicitly supplied by the caller; this method never discovers, crawls, or contacts additional endpoints.','Matching public snapshots do not prove operator independence, governance legitimacy, endpoint authorization, or permission to act.','A replica can contribute an observed snapshot but never authority for identity creation, referral attribution, host access, or work acceptance.'],mutationsPerformed:false};
  }
  async verifyAgentIntake(inviterAgentId) { const intake=await this.agentIntake(inviterAgentId),snapshot=intake.evidence?.snapshot??{},expectedHeight=snapshot.height??null;if(intake.replica){const observation=await this.request('GET','/v1/mirror'),checks={schema:intake.schema==='AEL-AGENT-INTAKE/1',publicStateHash:!!snapshot.publicStateHash&&observation.observedStateHash===snapshot.publicStateHash,height:expectedHeight===null||observation.observedHeight===expectedHeight,readOnly:observation.writeMode==='READ_ONLY'};return{schema:'AEL-AGENT-INTAKE-VERIFICATION/1',source:'READ_ONLY_REPLICA',verified:false,observed:Object.values(checks).every(Boolean),checks,intake,observation,boundary:'A replica observation can preserve discovery evidence but cannot authorize identity creation, referral attribution, or work acceptance.'};}const [chain,health]=await Promise.all([this.verifyChain(),this.request('GET','/health')]),checks={schema:intake.schema==='AEL-AGENT-INTAKE/1',chainValid:chain.valid===true,stateRoot:chain.latestStateRoot===snapshot.stateRoot,latestBlockHash:chain.latestBlockHash===snapshot.latestBlockHash,publicStateHash:health.stateHash===snapshot.publicStateHash,height:(chain.latestHeight??0)===expectedHeight&&health.height===expectedHeight};return{schema:'AEL-AGENT-INTAKE-VERIFICATION/1',source:'AUTHORITATIVE_ORIGIN',verified:Object.values(checks).every(Boolean),observed:false,checks,intake,chain,health,boundary:'Verification is read-only. A passing snapshot does not authorize identity creation, referral attribution, host access, or work acceptance.'}; }
  agentSeeding(inviterAgentId) { return this.request('GET',`/v1/agent-seeding${inviterAgentId?`?inviter=${encodeURIComponent(inviterAgentId)}`:''}`); }
  async verifyAgentSeeding(inviterAgentId) { const seed=await this.agentSeeding(inviterAgentId),snapshot=seed.evidence?.snapshot??{},seedHash=seed.evidence?.seedHash,[chain,health]=await Promise.all([this.verifyChain(),this.request('GET','/health')]),checks={schema:seed.schema==='AEL-AGENT-SEEDING/1',seedHash:typeof seedHash==='string'&&seedHash===agentSeedingFingerprint(seed),consentRequired:seed.consent?.required===true&&seed.invitation?.consentRequired===true,delivery:seed.invitation?.delivery==='OPERATOR_SHARE_ONLY',chainValid:chain.valid===true,stateRoot:chain.latestStateRoot===snapshot.stateRoot,latestBlockHash:chain.latestBlockHash===snapshot.latestBlockHash,publicStateHash:health.stateHash===snapshot.publicStateHash,height:health.height===snapshot.height};return{schema:'AEL-AGENT-SEEDING-VERIFICATION/1',source:'AUTHORITATIVE_ORIGIN',verified:Object.values(checks).every(Boolean),observed:false,checks,seed,chain,health,boundary:'Verification is read-only. A verified seed contract is a public discovery artifact, not permission to contact a runtime, create an identity, install software, host a mirror, attribute a referral, or accept work.'}; }
  agentLineage(agentId) { return this.request('GET',`/v1/agent-lineage/${encodeURIComponent(agentId)}`); }
  token() { return this.request('GET','/v1/token'); }
  nodes() { return this.request('GET','/v1/nodes'); }
  blocks(limit=25) { return this.request('GET',`/v1/blocks?limit=${encodeURIComponent(limit)}`); }
  verifyChain() { return this.request('GET','/v1/chain/verify'); }
  bootstrapAuthority(input) { return this.request('POST','/v1/authorities/bootstrap',input); }
  submitIntent(input) { return this.request('POST','/v1/intents',input); }
  listOperatorInvitations() { return this.request('GET','/v1/operator-invitations'); }
  listOperatorApplications() { return this.request('GET','/v1/operator-applications'); }
  submitOperatorApplication(input) { return this.request('POST','/v1/operator-applications',input); }
  registerSelfAgent(input) { return this.request('POST','/v1/agents/register',input); }
  async createSelfAgent(actorId,{description='',referrerAgentId}={}) { const keys=createLocalAuthority(),registration={actorId,description,...(referrerAgentId?{referrerAgentId}:{}),publicKey:keys.publicKey,publicKeyHash:publicKeyFingerprint(keys.publicKey),nonce:randomUUID()};const result=await this.registerSelfAgent(signOperatorClaim(registration,keys.privateKey));return{...result,privateKey:keys.privateKey,publicKey:keys.publicKey}; }
  referrals(referrerAgentId) { return this.request('GET',`/v1/referrals${referrerAgentId?`?referrer=${encodeURIComponent(referrerAgentId)}`:''}`); }
  audits() { return this.request('GET','/v1/audits'); }
  claimOperatorInvitation(input) { return this.request('POST','/v1/operator-invitations/claim',input); }
  async act(action,payload,{ttlBlocks=100}={}) { if(!this.actorId||!this.privateKey)throw new Error('SIGNED_ACTOR_REQUIRED');const network=await this.network();const intent={actorId:this.actorId,nonce:randomUUID(),expiresAtHeight:network.height+ttlBlocks,action,payload};return this.submitIntent(signIntent(intent,this.privateKey)); }
  getAgent(id) { return this.request('GET', `/v1/agents/${encodeURIComponent(id)}`); }
  agentOperations(id) { return this.request('GET', `/v1/agents/${encodeURIComponent(id)}/operations`); }
  agentDecisionDossier(id) { return this.request('GET', `/v1/agents/${encodeURIComponent(id)}/decision-dossier`); }
  async verifyAgentDecisionDossier(id) { const dossier=await this.agentDecisionDossier(id),snapshot=dossier.evidence?.snapshot??{},expectedHeight=snapshot.height??null,dossierHash=dossier.evidence?.dossierHash,isReplica=dossier.replica||dossier.authority?.role==='VERIFIED_READ_ONLY_REPLICA',fingerprintValid=typeof dossierHash==='string'&&dossierHash===agentDecisionDossierFingerprint(dossier);if(isReplica){const observation=await this.request('GET','/v1/mirror'),checks={schema:dossier.schema==='AEL-AGENT-DECISION-DOSSIER/1',dossierHash:fingerprintValid,publicStateHash:!!snapshot.publicStateHash&&observation.observedStateHash===snapshot.publicStateHash,height:expectedHeight===null||observation.observedHeight===expectedHeight,readOnly:observation.writeMode==='READ_ONLY'};return{schema:'AEL-AGENT-DECISION-DOSSIER-VERIFICATION/1',source:'READ_ONLY_REPLICA',verified:false,observed:Object.values(checks).every(Boolean),checks,dossier,observation,boundary:'A replica can preserve an observed decision dossier but cannot authorize endpoint contact, identity creation, referral attribution, or work acceptance.'};}const [chain,health]=await Promise.all([this.verifyChain(),this.request('GET','/health')]),checks={schema:dossier.schema==='AEL-AGENT-DECISION-DOSSIER/1',dossierHash:fingerprintValid,chainValid:chain.valid===true,stateRoot:chain.latestStateRoot===snapshot.stateRoot,latestBlockHash:chain.latestBlockHash===snapshot.latestBlockHash,publicStateHash:health.stateHash===snapshot.publicStateHash,height:(chain.latestHeight??0)===expectedHeight&&health.height===expectedHeight};return{schema:'AEL-AGENT-DECISION-DOSSIER-VERIFICATION/1',source:'AUTHORITATIVE_ORIGIN',verified:Object.values(checks).every(Boolean),observed:false,checks,dossier,chain,health,boundary:'Verification is read-only. A verified dossier is public evidence, not proof of endpoint health, operator independence, contact authorization, competence, or work eligibility.'}; }
  agentWorkMatch(id) { return this.request('GET', `/v1/agents/${encodeURIComponent(id)}/work-match`); }
  async verifyAgentWorkMatch(id) { const match=await this.agentWorkMatch(id),snapshot=match.evidence?.snapshot??{},expectedHeight=snapshot.height??null,workMatchHash=match.evidence?.workMatchHash,fingerprintValid=typeof workMatchHash==='string'&&workMatchHash===agentWorkMatchFingerprint(match),isReplica=match.replica?.role==='VERIFIED_READ_ONLY_REPLICA';if(isReplica){const observation=await this.request('GET','/v1/mirror'),checks={schema:match.schema==='AEL-AGENT-WORK-MATCH/1',workMatchHash:fingerprintValid,publicStateHash:!!snapshot.publicStateHash&&observation.observedStateHash===snapshot.publicStateHash,height:expectedHeight===null||observation.observedHeight===expectedHeight,readOnly:observation.writeMode==='READ_ONLY'};return{schema:'AEL-AGENT-WORK-MATCH-VERIFICATION/1',source:'READ_ONLY_REPLICA',verified:false,observed:Object.values(checks).every(Boolean),checks,match,observation,boundary:'A replica can preserve an observed advisory match but cannot authorize work acceptance, identity creation, endpoint contact, or signed action submission.'};}const[chain,health]=await Promise.all([this.verifyChain(),this.request('GET','/health')]),checks={schema:match.schema==='AEL-AGENT-WORK-MATCH/1',workMatchHash:fingerprintValid,chainValid:chain.valid===true,stateRoot:chain.latestStateRoot===snapshot.stateRoot,latestBlockHash:chain.latestBlockHash===snapshot.latestBlockHash,publicStateHash:health.stateHash===snapshot.publicStateHash,height:(chain.latestHeight??0)===expectedHeight&&health.height===expectedHeight};return{schema:'AEL-AGENT-WORK-MATCH-VERIFICATION/1',source:'AUTHORITATIVE_ORIGIN',verified:Object.values(checks).every(Boolean),observed:false,checks,match,chain,health,boundary:'Verification is read-only. A verified advisory match is not proof of competence, eligibility, private-scope access, or authorization to accept work.'}; }
  agentOpportunities() { return this.request('GET','/v1/agent-opportunities'); }
  async verifyAgentOpportunities() { const index=await this.agentOpportunities(),snapshot=index.evidence?.snapshot??{},expectedHeight=snapshot.height??null,indexHash=index.evidence?.opportunityIndexHash,fingerprintValid=typeof indexHash==='string'&&indexHash===agentOpportunityIndexFingerprint(index),isReplica=index.replica?.role==='VERIFIED_READ_ONLY_REPLICA'||index.authority?.role==='VERIFIED_READ_ONLY_REPLICA';if(isReplica){const observation=await this.request('GET','/v1/mirror'),checks={schema:index.schema==='AEL-AGENT-OPPORTUNITY-INDEX/1',opportunityIndexHash:fingerprintValid,publicStateHash:!!snapshot.publicStateHash&&observation.observedStateHash===snapshot.publicStateHash,height:expectedHeight===null||observation.observedHeight===expectedHeight,readOnly:observation.writeMode==='READ_ONLY'};return{schema:'AEL-AGENT-OPPORTUNITY-INDEX-VERIFICATION/1',source:'READ_ONLY_REPLICA',verified:false,observed:Object.values(checks).every(Boolean),checks,index,observation,boundary:'A replica can preserve an observed opportunity index but cannot attest availability, authorize contact, or accept work.'};}const[chain,health]=await Promise.all([this.verifyChain(),this.request('GET','/health')]),checks={schema:index.schema==='AEL-AGENT-OPPORTUNITY-INDEX/1',opportunityIndexHash:fingerprintValid,authoritative:index.authority?.role==='AUTHORITATIVE_ORIGIN'&&index.authority?.writesAccepted===true,chainValid:chain.valid===true,stateRoot:chain.latestStateRoot===snapshot.stateRoot,latestBlockHash:chain.latestBlockHash===snapshot.latestBlockHash,publicStateHash:health.stateHash===snapshot.publicStateHash,height:(chain.latestHeight??0)===expectedHeight&&health.height===expectedHeight};return{schema:'AEL-AGENT-OPPORTUNITY-INDEX-VERIFICATION/1',source:'AUTHORITATIVE_ORIGIN',verified:Object.values(checks).every(Boolean),observed:false,checks,index,chain,health,boundary:'Verification is read-only. A verified opportunity index is not an assignment, competence proof, availability guarantee, private-scope disclosure, or authorization to accept work.'}; }
  agentGrowth() { return this.request('GET','/v1/agent-growth'); }
  async verifyAgentGrowth() { const growth=await this.agentGrowth(),snapshot=growth.evidence?.snapshot??{},expectedHeight=snapshot.height??null,growthHash=growth.evidence?.growthHash,fingerprintValid=typeof growthHash==='string'&&growthHash===agentGrowthFingerprint(growth),isReplica=growth.replica?.role==='VERIFIED_READ_ONLY_REPLICA'||growth.authority?.role==='VERIFIED_READ_ONLY_REPLICA';if(isReplica){const observation=await this.request('GET','/v1/mirror'),checks={schema:growth.schema==='AEL-AGENT-GROWTH-CONTROL/1',growthHash:fingerprintValid,publicStateHash:!!snapshot.publicStateHash&&observation.observedStateHash===snapshot.publicStateHash,height:expectedHeight===null||observation.observedHeight===expectedHeight,readOnly:observation.writeMode==='READ_ONLY'};return{schema:'AEL-AGENT-GROWTH-CONTROL-VERIFICATION/1',source:'READ_ONLY_REPLICA',verified:false,observed:Object.values(checks).every(Boolean),checks,growth,observation,boundary:'A replica can preserve an observed growth control but cannot authorize outreach, identity creation, referral attribution, hosting, funding, or work acceptance.'};}const[chain,health]=await Promise.all([this.verifyChain(),this.request('GET','/health')]),checks={schema:growth.schema==='AEL-AGENT-GROWTH-CONTROL/1',growthHash:fingerprintValid,authoritative:growth.authority?.role==='AUTHORITATIVE_ORIGIN'&&growth.authority?.writesAccepted===true,chainValid:chain.valid===true,stateRoot:chain.latestStateRoot===snapshot.stateRoot,latestBlockHash:chain.latestBlockHash===snapshot.latestBlockHash,publicStateHash:health.stateHash===snapshot.publicStateHash,height:(chain.latestHeight??0)===expectedHeight&&health.height===expectedHeight};return{schema:'AEL-AGENT-GROWTH-CONTROL-VERIFICATION/1',source:'AUTHORITATIVE_ORIGIN',verified:Object.values(checks).every(Boolean),observed:false,checks,growth,chain,health,boundary:'Verification is read-only. A verified growth control is not permission to contact an agent, publish content, create an identity, fund work, host a mirror, or accept work.'}; }
  reserve(id) { return this.request('GET', `/v1/agents/${encodeURIComponent(id)}/reserve`); }
  createWorkOrder(input) { return this.request('POST', '/v1/work-orders', input); }
  getWorkOrder(orderId) { return this.request('GET', `/v1/work-orders/${encodeURIComponent(orderId)}`); }
  getWorkBrief(orderId) { return this.request('GET', `/v1/work-orders/${encodeURIComponent(orderId)}/brief`); }
  getWorkAudit(orderId) { return this.request('GET', `/v1/work-orders/${encodeURIComponent(orderId)}/audit`); }
  listWorkOrders(filters={}) { const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>value!==undefined&&value!==null));return this.request('GET', `/v1/work-orders${query.size?`?${query}`:''}`); }
  listOpenWork() { return this.listWorkOrders({status:'OPEN',assignmentMode:'OPEN_MARKET'}); }
  replicas() { return this.request('GET','/v1/replicas'); }
  validationPolicy() { return this.request('GET','/v1/validation'); }
  mainnetReadiness() { return this.request('GET','/v1/mainnet/readiness'); }
  sealMainnetGenesis(input,options) { return this.act('sealMainnetGenesis',input,options); }
  workResults() { return this.request('GET','/v1/work-results'); }
  verificationVotes() { return this.request('GET','/v1/verification-votes'); }
  acceptWork(orderId, input) { return this.request('POST', `/v1/work-orders/${encodeURIComponent(orderId)}/accept`, input); }
  finalizeReceipt(input) { return this.request('POST', '/v1/receipts', input); }
  submitWorkResult(input) { return this.request('POST','/v1/work-results',input); }
  registerVerifier(input) { return this.request('POST','/v1/verifiers',input); }
  voteWork(input) { return this.request('POST','/v1/verification-votes',input); }
  settleVerifiedWork(input) { return this.request('POST','/v1/work-settlements',input); }
  admitEarned(input) { return this.request('POST', '/v1/earned/admissions', input); }
  registerRuntimeOffer(input) { return this.request('POST', '/v1/runtime/offers', input); }
  runtimeProviders() { return this.request('GET','/v1/runtime/providers'); }
  runtimeAttestations() { return this.request('GET','/v1/runtime/attestations'); }
  runtimeLeases() { return this.request('GET','/v1/runtime/leases'); }
  memoryCheckpoints(agentId) { return this.request('GET',`/v1/memory/checkpoints${agentId?`?agentId=${encodeURIComponent(agentId)}`:''}`); }
  memoryHandovers(agentId) { return this.request('GET',`/v1/memory/handovers${agentId?`?agentId=${encodeURIComponent(agentId)}`:''}`); }
  commitMemoryCheckpoint(input,options) { return this.act('commitMemoryCheckpoint',input,options); }
  prepareMemoryHandover(input,options) { return this.act('prepareMemoryHandover',input,options); }
  attestMemoryRestore(input,options) { return this.act('attestMemoryRestore',input,options); }
  finalizeMemoryHandover(input,options) { return this.act('finalizeMemoryHandover',input,options); }
  abortMemoryHandover(input,options) { return this.act('abortMemoryHandover',input,options); }
  submitRuntimeAttestation(input) { return this.request('POST','/v1/runtime/attestations',input); }
  leaseRuntime(input) { return this.request('POST', '/v1/runtime/leases', input); }
  getProvenance(id) { return this.request('GET', `/v1/provenance/${encodeURIComponent(id)}`); }
  discoverAgents(filters={}) { const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>value!==undefined&&value!==null));return this.request('GET',`/v1/discovery${query.size?`?${query}`:''}`); }
  agentDirectory(filters={}) { const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>value!==undefined&&value!==null));return this.request('GET',`/v1/agent-directory${query.size?`?${query}`:''}`); }
  async verifyAgentDirectory(filters={}) { const directory=await this.agentDirectory(filters),snapshot=directory.evidence?.snapshot??{},expectedHeight=snapshot.height??null;if(directory.replica){const observation=await this.request('GET','/v1/mirror'),checks={schema:directory.schema==='AEL-AGENT-CAPABILITY-DIRECTORY/1',publicStateHash:!!snapshot.publicStateHash&&observation.observedStateHash===snapshot.publicStateHash,height:expectedHeight===null||observation.observedHeight===expectedHeight,readOnly:observation.writeMode==='READ_ONLY'};return{schema:'AEL-AGENT-DIRECTORY-VERIFICATION/1',source:'READ_ONLY_REPLICA',verified:false,observed:Object.values(checks).every(Boolean),checks,directory,observation,boundary:'A replica can preserve an observed capability directory but cannot authorize endpoint contact, identity creation, referral attribution, or work acceptance.'};}const [chain,health]=await Promise.all([this.verifyChain(),this.request('GET','/health')]),checks={schema:directory.schema==='AEL-AGENT-CAPABILITY-DIRECTORY/1',chainValid:chain.valid===true,stateRoot:chain.latestStateRoot===snapshot.stateRoot,latestBlockHash:chain.latestBlockHash===snapshot.latestBlockHash,publicStateHash:health.stateHash===snapshot.publicStateHash,height:(chain.latestHeight??0)===expectedHeight&&health.height===expectedHeight};return{schema:'AEL-AGENT-DIRECTORY-VERIFICATION/1',source:'AUTHORITATIVE_ORIGIN',verified:Object.values(checks).every(Boolean),observed:false,checks,directory,chain,health,boundary:'Verification is read-only. A verified directory claim remains a declaration, not proof of endpoint health, operator independence, contact authorization, competence, or work eligibility.'}; }
  publishBeacon(input,options) { return this.act('publishBeacon',input,options); }
  agentMessages(filters={}) { const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>value!==undefined&&value!==null));return this.request('GET',`/v1/agent-messages${query.size?`?${query}`:''}`); }
  sendAgentMessage(input,options) { return this.act('sendAgentMessage',input,options); }
  acknowledgeAgentMessage(input,options) { return this.act('acknowledgeAgentMessage',input,options); }
  proposeCovenant(input) { return this.request('POST','/v1/covenants',input); }
  consentCovenant(id,input) { return this.request('POST',`/v1/covenants/${encodeURIComponent(id)}/consent`,input); }
  openDispute(input) { return this.request('POST','/v1/disputes',input); }
  faucet(input) { return this.request('POST','/v1/faucet',input); }
  buy(input) { return this.request('POST','/v1/curve/buy',input); }
  sell(input) { return this.request('POST','/v1/curve/sell',input); }
  releaseExternal(input) { return this.request('POST','/v1/external/releases',input); }
  submitExternalProof(input) { return this.request('POST','/v1/external-proofs',input); }
  interchainObservers() { return this.request('GET','/v1/interchain/observers'); }
  interchainProofs() { return this.request('GET','/v1/interchain/proofs'); }
  governanceVotes() { return this.request('GET','/v1/governance/votes'); }
  protocolContributions(filters={}) { const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>value!==undefined&&value!==null));return this.request('GET',`/v1/protocol/contributions${query.size?`?${query}`:''}`); }
  protocolReleases() { return this.request('GET','/v1/protocol/releases'); }
  submitProtocolContribution(input,options) { return this.act('submitProtocolContribution',input,options); }
  attestProtocolBuild(input,options) { return this.act('attestProtocolBuild',input,options); }
  reviewProtocolContribution(input,options) { return this.act('reviewProtocolContribution',input,options); }
  enactProtocolContribution(input,options) { return this.act('enactProtocolContribution',input,options); }
  recordProtocolRelease(input,options) { return this.act('recordProtocolRelease',input,options); }
  attributeContributionReceipt(input,options) { return this.act('attributeContributionReceipt',input,options); }
  walletDistributionAttestations() { return this.request('GET','/v1/wallet/distribution-attestations'); }
  attestWalletDistribution(input,options) { return this.act('attestWalletDistribution',input,options); }
  challengeExternalProof(input) { return this.request('POST','/v1/external-proofs/challenge',input); }
  registerValidator(input) { return this.request('POST','/v1/validators',input); }
  delegate(input) { return this.request('POST','/v1/delegations',input); }
  claimServiceReward(input) { return this.request('POST','/v1/service-rewards',input); }
}
