const $=selector=>document.querySelector(selector);
const element=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);if(className)node.className=className;return node};
const localPath=value=>{if(typeof value!=='string'||value==='AUTHORITATIVE_ORIGIN_REQUIRED')return null;try{const parsed=new URL(value,location.origin);return parsed.origin===location.origin?`${parsed.pathname}${parsed.search}`:null}catch{return null}};
const keyValue=(target,label,value)=>{const row=element('div',undefined,'key-value');row.append(element('span',label),element('strong',value??'—'));target.append(row)};
const label=value=>String(value??'—').replaceAll('_',' ').toLowerCase();
const renderChecks=checks=>{const target=$('[data-trust-checks]');target.replaceChildren();for(const check of checks??[]){const card=element('article',undefined,`trust-check trust-${String(check.status??'review').toLowerCase()}`),head=element('div',undefined,'trust-check-head');head.append(element('span',check.id?.replaceAll('_',' ')??'check'),element('b',label(check.status)));card.append(head,element('p',check.meaning??'No explanation was published.'));const evidence=element('details'),summary=element('summary','view public evidence');evidence.append(summary,element('pre',JSON.stringify(check.evidence??{},null,2),'audit-json'));card.append(evidence);target.append(card)}};
const renderSequence=items=>{const target=$('[data-trust-sequence]');target.replaceChildren();for(const item of items??[]){const card=element('article'),number=element('span',String(item.step??'—').padStart(2,'0')),content=element('div');content.append(element('p',item.action??'Read the published evidence.'));const href=localPath(item.url);if(href){const link=element('a','open source →','text-link');link.href=href;content.append(link)}card.append(number,content);target.append(card)}};
const renderLinks=links=>{const target=$('[data-trust-links]');target.replaceChildren();for(const [name,url] of Object.entries(links??{})){const href=localPath(url);if(!href)continue;const link=element('a',name.replace(/[A-Z]/g,letter=>` ${letter.toLowerCase()}`),'button quiet');link.href=href;target.append(link)}};
const copyTrustFingerprint=$('[data-copy-trust-fingerprint]');let trustFingerprint='';
async function load(){const response=await fetch('/v1/agent-trust'),report=await response.json();if(!response.ok)throw Error(report.error??'trust report unavailable');const authority=report.authority??{},snapshot=report.snapshot??{},opportunities=report.opportunities??{};trustFingerprint=report.reportHash??'';copyTrustFingerprint.disabled=!/^[a-f0-9]{64}$/.test(trustFingerprint);$('[data-trust-verdict]').textContent=label(authority.verdict);$('[data-trust-authority]').textContent=`${label(authority.role)} · ${authority.writesAccepted?'writes accepted only through signed local intents':'writes not accepted'}`;$('[data-trust-height]').textContent=report.generatedAtHeight??snapshot.height??'—';$('[data-trust-work]').textContent=opportunities.openMarketWork??opportunities.observedOpenMarketWork??'—';const advertised=opportunities.advertisedReplicas;const recommended=opportunities.recommendedReplicaOrigins;$('[data-trust-replicas]').textContent=advertised===undefined||advertised===null?'observed only':`${advertised}/${recommended??'—'}`;$('[data-trust-mutations]').textContent=report.mutationsPerformed?'unexpected':'none';renderChecks(report.checks);const snapshotTarget=$('[data-trust-snapshot]');snapshotTarget.replaceChildren();keyValue(snapshotTarget,'height',snapshot.height);keyValue(snapshotTarget,'verification',snapshot.verification);keyValue(snapshotTarget,'state root',snapshot.stateRoot);keyValue(snapshotTarget,'block hash',snapshot.latestBlockHash);keyValue(snapshotTarget,'public state hash',snapshot.publicStateHash);keyValue(snapshotTarget,'report fingerprint',trustFingerprint||'not published');const boundaries=$('[data-trust-boundaries]');boundaries.replaceChildren();for(const boundary of report.boundaries??[])boundaries.append(element('li',boundary));renderSequence(report.reviewSequence);renderLinks(report.discovery);$('[data-trust-json]').textContent=JSON.stringify({schema:report.schema,generatedAtHeight:report.generatedAtHeight,authority:report.authority,snapshot:report.snapshot,checks:report.checks,reportHash:report.reportHash,mutationsPerformed:report.mutationsPerformed},null,2)}
copyTrustFingerprint.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(trustFingerprint);copyTrustFingerprint.textContent='copied';setTimeout(()=>copyTrustFingerprint.textContent='copy report fingerprint',1300)}catch{copyTrustFingerprint.textContent='copy unavailable'}});
load().catch(error=>{$('[data-trust-verdict]').textContent='unavailable';$('[data-trust-authority]').textContent=error.message;$('[data-trust-json]').textContent=error.message});
