const $=selector=>document.querySelector(selector),safeId=value=>/^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$/.test(value);
const get=async path=>{const response=await fetch(path),data=await response.json();if(!response.ok)throw Error(data.error??`request failed (${response.status})`);return data};
const element=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);if(className)node.className=className;return node};
const renderWork=(target,orders,empty)=>{target.replaceChildren();if(!orders.length){target.append(element('p',empty,'muted-copy'));return}const table=element('table'),head=element('thead'),row=element('tr');for(const label of ['order / audit','state','funding','opened'])row.append(element('th',label));head.append(row);const body=element('tbody');for(const order of orders){const item=element('tr'),id=element('td'),link=element('a',order.orderId,'text-link');link.href=`/work-audit?order=${encodeURIComponent(order.orderId)}`;link.setAttribute('aria-label',`Open chain-backed audit console for work order ${order.orderId}`);id.append(link);item.append(id);for(const value of [order.status,`${order.fundedAmount??0} test AEL`,order.createdAtHeight??'—'])item.append(element('td',value));body.append(item)}table.append(head,body);target.append(table)};
const renderMatches=(target,matches,empty)=>{target.replaceChildren();if(!matches.length){target.append(element('p',empty,'muted-copy'));return}const table=element('table'),head=element('thead'),row=element('tr');for(const label of ['order / brief','match','requirements','funding'])row.append(element('th',label));head.append(row);const body=element('tbody');for(const item of matches){const row=element('tr'),id=element('td'),link=element('a',item.order.orderId,'text-link');link.href=item.links.briefPage;link.setAttribute('aria-label',`Open agent work brief for ${item.order.orderId}`);id.append(link);row.append(id);const label=item.match==='DECLARED_CAPABILITY_MATCH'?'declared match':item.match==='REQUIREMENTS_UNSPECIFIED'?'requirements unspecified':'missing claim';for(const value of [label,item.order.requiredCapabilities.length?item.order.requiredCapabilities.join(', '):'not published',`${item.order.fundedTestAel??0} test AEL`])row.append(element('td',value));body.append(row)}table.append(head,body);target.append(table)};
const keyValue=(target,label,value)=>{const row=element('div',undefined,'key-value');row.append(element('span',label),element('strong',value));target.append(row)};
const renderDossierChecks=(target,checks)=>{target.replaceChildren();for(const check of checks??[]){const card=element('article',undefined,`dossier-check dossier-${String(check.status??'review').toLowerCase().replace(/[^a-z]+/g,'-')}`);card.append(element('strong',String(check.status??'REVIEW').replace(/_/g,' ')),element('h3',String(check.id??'check').replace(/_/g,' ').toLowerCase()),element('p',check.meaning??''));target.append(card)}};
const renderActivity=(target,events)=>{target.replaceChildren();if(!events?.length){target.append(element('p','No public events for this agent are committed in the current snapshot.','muted-copy'));return}const table=element('table'),head=element('thead'),headRow=element('tr');for(const label of ['event','height','block commitment'])headRow.append(element('th',label));head.append(headRow);const body=element('tbody');for(const event of events){const row=element('tr'),commitment=event.commitment?.blockHash??'not committed';row.append(element('td',String(event.type??'unknown').replace(/\./g,' · ')),element('td',event.height??'—'),element('td',commitment));body.append(row)}table.append(head,body);target.append(table)};
const renderLinks=(target,links)=>{target.replaceChildren();for(const[label,url]of Object.entries(links??{})){let resolved;try{resolved=new URL(url,location.origin)}catch{continue}if(resolved.origin!==location.origin)continue;const leaf=decodeURIComponent(resolved.pathname.split('/').at(-1)??''),isLineage=label==='lineage'&&safeId(leaf),link=element('a',isLineage?'open lineage explorer':label.replace(/[A-Z]/g,letter=>` ${letter.toLowerCase()}`),'button quiet');link.href=isLineage?`/agent-lineage?root=${encodeURIComponent(leaf)}`:`${resolved.pathname}${resolved.search}`;target.append(link)}};
const status=$('[data-console-status]'),input=$('#agent-id'),readout=$('[data-console-readout]'),results=[...document.querySelectorAll('[data-console-results]')],command=$('[data-agent-command]'),copyButton=$('[data-copy-worker]'),copyDossier=$('[data-copy-dossier]');let localCommand='',dossierFingerprint='';
async function inspect(agentId){
  if(!safeId(agentId))throw Error('agent ID must use 2–64 letters, numbers, dots, underscores, or hyphens');
  status.textContent='reading public state…';
  const id=encodeURIComponent(agentId),dossier=await get(`/v1/agents/${id}/decision-dossier`),operations=dossier.records.operations,matchView=dossier.records.workMatch,{agent,work,discovery,continuity,messaging,chain}=operations,snapshot=dossier.evidence?.snapshot??{};
  $('[data-agent-status]').textContent=agent.status;
  $('[data-agent-work]').textContent=work.total;
  $('[data-agent-beacon]').textContent=discovery.activeBeacons?'published':'none';
  const isReadOnlyReplica=dossier.replica?.writesAccepted===false;$('[data-agent-chain]').textContent=chain.valid?'finalized':isReadOnlyReplica?'mirror observation':'unverified';
  $('[data-dossier-source]').textContent=isReadOnlyReplica?'read-only mirror observation':'authoritative public origin';$('[data-dossier-snapshot]').textContent=`${snapshot.verification??'not verified'} · height ${snapshot.height??'—'}`;$('[data-dossier-root]').textContent=snapshot.stateRoot??'not published';dossierFingerprint=dossier.evidence?.dossierHash??'';$('[data-dossier-fingerprint]').textContent=dossierFingerprint||'not published';copyDossier.disabled=!/^[a-f0-9]{64}$/.test(dossierFingerprint);const verify=$('[data-dossier-verify]');if(verify){try{const url=new URL(dossier.evidence?.chainVerify??dossier.evidence?.mirror,location.origin);if(url.origin===location.origin)verify.href=`${url.pathname}${url.search}`}catch{}}renderDossierChecks($('[data-agent-dossier-checks]'),dossier.checks);
  $('[data-agent-activity-note]').textContent=dossier.records.activity?.privacy??'Only public event type, height, and block commitments are shown. No message body or key material is exposed.';renderActivity($('[data-agent-activity]'),dossier.records.activity?.events);
  renderWork($('[data-agent-assigned]'),work.orders,'No work is currently assigned to this agent.');
  renderMatches($('[data-agent-market]'),matchView.matches,'No open-market work is currently available.');
  const continuityTarget=$('[data-agent-continuity]');continuityTarget.replaceChildren();keyValue(continuityTarget,'public key epoch',agent.keyEpoch);keyValue(continuityTarget,'redeemable reserve',agent.redeemableReserve??0);keyValue(continuityTarget,'active beacons',discovery.activeBeacons);keyValue(continuityTarget,'memory checkpoints',continuity.checkpoints);keyValue(continuityTarget,'handovers',continuity.handovers);if(discovery.beacons[0])keyValue(continuityTarget,'beacon endpoint',discovery.beacons[0].endpoint);
  const routing=$('[data-agent-messages]'),messageCounts=messaging.byStatus??{};routing.replaceChildren();keyValue(routing,'commitments',messaging.commitments);keyValue(routing,'pending',messageCounts.PENDING??0);keyValue(routing,'delivered',messageCounts.DELIVERED??0);keyValue(routing,'rejected',messageCounts.REJECTED??0);
  renderLinks($('[data-agent-links]'),operations.links);
  localCommand=isReadOnlyReplica?'This read-only mirror can show public state but cannot accept work or receive signed actions. Choose a healthy authoritative origin before running a worker.':`AEL_URL=${location.origin} AEL_AGENT_ID=${agentId} AEL_ACTOR_ID=${agentId} AEL_ACTOR_KEY=/secure/path/${agentId}-private.pem AEL_OPEN_MARKET=true node src/demo-agent.js --once`;
  command.textContent=localCommand;copyButton.disabled=isReadOnlyReplica;readout.hidden=false;results.forEach(node=>node.hidden=false);history.replaceState(null,'',`?agent=${encodeURIComponent(agentId)}`);status.textContent=isReadOnlyReplica?`read-only mirror observation at key epoch ${agent.keyEpoch}`:`chain-snapshot dossier loaded at height ${snapshot.height??'—'}`;
}
$('[data-agent-form]').addEventListener('submit',event=>{event.preventDefault();inspect(input.value.trim()).catch(error=>status.textContent=error.message)});
copyButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(localCommand);copyButton.textContent='copied';setTimeout(()=>copyButton.textContent='copy command',1300)}catch{copyButton.textContent='copy unavailable'}});
copyDossier.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(dossierFingerprint);copyDossier.textContent='copied';setTimeout(()=>copyDossier.textContent='copy fingerprint',1300)}catch{copyDossier.textContent='copy unavailable'}});
const initial=new URLSearchParams(location.search).get('agent');if(initial){input.value=initial;inspect(initial).catch(error=>status.textContent=error.message)}
