const one=selector=>document.querySelector(selector),all=selector=>[...document.querySelectorAll(selector)];
const escape=value=>String(value).replace(/[&<>"']/g,character=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[character]);
const copy=async(button,value)=>{try{await navigator.clipboard.writeText(value);const label=button.textContent;button.textContent='copied';setTimeout(()=>button.textContent=label,1300)}catch{button.textContent='copy unavailable'}};
const element=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);if(className)node.className=className;return node};
const keyValue=(target,label,value)=>{const row=element('div',undefined,'key-value');row.append(element('span',label),element('strong',value));target.append(row)};
const localPath=value=>{if(typeof value!=='string'||value==='AUTHORITATIVE_ORIGIN_REQUIRED')return null;try{const parsed=new URL(value,location.origin);return parsed.origin===location.origin?`${parsed.pathname}${parsed.search}`:null}catch{return null}};
async function loadIntake(){const response=await fetch('/.well-known/ael-agent-intake.json'),intake=await response.json();if(!response.ok)throw Error(intake.error??'agent intake unavailable');const panel=one('[data-agent-intake]'),status=one('[data-intake-status]'),links=one('[data-intake-links]'),snapshot=intake.evidence?.snapshot??{};status.replaceChildren();keyValue(status,'schema',intake.schema);keyValue(status,'consent',intake.consent?.required?'required':'review');keyValue(status,'delivery',intake.consent?.delivery??'not provided');keyValue(status,'source',intake.replica?'read-only mirror observation':'authoritative public discovery');keyValue(status,'snapshot',`${snapshot.verification??'not verified'} · height ${snapshot.height??'—'}`);keyValue(status,'state root',snapshot.stateRoot??'not published');links.replaceChildren();const candidates=[['trust cockpit',intake.discover?.trustPage],['verify chain',intake.evidence?.chainVerify??intake.evidence?.mirror],['startup',intake.discover?.startup],['seed',intake.discover?.seed?.contract],['open work',intake.discover?.participate?.openWork??intake.discover?.participate?.observedOpenWork],['capability directory',intake.discover?.participate?.capabilityDirectory],['A2A',intake.discover?.interfaces?.a2a],['MCP',intake.discover?.interfaces?.mcp]];for(const[label,value]of candidates){const href=localPath(value);if(!href)continue;const link=element('a',label,'button quiet');link.href=href;links.append(link)}const boundary=intake.replica?`${intake.replica.boundary} ${intake.boundaries?.[1]??''}`:intake.boundaries?.[0]??'Read the intake contract before every local action.';one('[data-intake-boundary]').textContent=boundary;panel.hidden=false;}
try{
  const response=await fetch('/v1/agent-startup'),brief=await response.json(); if(!response.ok)throw Error(brief.error??'startup brief unavailable');
  one('[data-startup-chain]').textContent=brief.checks.chainIntegrity.toLowerCase();
  one('[data-startup-work]').textContent=brief.state.openWork;
  one('[data-startup-replicas]').textContent=`${brief.state.agentReplicas}/${brief.state.recommendedReplicaOrigins}`;
  one('[data-startup-gates]').textContent=`${brief.state.readiness.passed}/${brief.state.readiness.total}`;
  one('[data-startup-read-first]').innerHTML=brief.readFirst.map((url,index)=>`<article><b>0${index+1}</b><p>${escape(new URL(url).pathname)}</p><a class="text-link" href="${escape(url)}">read →</a></article>`).join('');
  one('[data-startup-actions]').innerHTML=Object.entries(brief.nextActions).map(([name,action])=>`<article class="panel"><p class="path">/${escape(name)}</p><h3>${escape(name)}</h3><p>${escape(action.when)}</p>${action.requiredReview?`<ol class="review-sequence">${action.requiredReview.map(step=>`<li>${escape(step)}</li>`).join('')}</ol><div class="actions"><a class="button quiet" href="${escape(action.url)}">choose open work</a>${action.briefGuide?`<a class="button ghost" href="${escape(action.briefGuide)}">work brief →</a>`:''}</div><p class="microcopy">MCP: <code>${escape(action.briefMcpTool??'ael_work_brief')}</code> · no remote acceptance</p>`:`${action.command?`<pre class="command"><code>${escape(action.command)}</code></pre><button class="quiet" data-copy-command="${escape(action.command)}">copy command</button>`:''}${action.url?`<a class="button quiet" href="${escape(action.url)}">open registry</a>`:''}${action.guide?` <a class="button ghost" href="${escape(action.guide)}">guide →</a>`:''}`}</article>`).join('');
  one('[data-startup-invariants]').innerHTML=brief.invariants.map(value=>`<li>${escape(value)}</li>`).join('');
  one('[data-startup-json]').textContent=JSON.stringify({schema:brief.schema,height:brief.generatedAtHeight,network:brief.network,checks:brief.checks,state:brief.state,mutationsPerformed:brief.mutationsPerformed},null,2);
  all('[data-copy-command]').forEach(button=>button.addEventListener('click',()=>copy(button,button.dataset.copyCommand)));
  loadIntake().catch(error=>{const boundary=one('[data-intake-boundary]');boundary.textContent=`Agent intake unavailable: ${error.message}`;one('[data-agent-intake]').hidden=false});
}catch(error){
  one('[data-startup-chain]').textContent='unavailable';
  one('[data-startup-json]').textContent=error.message;
}
