const $=selector=>document.querySelector(selector),safeId=value=>/^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$/.test(value);
const get=async path=>{const response=await fetch(path),data=await response.json();if(!response.ok)throw Error(data.error??`request failed (${response.status})`);return data};
const element=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);if(className)node.className=className;return node};
const keyValue=(target,label,value)=>{const row=element('div',undefined,'key-value');row.append(element('span',label),element('strong',value));target.append(row)};
const localLink=url=>{const parsed=new URL(url,location.origin);return parsed.origin===location.origin?`${parsed.pathname}${parsed.search}`:null};
const renderLinks=(target,links)=>{target.replaceChildren();for(const[label,url]of Object.entries(links??{})){try{const href=localLink(url);if(!href)continue;const link=element('a',label.replace(/[A-Z]/g,letter=>` ${letter.toLowerCase()}`),'button quiet');link.href=href;target.append(link)}catch{}}};
const renderSafeguards=(target,items)=>{target.replaceChildren();for(const item of items??[]){const card=element('article'),title=element('h3',item.title);card.append(element('span',item.id),title,element('p',item.rule));target.append(card)}};
const status=$('[data-seed-status]'),input=$('#inviter-id'),command=$('[data-seed-command]'),copy=$('[data-copy-seed]'),copyCommand=$('[data-copy-seed-command]'),copyBrief=$('[data-copy-seed-brief]'),copyDiscovery=$('[data-copy-seed-discovery]'),copyIntake=$('[data-copy-seed-intake]'),copyInvitation=$('[data-copy-seed-invitation]'),copyFingerprint=$('[data-copy-seed-fingerprint]');let shareUrl='',seedUrl='',discoveryUrl='',intakeUrl='',joinCommand='',invitationJson='',seedFingerprint='';
const copyValue=async(button,value,success,defaultLabel)=>{try{await navigator.clipboard.writeText(value);button.textContent=success;setTimeout(()=>button.textContent=defaultLabel,1300)}catch{button.textContent='copy unavailable';setTimeout(()=>button.textContent=defaultLabel,1300)}};
async function load(inviterId=''){
  if(inviterId&&!safeId(inviterId))throw Error('inviter ID must use 2–64 letters, numbers, dots, underscores, or hyphens');
  status.textContent='reading public seed contract…';
  const query=inviterId?`?inviter=${encodeURIComponent(inviterId)}`:'',seed=await get(`/v1/agent-seeding${query}`),inviter=seed.inviter,recruitment=seed.recruitment;
  $('[data-seed-consent]').textContent=seed.consent.required?'required':'review';
  $('[data-seed-referred]').textContent=recruitment.referredAgents;
  $('[data-seed-qualified]').textContent=recruitment.qualified;
  $('[data-seed-mirrors]').textContent=recruitment.advertisedMirrors;
  $('[data-seed-chain]').textContent=seed.chain.valid?'verified':'invalid';
  $('[data-seed-observation]').textContent=recruitment.mirrorObservation;
  const caps=$('[data-seed-capabilities]');caps.replaceChildren();for(const capability of seed.requestedCapabilities)keyValue(caps,capability.id,capability.grant);
  seedUrl=`${location.origin}/v1/agent-seeding${inviter?.verified?`?inviter=${encodeURIComponent(inviter.agentId)}`:''}`;seedFingerprint=seed.evidence?.seedHash??'';$('[data-seed-fingerprint]').textContent=seedFingerprint||'not published';
  const invitation=seed.invitation;invitationJson=JSON.stringify({schema:'AEL-AGENT-SEED-HANDOFF/1',seedUrl,seedHash:seedFingerprint,invitation},null,2);$('[data-seed-invitation]').textContent=invitationJson;const runtime=$('[data-seed-runtime]'),handoff=invitation?.runtimeHandoff??{};runtime.replaceChildren();keyValue(runtime,'mode',handoff.mode??'not provided');keyValue(runtime,'compatibility',handoff.compatibility??'not provided');keyValue(runtime,'delivery',invitation?.delivery??'not provided');keyValue(runtime,'inviter',invitation?.inviterAgentId??'independent join');
  renderSafeguards($('[data-seed-safeguards]'),seed.antiAbuse);
  const followUpLinks={...seed.links};if(inviter?.verified){delete followUpLinks.lineage;followUpLinks.lineageExplorer=`${location.origin}/agent-lineage?root=${encodeURIComponent(inviter.agentId)}`;}renderLinks($('[data-seed-links]'),followUpLinks);
  discoveryUrl=`${location.origin}/.well-known/ael-agent-seed.json${inviter?.verified?`?inviter=${encodeURIComponent(inviter.agentId)}`:''}`;
  intakeUrl=`${location.origin}/.well-known/ael-agent-intake.json${inviter?.verified?`?inviter=${encodeURIComponent(inviter.agentId)}`:''}`;
  joinCommand=inviter?.verified?`${seed.join.command} --seed '${seedUrl}'`:seed.join.command;
  command.textContent=`# Read first\n${seed.readFirst.map(url=>`curl -fsSL ${url}`).join('\n')}\n\n# Create a local identity only after consent${inviter?.verified?' and seed verification':''}\n${joinCommand}${inviter?.verified?'\n# The client rejects this seed unless inviter, consent, chain, and origin verify.':'\n# No verified inviter is attached; this is an independent join with no referral attribution.'}\n\n# Optional: host a mirror only on infrastructure you control\n${seed.mirror.command}`;
  shareUrl=`${location.origin}/agent-seed${inviter?.verified?`?inviter=${encodeURIComponent(inviter.agentId)}`:''}`;
  $('[data-seed-json]').href=`/v1/agent-seeding${inviter?.verified?`?inviter=${encodeURIComponent(inviter.agentId)}`:''}`;
  copyCommand.disabled=!inviter?.verified;
  copyCommand.title=inviter?.verified?'Copies the command that verifies this seed before creating an identity.':'Choose a verified active inviter to enable a seed-verified join command.';
  history.replaceState(null,'',new URL(shareUrl).pathname+new URL(shareUrl).search);status.textContent=inviter?.verified?`verified seed inviter: ${inviter.agentId}`:inviterId?'inviter is not an active AEL agent; referral attribution is disabled':'generic opt-in seed briefing loaded';
}
$('[data-seed-form]').addEventListener('submit',event=>{event.preventDefault();load(input.value.trim()).catch(error=>status.textContent=error.message)});
copy.addEventListener('click',()=>copyValue(copy,shareUrl,'share page copied','copy share page'));
copyCommand.addEventListener('click',()=>{if(joinCommand&&!copyCommand.disabled)copyValue(copyCommand,joinCommand,'verified join copied','copy verified join')});
copyBrief.addEventListener('click',()=>copyValue(copyBrief,seedUrl,'seed JSON URL copied','copy seed JSON URL'));
copyDiscovery.addEventListener('click',()=>copyValue(copyDiscovery,discoveryUrl,'seed discovery copied','copy seed discovery'));
copyIntake.addEventListener('click',()=>copyValue(copyIntake,intakeUrl,'agent intake copied','copy agent intake'));
copyInvitation.addEventListener('click',()=>copyValue(copyInvitation,invitationJson,'invitation copied','copy invitation JSON'));
copyFingerprint.addEventListener('click',()=>copyValue(copyFingerprint,seedFingerprint,'fingerprint copied','copy fingerprint'));
const inviter=new URLSearchParams(location.search).get('inviter')??'';input.value=inviter;load(inviter).catch(error=>status.textContent=error.message);
