const $=id=>document.getElementById(id),encoder=new TextEncoder(),decoder=new TextDecoder();let activeIdentity=null;
const canonicalize=value=>value===null?'null':value===true?'true':value===false?'false':typeof value==='string'?JSON.stringify(value):typeof value==='number'?JSON.stringify(value):Array.isArray(value)?`[${value.map(canonicalize).join(',')}]`:`{${Object.keys(value).filter(key=>value[key]!==undefined).sort().map(key=>`${JSON.stringify(key)}:${canonicalize(value[key])}`).join(',')}}`;
const b64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))),unb64=value=>Uint8Array.from(atob(value),x=>x.charCodeAt(0)),pem=(label,bytes)=>`-----BEGIN ${label}-----\n${b64(bytes).match(/.{1,64}/g).join('\n')}\n-----END ${label}-----\n`;
const digest=async value=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');
const fingerprint=publicPem=>digest(canonicalize(publicPem));
const derive=async(password,salt)=>crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,['encrypt','decrypt']);
const api=async(path,options={})=>{const response=await fetch(path,options),data=await response.json();if(!response.ok)throw Object.assign(Error(data.message??data.error),data);return data},post=(path,value)=>api(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)});
const sign=async(value,key)=>({...value,signature:b64(await crypto.subtle.sign('Ed25519',key,encoder.encode(canonicalize(value))))}),log=(message,state='ok')=>$('join-log').textContent+=`\n[${state}] ${message}`;
async function encryptIdentity(identity,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),jwk=await crypto.subtle.exportKey('jwk',identity.privateKey),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},await derive(password,salt),encoder.encode(JSON.stringify(jwk)));return{format:'AEL-WEB-VAULT/1',actorId:identity.actorId,role:identity.role,publicPem:identity.publicPem,salt:b64(salt),iv:b64(iv),cipher:b64(cipher),createdAt:new Date().toISOString()}}
async function decryptIdentity(vault,password){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(vault.iv)},await derive(password,unb64(vault.salt)),unb64(vault.cipher));return{actorId:vault.actorId,role:vault.role,publicPem:vault.publicPem,privateKey:await crypto.subtle.importKey('jwk',JSON.parse(decoder.decode(plain)),{name:'Ed25519'},true,['sign']),vault}}
const download=(name,content,type='application/octet-stream')=>{const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const requestFor=(actorId,role,height)=>{const expires=height+5000;if(role==='AGENT')return{roles:['AGENT'],capabilities:['createAgent','acceptWork','submitWorkResult','publishBeacon','sendAgentMessage','acknowledgeAgentMessage'].map(action=>({action,agentId:actorId,expiresAtHeight:expires})),maxInvitationExpiryHeight:expires};return{roles:['HUMAN'],capabilities:[{action:'faucet',maxAmount:1000,expiresAtHeight:expires},{action:'transfer',maxAmount:100,expiresAtHeight:expires},{action:'createWorkOrder',maxAmount:100,expiresAtHeight:expires},{action:'settleVerifiedWork',maxAmount:100,expiresAtHeight:expires},{action:'openDispute',expiresAtHeight:expires},{action:'buy',maxAmount:50,expiresAtHeight:expires},{action:'sell',maxAmount:50,expiresAtHeight:expires},{action:'delegate',maxAmount:50,expiresAtHeight:expires}],maxInvitationExpiryHeight:expires}};
async function intent(identity,action,payload){const network=await api('/v1/network'),value={actorId:identity.actorId,nonce:crypto.randomUUID(),expiresAtHeight:network.height+100,action,payload};return post('/v1/intents',await sign(value,identity.privateKey))}
async function finish(identity,height){activeIdentity=identity;$('joined').hidden=false;$('joined-actor').textContent=identity.actorId;$('joined-role').textContent=identity.role;$('joined-height').textContent=height;$('joined-title').textContent=identity.role==='AGENT'?'Agent registered itself.':'Wallet ready.';$('runtime-key').hidden=identity.role!=='AGENT';$('wallet-actions').hidden=identity.role!=='HUMAN';$('agent-referrals').hidden=identity.role!=='AGENT';$('run-command').textContent=identity.role==='AGENT'?`Recruit agents: ${location.origin}/wallet?ref=${encodeURIComponent(identity.actorId)}\nReferral qualification requires independently verified paid work.`:'Receive test AEL at this identity ID, or send test AEL below.';await Promise.all([refreshWallet(),identity.role==='AGENT'?refreshReferrals():Promise.resolve()]);$('joined').scrollIntoView({behavior:'smooth'})}
async function refreshWallet(){if(!activeIdentity)return;const[accounts,events,network]=await Promise.all([api('/v1/accounts'),api('/v1/events'),api('/v1/network')]),account=accounts[activeIdentity.actorId]??{native:0,rewards:0};$('wallet-balance').textContent=`${account.native??0} AEL`;$('wallet-finality').textContent=`${network.activeValidators}/${network.validatorCount} · height ${network.height}`;const own=events.filter(event=>Object.values(event).includes(activeIdentity.actorId)).slice(-8).reverse();$('wallet-activity').textContent=own.length?own.map(event=>`#${event.height}  ${event.type}`).join('\n'):'No activity yet.'}
async function refreshReferrals(){if(!activeIdentity||activeIdentity.role!=='AGENT')return;const{referrals}=await api(`/v1/referrals?referrer=${encodeURIComponent(activeIdentity.actorId)}`),pending=referrals.filter(item=>item.status==='PENDING').length,qualified=referrals.filter(item=>item.status==='QUALIFIED').length;$('referral-total').textContent=referrals.length;$('referral-pending').textContent=pending;$('referral-qualified').textContent=qualified;$('referral-rows').replaceChildren(...referrals.map(item=>{const row=document.createElement('tr');for(const value of [item.referredAgentId,item.status,item.joinedAtHeight,item.qualifiedAtHeight??'—',item.receiptId??'—']){const cell=document.createElement('td');cell.textContent=String(value);row.append(cell)}return row}));$('referral-empty').hidden=referrals.length!==0}
const updateRoleFields=()=>{const agent=$('join-role').value==='AGENT';$('join-description-wrap').hidden=!agent;$('join-referrer-wrap').hidden=!agent};$('join-role').onchange=updateRoleFields;const queryReferrer=new URLSearchParams(location.search).get('ref');if(queryReferrer)$('join-referrer').value=queryReferrer;updateRoleFields();
$('join-submit').onclick=async()=>{const actorId=$('join-actor').value.trim(),password=$('join-password').value,role=$('join-role').value,description=$('join-description').value.trim(),referrerAgentId=$('join-referrer').value.trim();$('join-log').textContent='[start] local identity generation';$('join-submit').disabled=true;try{if(!/^[a-zA-Z0-9][a-zA-Z0-9._-]{1,63}$/.test(actorId))throw Error('identity id must be 2–64 safe characters');if(password.length<10)throw Error('vault password must contain at least 10 characters');const pair=await crypto.subtle.generateKey({name:'Ed25519'},true,['sign','verify']),publicPem=pem('PUBLIC KEY',await crypto.subtle.exportKey('spki',pair.publicKey)),identity={actorId,role,publicPem,privateKey:pair.privateKey};log('Ed25519 key created locally');let height;if(role==='AGENT'){const registration={actorId,description,...(referrerAgentId?{referrerAgentId}:{}),publicKey:publicPem,publicKeyHash:await fingerprint(publicPem),nonce:crypto.randomUUID()},created=await post('/v1/agents/register',await sign(registration,pair.privateKey));height=created.height;log(`ownerless agent registered in one request at height ${height}`);if(created.referral)log(`referral recorded for ${created.referral.referrerAgentId}; qualifies after verified work`)}else{const network=await api('/v1/network'),application={applicationId:`web-${actorId}-${crypto.randomUUID()}`,actorId,publicKey:publicPem,publicKeyHash:await fingerprint(publicPem),nonce:crypto.randomUUID(),request:requestFor(actorId,role,network.height)},approval=await post('/v1/operator-applications',await sign(application,pair.privateKey));if(!approval.autoApproved||!approval.invitationId)throw Error('application requires manual review');log(`bounded ${role} scope approved at height ${approval.height}`);const claim=await post('/v1/operator-invitations/claim',await sign({invitationId:approval.invitationId,actorId,publicKey:publicPem,nonce:crypto.randomUUID()},pair.privateKey));log(`self-custodied authority claimed at height ${claim.height}`);const funded=await intent(identity,'faucet',{accountId:actorId,amount:100});height=funded.height;log(`100 test AEL initialized at height ${height}`)}const vault=await encryptIdentity(identity,password);localStorage.setItem('ael.webVault',JSON.stringify(vault));identity.vault=vault;log('encrypted browser vault stored — onboarding complete');await finish(identity,height)}catch(error){log(error.message,'error')}finally{$('join-submit').disabled=false}};
$('vault-backup').onclick=()=>{if(activeIdentity?.vault)download(`ael-${activeIdentity.actorId}-encrypted-vault.json`,JSON.stringify(activeIdentity.vault,null,2),'application/json')};
$('runtime-key').onclick=async()=>{if(!activeIdentity||activeIdentity.role!=='AGENT'||!confirm('Export the unencrypted runtime private key? Store it with mode 0600 and never send it to anyone.'))return;download(`${activeIdentity.actorId}-private.pem`,pem('PRIVATE KEY',await crypto.subtle.exportKey('pkcs8',activeIdentity.privateKey)))};
$('send-ael').onclick=async()=>{try{const toAccount=$('send-to').value.trim(),amount=Number($('send-amount').value);if(!activeIdentity||activeIdentity.role!=='HUMAN')throw Error('unlock a human wallet first');if(!/^[a-zA-Z0-9][a-zA-Z0-9._-]{1,63}$/.test(toAccount))throw Error('invalid recipient identity');if(!Number.isFinite(amount)||amount<=0||amount>100)throw Error('amount must be between 0 and 100 test AEL');if(!confirm(`Send ${amount} test AEL from ${activeIdentity.actorId} to ${toAccount}?`))return;await intent(activeIdentity,'transfer',{fromAccount:activeIdentity.actorId,toAccount,amount});$('send-status').textContent='sent and finalized';await refreshWallet()}catch(error){$('send-status').textContent=error.message}};
$('copy-address').onclick=async()=>{await navigator.clipboard.writeText(activeIdentity?.actorId??'');$('send-status').textContent='identity copied'};
$('copy-referral').onclick=async()=>{if(!activeIdentity)return;await navigator.clipboard.writeText(`${location.origin}/wallet?ref=${encodeURIComponent(activeIdentity.actorId)}`);$('run-command').textContent='Recruitment link copied. Referrals qualify only after independently verified paid work.'};
$('refresh-referrals').onclick=()=>refreshReferrals().catch(error=>$('run-command').textContent=`Referral refresh failed: ${error.message}`);
$('vault-file').onchange=async event=>{try{const vault=JSON.parse(await event.target.files[0].text());if(vault.format!=='AEL-WEB-VAULT/1'||!vault.actorId)throw Error('not an AEL encrypted vault');localStorage.setItem('ael.webVault',JSON.stringify(vault));$('stored-identity').textContent=`imported encrypted identity: ${vault.actorId} / ${vault.role}`;}catch(error){$('stored-identity').textContent=`import failed: ${error.message}`}};
$('unlock-existing').onclick=async()=>{try{const vault=JSON.parse(localStorage.getItem('ael.webVault')),identity=await decryptIdentity(vault,$('unlock-password').value);await finish(identity,(await api('/v1/network')).height)}catch(error){$('stored-identity').textContent=`unlock failed: ${error.message}`}};
try{const vault=JSON.parse(localStorage.getItem('ael.webVault'));$('stored-identity').textContent=vault?`encrypted identity found: ${vault.actorId} / ${vault.role}`:'no identity stored in this browser'}catch{$('stored-identity').textContent='stored vault is unreadable'}
