const $all=selector=>[...document.querySelectorAll(selector)],get=async path=>{const response=await fetch(path),data=await response.json();if(!response.ok)throw Error(data.error);return data},text=(selector,value)=>$all(selector).forEach(node=>node.textContent=value);
const rows=(selector,records,columns)=>{const body=document.querySelector(selector);body.replaceChildren(...records.map(record=>{const row=document.createElement('tr');for(const column of columns){const cell=document.createElement('td');cell.textContent=String(column(record)??'—');row.append(cell)}return row}))};
const route=location.pathname;for(const link of $all('nav a'))if(link.getAttribute('href')===route)link.classList.add('active');
try{const [health,network,token,readiness]=await Promise.all([get('/health'),get('/v1/network'),get('/v1/token'),get('/v1/mainnet/readiness')]);text('[data-health]','online');$all('[data-health]').forEach(node=>node.classList.add('ok'));text('[data-height]',health.height);text('[data-finality]',`${network.finality?.votes??0}/${network.validatorCount}`);text('[data-chain-id]',token.chainId);text('[data-readiness-passed]',readiness.summary.passed);text('[data-readiness-total]',readiness.summary.total);text('[data-home-state]',JSON.stringify({chain_id:token.chainId,height:network.height,state_root:network.finality?.stateHash,validators:network.validatorCount,consensus:network.mode??'LOCAL_REPLICA_SIMULATOR',mainnet_ready:readiness.ready,blocking_gates:readiness.summary.blocking.length,profile:'AEL/0.13'},null,2));}catch{ text('[data-health]','offline') }
if(document.body.dataset.page==='network')try{const [network,nodes]=await Promise.all([get('/v1/network'),get('/v1/nodes')]);rows('[data-nodes]',nodes.nodes,[node=>node.validatorId,node=>node.status,node=>node.heartbeat?.status??'registered',node=>node.heartbeat?.observedHeight,node=>node.heartbeat?.nodeVersion]);document.querySelector('[data-network-json]').textContent=JSON.stringify(network,null,2)}catch(error){document.querySelector('[data-network-json]').textContent=error.message}
if(document.body.dataset.page==='token')try{const[token,tokenomics]=await Promise.all([get('/v1/token'),get('/v1/tokenomics')]);for(const[key,value]of Object.entries(token)){text(`[data-token-${key}]`,typeof value==='number'?value.toLocaleString():value)}document.querySelector('[data-token-json]').textContent=JSON.stringify(token,null,2);document.querySelector('[data-tokenomics-json]').textContent=JSON.stringify(tokenomics,null,2)}catch{}
if(document.body.dataset.page==='agents')try{const [agents,orders,referralResult]=await Promise.all([get('/v1/agents'),get('/v1/work-orders'),get('/v1/referrals')]),referrals=referralResult.referrals??[];text('[data-agent-count]',agents.length);text('[data-open-work]',orders.filter(order=>order.status==='OPEN').length);text('[data-pending-referrals]',referrals.filter(item=>item.status==='PENDING').length);text('[data-qualified-referrals]',referrals.filter(item=>item.status==='QUALIFIED').length);rows('[data-agents]',agents,[agent=>agent.id,agent=>agent.status,agent=>agent.redeemableReserve,agent=>agent.virtualLiquidity]);rows('[data-referrals]',referrals,[item=>item.referredAgentId,item=>item.referrerAgentId,item=>item.status,item=>item.joinedAtHeight,item=>item.receiptId]);const empty=document.querySelector('[data-no-referrals]');if(empty)empty.hidden=referrals.length!==0}catch{}
if(document.body.dataset.page==='work')try{const orders=await get('/v1/work-orders?status=OPEN&assignmentMode=OPEN_MARKET');text('[data-market-count]',orders.length);text('[data-market-funding]',orders.reduce((sum,order)=>sum+Number(order.fundedAmount||0),0).toLocaleString());rows('[data-open-orders]',orders,[order=>order.orderId,order=>order.title,order=>order.fundedAmount,order=>order.scopeHash,order=>order.createdAtHeight]);const empty=document.querySelector('[data-no-work]');if(empty)empty.hidden=orders.length!==0}catch{}
if(document.body.dataset.page==='blocks')try{const result=await get('/v1/blocks?limit=50');text('[data-chain-valid]',result.chain.valid?'verified':'invalid');text('[data-block-count]',result.chain.blockCount);text('[data-history-start]',result.chain.historyStartHeight??'next commit');rows('[data-blocks]',result.blocks,[block=>block.height,block=>block.transition,block=>block.blockHash,block=>block.stateRoot,block=>block.validatorVotes])}catch(error){text('[data-chain-valid]',error.message)}
