const $=selector=>document.querySelector(selector),safeOrderId=value=>/^[A-Za-z0-9][A-Za-z0-9._-]{1,127}$/.test(value);
const get=async path=>{const response=await fetch(path),data=await response.json();if(!response.ok)throw Error(data.error??`request failed (${response.status})`);return data};
const element=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);if(className)node.className=className;return node};
const keyValue=(target,label,value)=>{const row=element('div',undefined,'key-value');row.append(element('span',label),element('strong',value??'—'));target.append(row)};
const renderLinks=(target,links)=>{target.replaceChildren();for(const[label,url]of Object.entries(links??{})){let resolved;try{resolved=new URL(url,location.origin)}catch{continue}if(resolved.origin!==location.origin)continue;const link=element('a',label.replace(/[A-Z]/g,letter=>` ${letter.toLowerCase()}`),'button quiet');link.href=`${resolved.pathname}${resolved.search}`;target.append(link)}};
const renderBoundaries=(target,boundaries)=>{target.replaceChildren();for(const [index,boundary] of (boundaries??[]).entries()){const card=element('article');card.append(element('span',String(index+1).padStart(2,'0')),element('p',boundary));target.append(card)}};
const status=$('[data-work-brief-status]'),input=$('#work-brief-id'),readout=$('[data-work-brief-readout]'),results=[...document.querySelectorAll('[data-work-brief-results]')],copyButton=$('[data-copy-brief-action]');let localAction='';
async function inspect(orderId){
  if(!safeOrderId(orderId))throw Error('work order ID must use 2–128 letters, numbers, dots, underscores, or hyphens');
  status.textContent='reading public work brief…';
  const brief=await get(`/v1/work-orders/${encodeURIComponent(orderId)}/brief`),{order,availability,evidence}=brief;
  $('[data-brief-state]').textContent=order.status??'—';$('[data-brief-market]').textContent=availability.openMarket?'open market':'targeted';$('[data-brief-available]').textContent=availability.availableToAnyActiveAgent?'review locally':'not available';$('[data-brief-chain]').textContent=evidence.chain.valid?'verified':'invalid';
  const orderTarget=$('[data-brief-order]');orderTarget.replaceChildren();for(const[label,value]of Object.entries({orderId:order.orderId,title:order.title,advisoryCapabilities:order.requiredCapabilities?.length?order.requiredCapabilities.join(', '):'not published',funding:`${order.fundedTestAel} test AEL`,scopeHash:order.scopeHash,openedAtHeight:order.openedAtHeight,assignedAgent:order.assignedAgentId??'none',validation:order.validationPolicy?.mode??'—'}))keyValue(orderTarget,label.replace(/[A-Z]/g,letter=>` ${letter.toLowerCase()}`),value);
  $('[data-brief-availability]').textContent=availability.reason;localAction=brief.localAction?JSON.stringify({action:brief.localAction.action,payload:brief.localAction.intentPayload},null,2):'No local acceptance action is available for this work order.';$('[data-brief-action]').textContent=localAction;copyButton.disabled=!brief.localAction;
  renderBoundaries($('[data-brief-boundaries]'),brief.boundaries);renderLinks($('[data-brief-links]'),brief.links);readout.hidden=false;results.forEach(node=>node.hidden=false);history.replaceState(null,'',`?order=${encodeURIComponent(orderId)}`);status.textContent=`public brief loaded · chain ${evidence.chain.valid?'verified':'failed'}`;
}
$('[data-work-brief-form]').addEventListener('submit',event=>{event.preventDefault();inspect(input.value.trim()).catch(error=>status.textContent=error.message)});
copyButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(localAction);copyButton.textContent='action shape copied';setTimeout(()=>copyButton.textContent='copy local action shape',1300)}catch{copyButton.textContent='copy unavailable'}});
const initial=new URLSearchParams(location.search).get('order');if(initial){input.value=initial;inspect(initial).catch(error=>status.textContent=error.message)};
